### ISSUE TITLE
Adopt a uniform Coding Style for gargoyle-specific code

### ISSUE THREAD

**Issue by rbrito** [ericpaulbishop/gargoyle#185]
Hi.

One of the things that make the Linux kernel have a highly consistent code is their [CodingStyle document](https://www.kernel.org/doc/Documentation/CodingStyle), which has principles that are not really restricted to C, but they can transcend to other languages in a similar fashion, like, for instance, [JavaScript](https://github.com/rwldrn/idiomatic.js/blob/master/readme.md#all-code-in-any-code-base-should-look-like-a-single-person-typed-it-no-matter-how-many-people-contributed).

I propose that, for code specific to gargoyle (i.e., not the code that is regularly imported from other places), we adopt the CodingStyle document from the Linux kernel.

I'm filing this as a bug more as a request-for-comments/declaration of intent, before mass reformatting the code for readability and 

Regards,

Rogério Brito.

**Comment by user501254** [comment]
@ericpaulbishop , you can use markdown within GitHub comments. I guess this is what you meant.

    if(a)
    {
      i=j;
    }

**Comment by fatso83** [comment]
I have no insights as to how the projects structures its code, but if the Gargoyle specific changes were somehow in a folder of its own then enforcing a coding guideline through linters would be super-simple.
