### ISSUE TITLE
Gargoyle 1.70 VPN issue between client and hosts behind vpn

### ISSUE THREAD

**Issue by mcaptur** [ericpaulbishop/gargoyle#330]
Vpn connects successfully from client and route is added, however client cannot access hosts behind vpn server (see http://www.gargoyle-router.com/phpbb/viewtopic.php?f=6&t=6562&p=26594#p26578).

problem is solved by adding  

config forwarding 'lan_vpn_forwarding'
        option src 'vpn'
        option dest 'lan'

to /etc/config/firewall

**Comment by ericpaulbishop** [comment]
This should be fixed in 73cb9f51ed1bf2b25f3215eb0703c8b26dfab6fe

Thanks for reporting this.
