### ISSUE TITLE
Quota Upload QoS Class

### ISSUE THREAD

**Issue by lantis1008** [ericpaulbishop/gargoyle#339]
Hey Eric,

when using a quota rule that bumps someone into an upload QoS class when they exceed their limit, the QoS class doesn't seem to stick properly.
download rule applies as expected.
i had a dig through the code but quotas stuff is too spread out for me to easily find where the error is. i assume its in the firewall_util, although it looked ok to me.

**Comment by ericpaulbishop** [comment]
Fixed in 1f44a0c4 which I just committed about 2 hours ago.
