### ISSUE TITLE
Can't login to web management page

### ISSUE THREAD

**Issue by user501254** [ericpaulbishop/gargoyle#344]
**Upgraded to Android Lollipop 5.0.2, can't access router management page.**
After putting in the password and tapping enter, page gets stuck with the overlay message "please wait while settings are being applied".
It's working fine on other platforms.

Gargoyle Router firmware 1.6 stable
TP-Link TL-WR740N Wireless Router 
Chrome 42.0.2311.109

**Comment by lantis1008** [comment]
Once you hit login, let it spin for 30 seconds, then try to manually navigate to "http://192.168.1.1/overview.sh"

**Comment by user501254** [comment]
That didn't work. I am greeted back with a login page.

**Comment by lantis1008** [comment]
If it works fine on other platforms I'd say it's just a peculiar bug. 
1.7.x that you can download from the forums has updated the type of web server used which may or may not help your problem if you are interested. 
It is part of the "unstable" branch but there are very few complaints about it. 
Head over to https://www.gargoyle-router.com/phpbb/viewtopic.php?f=14&t=6991

**Comment by user501254** [comment]
I  would rather wait for the stable build :yum:

**Comment by user501254** [comment]
I confirm thing to be working properly on the latest stable release 1.8.0.
Router management page can be accessed through Chrome on a mobile device.
