### ISSUE TITLE
libipt_bandwidth.c compile error

### ISSUE THREAD

**Issue by hero18688** [ericpaulbishop/gargoyle#355]
mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -mips16 -minterlink-mips16 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/home/workingdir/gargoyle/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/iptables-1.4.21/include -I/home/workingdir/gargoyle/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/linux-3.18.17/user_headers/include -ffunction-sections -fdata-sections -DNO_LEGACY   -o libipt_bandwidth.oo -c libipt_bandwidth.c;
libipt_bandwidth.c: In function 'param_problem_exit_error':
libipt_bandwidth.c:537:3: error: format not a string literal and no format arguments [-Werror=format-security]
   xtables_error(PARAMETER_PROBLEM, msg);
   ^
cc1: some warnings being treated as errors
make[6]: *** [libipt_bandwidth.oo] Error 1
make[6]: Leaving directory `/home/workingdir/gargoyle/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/iptables-1.4.21/extensions'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory `/home/workingdir/gargoyle/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/iptables-1.4.21'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/home/workingdir/gargoyle/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/iptables-1.4.21'
make[3]: *** [/home/workingdir/gargoyle/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/iptables-1.4.21/.built] Error 2
make[3]: Leaving directory `/home/workingdir/gargoyle/package/network/utils/iptables'
make[2]: *** [package/network/utils/iptables/compile] Error 2
make[2]: Leaving directory `/home/workingdir/gargoyle'
make[1]: *** [/home/workingdir/gargoyle/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/workingdir/gargoyle'
make: *** [world] 错误 2
make j=5 V=99  196.19s user 44.97s system 31% cpu 12:48.77 total
➜  981213_150701 git:(master) ✗

**Comment by wongsyrone** [comment]
Changes by myself, and not for sure
```diff
diff --git a/package/network/utils/iptables/patches/650-custom_netfilter_match_modules.patch b/package/network/utils/iptables/patches/650-custom_netfilter_match_modules.patch
index 534dbae..0aef0d8 100644
--- a/package/network/utils/iptables/patches/650-custom_netfilter_match_modules.patch
+++ b/package/network/utils/iptables/patches/650-custom_netfilter_match_modules.patch
@@ -542,7 +542,7 @@
 +static void param_problem_exit_error(char* msg)
 +{
 +	#ifdef xtables_error
-+		xtables_error(PARAMETER_PROBLEM, msg);
++		xtables_error(PARAMETER_PROBLEM, "%s", msg);
 +	#else
 +		exit_error(PARAMETER_PROBLEM, msg);
 +	#endif
@@ -1008,7 +1008,7 @@
 +static void param_problem_exit_error(char* msg)
 +{
 +	#ifdef xtables_error
-+		xtables_error(PARAMETER_PROBLEM, msg);
++		xtables_error(PARAMETER_PROBLEM, "%s", msg);
 +	#else
 +		exit_error(PARAMETER_PROBLEM, msg);
 +	#endif
@@ -1690,7 +1690,7 @@
 +static void param_problem_exit_error(char* msg)
 +{
 +	#ifdef xtables_error
-+		xtables_error(PARAMETER_PROBLEM, msg);
++		xtables_error(PARAMETER_PROBLEM, "%s", msg);
 +	#else
 +		exit_error(PARAMETER_PROBLEM, msg);
 +	#endif
@@ -2541,7 +2541,7 @@
 +static void param_problem_exit_error(char* msg)
 +{
 +	#ifdef xtables_error
-+		xtables_error(PARAMETER_PROBLEM, msg);
++		xtables_error(PARAMETER_PROBLEM, "%s", msg);
 +	#else
 +		exit_error(PARAMETER_PROBLEM, msg);
 +	#endif
```

**Comment by hero18688** [comment]
fixed,thanks
