### ISSUE TITLE
Fails to connect to openssh Server: Bad hostkey signature

### ISSUE THREAD

**Issue by asarubbo** [ericpaulbishop/gargoyle#363]
While I try to connect from the router to an openssh server I receive the error:
ssh: Connection to root@HOST exited: Bad hostkey signature.

This error is discussed here: http://www.dd-wrt.com/phpBB2/viewtopic.php?p=966242
And there is a patch here: http://patchwork.ozlabs.org/patch/462182/

Is possible have this patch pulled in or have a newer dropbear?

**Comment by ericpaulbishop** [comment]
This should now be fixed in 1.9.0
