### ISSUE TITLE
1.8.0 WiFi connections dropped/rejected after stable operation

### ISSUE THREAD

**Issue by nworbnhoj** [ericpaulbishop/gargoyle#369]
After a period (2-24hrs) of stable operation, WiFi connections are dropped and new connections are not possible. `/etc/init.d/network restart` resolves the issue temporarily.

This behaviour has been reported with 1.8.0 on TL-WDR3600 & TL-1043ND-V2
http://www.gargoyle-router.com/phpbb/viewtopic.php?f=3&t=7431&start=30#p31040
http://www.gargoyle-router.com/phpbb/viewtopic.php?f=8&t=7508#p31467
and appears to abate when Guest network is disabled
http://www.gargoyle-router.com/phpbb/viewtopic.php?f=8&t=7508#p31517

Typical log entries:

    Mon Sep 14 21:01:13 2015 daemon.info hostapd: wlan1: STA mm:mm:aa:aa:cc:cc IEEE 802.11: authenticated
    Mon Sep 14 21:01:13 2015 daemon.info hostapd: wlan1: STA mm:mm:aa:aa:cc:cc IEEE 802.11: associated (aid 1)
    Mon Sep 14 21:01:21 2015 daemon.info hostapd: wlan1: STA mm:mm:aa:aa:cc:cc IEEE 802.11: deauthenticated due to local deauth request

**Comment by ericpaulbishop** [comment]
Does this happen on stock OpenWRT Barrier Breaker firmware, with the same network configuration?

My policy is to update the wifi drivers to the latest version available on OpenWRT but I lack the time/expertise/resources to dive into the enormously complex code base of wireless drivers in linux and find any potential bugs there.

**Comment by nworbnhoj** [comment]
Unfortunately, I have no experience with OpenWRT (except via Gargoyle) and would not be confident that I could replicate "the same network configuration" to the extent that a definitive answer could be achieved - particularly since the Guest network functionality appears to be implicated (ie the ebtables set-up would need to be replicated).

I have now confirmed WiFi stability for some days with the Guest network disabled on both the TL-WDR3600 and TL-1043ND-V2. The instability with the WiFi Guest network enabled is a little different on the two devices. On the TL-1043ND-V2 all of the WiFi SSID's become inoperative. On the TL-WDR3600 only the Guest WiFi becomes inoperative while the main WiFi SSIDs remain functional.

**Comment by Firefly1337** [comment]
Bump.
I think I have the same issue:
http://www.gargoyle-router.com/phpbb/viewtopic.php?f=11&t=7052

My current workaround is to set the router to reboot itself every day.

**Comment by gwlim** [comment]
OpenWRT has this issues as well especially when iDevices are in the network.
Solution is to add
option disassoc_low_ack '0'

**Comment by ericpaulbishop** [comment]
I am going to close this issue for now. 1.9.0 is out with the latest wireless drivers and some fixes, and I advise anyone still having this issue to migrate to 1.9.0.
