### ISSUE TITLE
Archer V2 Wi-fi Channels Reversed

### ISSUE THREAD

**Issue by ioguy** [ericpaulbishop/gargoyle#392]
Archer C7 V2 in 1.8.X

In the channel config, the 2.4Ghz channel select shows 5Ghz channels and vise versa. 
5Ghz channels: 1-11
2.4Ghz channels: 36-165

If I try to change 5Gz to 40Mhz its available channels dropdown goes blank.

Currently showing 2.4Gz on channel 1 and 5Ghz enabled.
Wi-Fi snoop shows channel 6 and no 5Ghz.

**Comment by lantis1008** [comment]
Can you please post the outputs of
`iw phy0 info`
`iw phy1 info`
and 
`cat /tmp/cached_basic_vars`

Cheers.

**Comment by ioguy** [comment]
phy0:
Wiphy phy0
        max # scan SSIDs: 16
        max scan IEs length: 199 bytes
        Retry short limit: 7
        Retry long limit: 4
        Coverage class: 0 (up to 0m)
        Device supports AP-side u-APSD.
        Available Antennas: TX 0 RX 0
        Supported interface modes:
                 * IBSS
                 * managed
                 * AP
                 * AP/VLAN
                 * monitor
                 * P2P-client
                 * P2P-GO
        Band 2:
                Capabilities: 0x19e3
                        RX LDPC
                        HT20/HT40
                        Static SM Power Save
                        RX HT20 SGI
                        RX HT40 SGI
                        TX STBC
                        RX STBC 1-stream
                        Max AMSDU length: 7935 bytes
                        DSSS/CCK HT40
                Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
                Minimum RX AMPDU time spacing: 8 usec (0x06)
                HT TX/RX MCS rate indexes supported: 0-23
                VHT Capabilities (0x338001b2):
                        Max MPDU length: 11454
                        Supported Channel Width: neither 160 nor 80+80
                        RX LDPC
                        short GI (80 MHz)
                        TX STBC
                        RX antenna pattern consistency
                        TX antenna pattern consistency
                VHT RX MCS set:
                        1 streams: MCS 0-9
                        2 streams: MCS 0-9
                        3 streams: MCS 0-9
                        4 streams: not supported
                        5 streams: not supported
                        6 streams: not supported
                        7 streams: not supported
                        8 streams: not supported
                VHT RX highest supported: 0 Mbps
                VHT TX MCS set:
                        1 streams: MCS 0-9
                        2 streams: MCS 0-9
                        3 streams: MCS 0-9
                        4 streams: not supported
                        5 streams: not supported
                        6 streams: not supported
                        7 streams: not supported
                        8 streams: not supported
                VHT TX highest supported: 0 Mbps
                Frequencies:
                        * 5180 MHz [36] (17.0 dBm)
                        * 5200 MHz [40] (17.0 dBm)
                        * 5220 MHz [44] (17.0 dBm)
                        * 5240 MHz [48] (17.0 dBm)
                        * 5260 MHz [52] (23.0 dBm) (no IR, radar detection)
                          DFS state: usable (for 752039 sec)
                          DFS CAC time: 60000 ms
                        * 5280 MHz [56] (23.0 dBm) (no IR, radar detection)
                          DFS state: usable (for 752039 sec)
                          DFS CAC time: 60000 ms
                        * 5300 MHz [60] (23.0 dBm) (no IR, radar detection)
                          DFS state: usable (for 752039 sec)
                          DFS CAC time: 60000 ms
                        * 5320 MHz [64] (23.0 dBm) (no IR, radar detection)
                          DFS state: usable (for 752039 sec)
                          DFS CAC time: 60000 ms
                        * 5500 MHz [100] (disabled)
                        * 5520 MHz [104] (disabled)
                        * 5540 MHz [108] (disabled)
                        * 5560 MHz [112] (disabled)
                        * 5580 MHz [116] (disabled)
                        * 5600 MHz [120] (disabled)
                        * 5620 MHz [124] (disabled)
                        * 5640 MHz [128] (disabled)
                        * 5660 MHz [132] (disabled)
                        * 5680 MHz [136] (disabled)
                        * 5700 MHz [140] (disabled)
                        * 5745 MHz [149] (30.0 dBm)
                        * 5765 MHz [153] (30.0 dBm)
                        * 5785 MHz [157] (30.0 dBm)
                        * 5805 MHz [161] (30.0 dBm)
                        * 5825 MHz [165] (30.0 dBm)
        valid interface combinations:
                 * #{ AP } <= 8,
                   total <= 8, #channels <= 1, STA/AP BI must match
        HT Capability overrides:
                 * MCS: ff ff ff ff ff ff ff ff ff ff
                 * maximum A-MSDU length
                 * supported channel width
                 * short GI for 40 MHz
                 * max A-MPDU length exponent
                 * min MPDU start spacing

phy1:
Wiphy phy1
        max # scan SSIDs: 4
        max scan IEs length: 2257 bytes
        Retry short limit: 7
        Retry long limit: 4
        Coverage class: 0 (up to 0m)
        Device supports AP-side u-APSD.
        Device supports T-DLS.
        Available Antennas: TX 0x7 RX 0x7
        Configured Antennas: TX 0x7 RX 0x7
        Supported interface modes:
                 * IBSS
                 * managed
                 * AP
                 * AP/VLAN
                 * WDS
                 * monitor
                 * mesh point
                 * P2P-client
                 * P2P-GO
        Band 1:
                Capabilities: 0x11ef
                        RX LDPC
                        HT20/HT40
                        SM Power Save disabled
                        RX HT20 SGI
                        RX HT40 SGI
                        TX STBC
                        RX STBC 1-stream
                        Max AMSDU length: 3839 bytes
                        DSSS/CCK HT40
                Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
                Minimum RX AMPDU time spacing: 8 usec (0x06)
                HT TX/RX MCS rate indexes supported: 0-23
                Frequencies:
                        * 2412 MHz [1] (30.0 dBm)
                        * 2417 MHz [2] (30.0 dBm)
                        * 2422 MHz [3] (30.0 dBm)
                        * 2427 MHz [4] (30.0 dBm)
                        * 2432 MHz [5] (30.0 dBm)
                        * 2437 MHz [6] (30.0 dBm)
                        * 2442 MHz [7] (30.0 dBm)
                        * 2447 MHz [8] (30.0 dBm)
                        * 2452 MHz [9] (30.0 dBm)
                        * 2457 MHz [10] (30.0 dBm)
                        * 2462 MHz [11] (30.0 dBm)
                        * 2467 MHz [12] (disabled)
                        * 2472 MHz [13] (disabled)
                        * 2484 MHz [14] (disabled)
        valid interface combinations:
                 * #{ managed, WDS } <= 2048, #{ AP, mesh point } <= 8, #{ P2P-client, P2P-GO } <= 1, #{ IBSS } <= 1,
                   total <= 2048, #channels <= 1, STA/AP BI must match
        HT Capability overrides:
                 * MCS: ff ff ff ff ff ff ff ff ff ff
                 * maximum A-MSDU length
                 * supported channel width
                 * short GI for 40 MHz
                 * max A-MPDU length exponent
                 * min MPDU start spacing

vars:
var isBcm94704 = false;
var allLanMacs = [];
allLanMacs.push("14:cc:20:d4:ff:85");
allLanMacs.push("14:cc:20:d4:ff:86");
var wifiDevG=uciWirelessDevs.length > 0 ? uciWirelessDevs[0] : "";
var wifiDevA="";
var wirelessDriver="mac80211";
var mac80211Channels = [];
var mac80211ChFreqs = [];
var mac80211ChPwrs = [];
var nextCh=[];
var wifiN = true ;
var dualBandWireless=true;
nextCh     = [];
nextChFreq = [];
nextChPwr  = [];
wifiDevG="radio0";
nextCh.push(36); nextChFreq[36] = "5180MHz"; nextChPwr[36] = 17;
nextCh.push(40); nextChFreq[40] = "5200MHz"; nextChPwr[40] = 17;
nextCh.push(44); nextChFreq[44] = "5220MHz"; nextChPwr[44] = 17;
nextCh.push(48); nextChFreq[48] = "5240MHz"; nextChPwr[48] = 17;
nextCh.push(149); nextChFreq[149] = "5745MHz"; nextChPwr[149] = 30;
nextCh.push(153); nextChFreq[153] = "5765MHz"; nextChPwr[153] = 30;
nextCh.push(157); nextChFreq[157] = "5785MHz"; nextChPwr[157] = 30;
nextCh.push(161); nextChFreq[161] = "5805MHz"; nextChPwr[161] = 30;
nextCh.push(165); nextChFreq[165] = "5825MHz"; nextChPwr[165] = 30;
mac80211Channels["G"] = nextCh ;
mac80211ChFreqs["G"]  = nextChFreq ;
mac80211ChPwrs["G"]   = nextChPwr ;
nextCh     = [];
nextChFreq = [];
nextChPwr  = [];
wifiDevA="radio1";
nextCh.push(1); nextChFreq[1] = "2412MHz"; nextChPwr[1] = 30;
nextCh.push(2); nextChFreq[2] = "2417MHz"; nextChPwr[2] = 30;
nextCh.push(3); nextChFreq[3] = "2422MHz"; nextChPwr[3] = 30;
nextCh.push(4); nextChFreq[4] = "2427MHz"; nextChPwr[4] = 30;
nextCh.push(5); nextChFreq[5] = "2432MHz"; nextChPwr[5] = 30;
nextCh.push(6); nextChFreq[6] = "2437MHz"; nextChPwr[6] = 30;
nextCh.push(7); nextChFreq[7] = "2442MHz"; nextChPwr[7] = 30;
nextCh.push(8); nextChFreq[8] = "2447MHz"; nextChPwr[8] = 30;
nextCh.push(9); nextChFreq[9] = "2452MHz"; nextChPwr[9] = 30;
nextCh.push(10); nextChFreq[10] = "2457MHz"; nextChPwr[10] = 30;
nextCh.push(11); nextChFreq[11] = "2462MHz"; nextChPwr[11] = 30;
mac80211Channels["A"] = nextCh ;
mac80211ChFreqs["A"]  = nextChFreq ;
mac80211ChPwrs["A"]   = nextChPwr ;

**Comment by lantis1008** [comment]
Great! Exactly what I needed. 
So the basic convention is that the 2.4 radio is labelled "0" and the 5 is "1". Your device seems to be backwards.
I'll take a look into why the check doesn't detect this, but I'm currently on a coding break until next week. 

Cheers

**Comment by lantis1008** [comment]
Also by any chance have you tried 1.9.0 to see if the behaviour is the same?

**Comment by ericpaulbishop** [comment]
I think this should be fixed in the latest wifiAC changes from Lantis I just merged, so (at least for now) I'm closing this issue.
