### ISSUE TITLE
Images for some routers fail to build

### ISSUE THREAD

**Issue by wodim** [ericpaulbishop/gargoyle#405]
As of recently, images for some routers (those with a 4M flash) fail to build because the resulting images are too big.

In my case, it is the TL-WR741ND image not being generated (the one I need), but I can imagine lots of them are also failing.

**Comment by ericpaulbishop** [comment]
Do you have any suggestions on what to remove?

I've already spent weeks looking for things to take out when I migrated to Chaos Calmer, where the build size increased dramatically. There's not much left to remove, but I am very open to suggestions.

**Comment by wodim** [comment]
Is it possible to get a list of packages that will be built for a certain router, and also to know what's the size of the resulting image and how big it should be (i.e. for how much it overflows)?

In any case, I don't know much of openwrt. Isn't it possible to change the compiler flags in a way that makes it generate smaller binaries?

**Comment by ericpaulbishop** [comment]
[1] There is a list of included packages in  ls ~/gargoyle/targets/ar71xx/profiles/default/config, though you'll have to figure out the sizes yourself. Part of the issue with sizes is that the size of the package is larger than the amount you'll save by removing it, because it gets gzipped in the firmware image, and the gizipped size is what you save. Feel free to have a look and make recommendations.

[2] No.

**Comment by obsy** [comment]
Eric:
1. change nls-base from =y to =m
2. remove bridge package. I used bridge from BusyBox with small patch for showmacs

**Comment by obsy** [comment]
3. Make new theme, lightest, without images.

**Comment by ericpaulbishop** [comment]
[1] and [2] suggestions by obsy above are now implemented, thanks.

**Comment by wodim** [comment]
This is still not fixed, those images are still failing to generate.

**Comment by obsy** [comment]
Eric, next:
- resloveip to =m, not used by any script
- libnfnetlink to =m, used only by miniupnpd
- libmnl to =m

And select kmod-pptp/kmod-gre/kmod-tun as =m, add these to plugins openvpn/pptp, remove dependency from gargoyle-firewall-util

**Comment by wodim** [comment]
Please reopen this. This is not fixed.

**Comment by lantis1008** [comment]
What else would you suggest removing?

**Comment by wodim** [comment]
I can't suggest anything because I haven't got a clue about this stuff, but
I think this (critical, in my opinion) bug should remain open for as long
as it exists.

**Comment by lantis1008** [comment]
the last 4MB image I generated was 4.1MB. It's not even a game of a few kilobytes anymore we are talking at least 300kB to remove to get a plausible image. 
To put it in perspective, stripping the gargoyle firmware of its theme related images only saves 14% of that goal.

**Comment by wodim** [comment]
How much would be saved if you removed the web interface altogether? I know
it's not a solution for this specific issue but I really, really need a
more recent image.

**Comment by ericpaulbishop** [comment]
I'm beginning to think that the logical strategy is to merely drop support for 4M routers. We've already removed all the obvious things, and it seems likely that future releases of OpenWRT are going to be even bigger than this. It's already close to impossible, and next time around it's going to be completely impossible. It may be time...

**Comment by obsy** [comment]
IMO  +1.
