### ISSUE TITLE
[rfc] Buttons

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#407]
016-ar71xx-button-hotplug.patch
017-ar71xx-button-handlers.patch

Should be removed? All buttons handler are in /etc/rc.button in CC, so we should not duplicate these functions,  gargoyle also supports other platforms as mvenu or ramips.

**Comment by ericpaulbishop** [comment]
This should now be addressed in 3f7f810aaf2e78335b2781a675b744653eb23e23
