### ISSUE TITLE
Fails to compile: Package download - 404 error

### ISSUE THREAD

**Issue by stopspazzing** [ericpaulbishop/gargoyle#422]
Tried twice, everything is fine until you hit ca-certificates and then 404 error, there are 2-3 other packages that fail afterwards ultimately leading to the whole compile to fail since files cant be downloaded. Can you verify the packages are pointing to correct location to download the needed files?

**Comment by ericpaulbishop** [comment]
Should now be fixed, thanks for pointing this out.
