### ISSUE TITLE
IMQ crash and system reboot with high traffic, please update the IMQ patch.

### ISSUE THREAD

**Issue by hc313** [ericpaulbishop/gargoyle#425]
I have also met the crash, and found the same issue in Gargoyle Forum: https://gargoyle-router.com/phpbb/viewtopic.php?f=12&t=7292.
When I browse the imq github, I found it https://github.com/imq/linuximq/issues/30, and give the solution at https://github.com/imq/linuximq/commit/ce7662597b926983da4626c04917c3d24eb32802
Please update the kernel 3.18 IMQ patch.

**Comment by lantis1008** [comment]
@ericpaulbishop 
i'm taking a look at this, i think it is important to add.
i've done a diff on what you already have versus these changes

https://www.diffchecker.com/g9wvdrkr

pretty simple changes mostly, but before i do anything just wanted to double check:
Lines 914-1263 were added by you and are required?
Lines 1365-1378 were modified by you and are required? i see you commented out the original lines.
Line 1525, do you make use of this?
and then the last 200 or so lines are another patch by you and required i assume.

**Comment by hc313** [comment]
Lines 914-1263 and Lines 1365-1378 was add by gargoyle.
Line 1525 is the ori kernel of differernet version diff.

**Comment by lantis1008** [comment]
@hc313
You're saying that line 1525 is no longer required?

**Comment by lantis1008** [comment]
Bumping this @ericpaulbishop
Happy to do the leg work just would like you to once over my assumptions in the previous comment.

**Comment by ericpaulbishop** [comment]
Yes, that looks right, please go ahead an implement this. It would be very helpful.

Very sorry for slow replies/merging of pull requests lately -- I've been overwhelmed by several other things lately.

**Comment by lantis1008** [comment]
Will do.

**Comment by lantis1008** [comment]
Really struggling with this one Eric. 
If you get a chance you may have better luck than I. 
I'll keep looking though.
