### ISSUE TITLE
Change plugin root can cause disk full

### ISSUE THREAD

**Issue by nworbnhoj** [ericpaulbishop/gargoyle#426]
When plugin root is changed, the existing plugins directory is blindly moved to the new target drive. If there is insufficient space on the target drive the process fails badly mid-stream leaving the target drive full. If moving from USB Storage back to the Root Drive then the failure is particularly disruptive.

The Gargoyle admin needs to be  
 - alerted that there is unsufficient space on the desired target drive
 - prevented from proceeding
 - invited to select an alternate target or uninstall plugins to resolve the issue

**Comment by ericpaulbishop** [comment]
I believe this has now been merged, so I'm closing the issue -- thank you for both finding and fixing the problem!
