### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by wodim** [ericpaulbishop/gargoyle#439]
Package kmod-ipt-layer7 is missing dependencies for the following libraries:
    nf_conntrack.ko
    make[4]: *** [/home/vagrant/gargoyle/custom-src/bin/ar71xx/packages/base/kmod-ipt-layer7_3.18.23-1-223e3fdd27db9122f3c52a76cf3816a1_ar71xx.ipk] Error 1
    make[4]: Leaving directory `/home/vagrant/gargoyle/custom-src/package/kernel/linux'
    make[3]: *** [package/kernel/linux/compile] Error 2
    make[3]: Leaving directory `/home/vagrant/gargoyle/custom-src'
    make[2]: *** [/home/vagrant/gargoyle/custom-src/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile] Error 2
    make[2]: Leaving directory `/home/vagrant/gargoyle/custom-src'
    make[1]: *** [world] Error 2
    make[1]: Leaving directory `/home/vagrant/gargoyle/custom-src'

**Comment by obsy** [comment]
See https://github.com/ericpaulbishop/gargoyle/pull/438

**Comment by wodim** [comment]
Oh.
