### ISSUE TITLE
Table "Connected Wireless Hosts" Blank

### ISSUE THREAD

**Issue by user501254** [ericpaulbishop/gargoyle#441]
"Connected Wireless Hosts" table under Connected Hosts page (http://192.168.1.1/hosts.sh) is blank even when there are multiple active wireless devices on the router.

Gargoyle Version: 1.9.0
Model: TP-Link TL-WR740N/ND v4

**Comment by lantis1008** [comment]
Fixed in 1.9.X. Please use the latest version.
