### ISSUE TITLE
The list of the current connections is incorrect.

### ISSUE THREAD

**Issue by asarubbo** [ericpaulbishop/gargoyle#452]
I had a setup on my lan which was 192.168.0.1/24

Since I switched to a lan with address 192.168.0.1/21 The list of the current connections are incorrect because the lan address are displayed as WAN

The attached screenshot shows:
-in the first line the connection LAN->LAN which is reported as WAN->LAN
-in the second line the connection LAN->WAN (reported as expected, so fine)

I'm using 1.6.1 on TP-Link TL-WR1043N/ND v1

![garg](https://cloud.githubusercontent.com/assets/4741819/12920197/ec48c908-cf47-11e5-8d11-f2cc172e1b78.png)

**Comment by lantis1008** [comment]
Can you please describe your network structure?
Include all subnets and the physical connections between them.

**Comment by asarubbo** [comment]
Apart explain what 192.168.0.1/21 is, I don't know what you want to know.

The lan address are from 192.168.0.2 to 192.168.7.254
the gateway is 192.168.0.1
the mask is 255.255.248.0

**Comment by lantis1008** [comment]
I'm trying to figure out if the address in question came through the WAN connection. Or are you operating VLANs?

If the address came through the WAN port then the behaviour is expected. 
Does that clarify the information I'm looking for?

**Comment by asarubbo** [comment]
I don't have VLANs.
Instead of a classic lan of /24 I just have a big lan because I need much assignable addresses.

192.168.5.3 is a client of the _LAN_ .
192.165.0.18 is another client of the _LAN_ .

the wan is a public static IP.

**Comment by lantis1008** [comment]
Ok interesting. Your setup isn't conventional by gargoyle standards so I'm sure it's something that wasn't accounted for. 
I'll try and look into it, or perhaps @nworbnhoj can look into it.
Thanks for reporting it.

**Comment by lantis1008** [comment]
Suggest close as of https://github.com/ericpaulbishop/gargoyle/commit/224183e3689338faf6017da2fe13896b9564d8ef
