### ISSUE TITLE
Spectrum Analyser

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#457]
On 1043v1:
```
Uncaught TypeError: Cannot read property '0' of undefined
initialiseAll @ spectrum_analyser.js?1.9.1.1--r48666-:38
(anonymous function) @ spectrum_analyser.sh:99
```
Also - shows wlan 1 (5GHz) that not exists on this router.

**Comment by lantis1008** [comment]
Can I get a 
'iwinfo | grep ESSID'
From you please? Thanks.

**Comment by obsy** [comment]
root@Gargoyle:~# iwinfo | grep ESSID
wlan0     ESSID: "Gargoyle"

**Comment by lantis1008** [comment]
Thanks. 
I'll fix this within 24 hours.
