### ISSUE TITLE
list network in wireless bride

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#513]
@lantis1008 

Default firewall zone:
```
config zone
	option name 'lan'
	list network 'lan'
	option input 'ACCEPT'
	option output 'ACCEPT'
	option forward 'ACCEPT'
```
If wireless bridge selected, latest changes sets firewall like this:

```
config zone
	option name 'lan'
	list network 'lan wwan'
	option input 'ACCEPT'
	option output 'ACCEPT'
	option forward 'ACCEPT'
```

And this is wrong (firewall reports error). Should be 
```
option  network 'lan wwan'
```
 or 
```
list network 'lan'
list network 'wwan'
```
(preffer this).  Please use uci.createListOption before uci.set

**Comment by lantis1008** [comment]
another user had this error but it never happened to me so I couldn't fix.
Thanks.
