### ISSUE TITLE
Bump to OpenWRT CC 15.05.1

### ISSUE THREAD

**Issue by luki92** [ericpaulbishop/gargoyle#518]
Hi,

There are some upgrades to the new release, including kernel (3.18.29 instead of 3.18.23).
It'd be nice to change Makefile to use last relase instead of the old one (from the end of Feb 2016).

This could be done by replacing
a03a846c49c067048cd225d476a7adf91ef8ff03
with 2f9f6244af96bae52acbf5854b82df23bb0f2d3
in build.sh

Additionally in ramips mt7620n:
CONFIG_PACKAGE_kmod-rt2x00-pci=y
CONFIG_PACKAGE_kmod-rt2800-pci=y
CONFIG_PACKAGE_kmod-eeprom-93cx6=y
are all unnecessary and can be switched off, as there is no PCI on this board. The last module is also not necessary - this can generate warning on compilation, but radio works fine without it (tested and confirmed).

**Comment by lantis1008** [comment]
Updating to latest commit caused my build to hang with an image too large error. 
It is still worth investigating.

**Comment by lantis1008** [comment]
@ericpaulbishop 

Suggest we fastforward to "e2d75572cbe197c128e3e13fbb4d142002f6b3bd"
We can then drop patch 028-fix-new-archer-c7-v2

If memory serves correctly, patch 004-fix_postinst_prerm_scripts may no longer apply cleanly.

**Comment by ericpaulbishop** [comment]
Now taken care of -- OpenWRT updated to latest CC  15.01 release.
