### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by nworbnhoj** [ericpaulbishop/gargoyle#519]
@ericpaulbishop please consider adding some trusted collaborators to the gargoyle project.

There is much to be done on the gargoyle development, and a number of people willing to contribute, but evaluation of pull-requests has been protracted in recent times. Adding one or more trusted collaborators, and an understanding that two or more should review pull-requests prior to merging, would speed the process without sacrificing quality unduly. Another approach might be to encourage collaborators to review and merge pull requests for experimental releases but retain sole control over official releases.

I for one have been happy to contribute significant development time to gargoyle - but having #403 in limbo for 4+ months saps my enthusiasm to contribute further.

**Comment by ericpaulbishop** [comment]
First, I apologize that it's taken so long to merge #403, but it's unusual how large that pull request is, and there's some show-stopper bugs (handling of device table without edit feature) as it was submitted. I try to merge small pull requests within a few days.

That said, I'll make you a deal: If both you and Lantis add a note to a pull request where both of you say you think it's ready to be merged as-is, unless I am aware of a show-stopper bug, I will merge it without further testing.

**Comment by nworbnhoj** [comment]
@ericpaulbishop this is a welcome advance that hopefully works well in practice.

To be fair though, I sought feedback on the "handling of device table without edit feature" the day after the original pull request, and received no response. This "show-stopper bug" could have been resolved months ago.
