### ISSUE TITLE
Pass 'noipv6' option to pppd

### ISSUE THREAD

**Issue by m45t3r** [ericpaulbishop/gargoyle#523]
Using a D-Link DSL-2740E in bridge mode (given by ISP) and a TP-Link TL-WR941ND as a (wireless) router, I can't connect via PPPoE without including `option pppd_options 'noipv6'` in `/etc/config/network` file. This is probably thanks to a bad implementation of PPPoE protocol from my modem, however since Gargoyle does not support IPv6 anyway this wouldn't be too much problem. Note that passing only `option ipv6 '0'` does not solve the problem. Tested in both release 1.8.1 and a custom compiled Gargoyle using trunk (removed debug funcionality from kernel, enabled stripped build and removed all USB support from default to make it fit in TL-WR941ND 4MB flash).

With OpenWRT itself, compiled from CC branch (commit 	openwrt/openwrt@ba0cac08164150e74567787251e44b4d0d0dc140) does not have this problem, however LuCI has a option to enable or disable IPv6 negotiation in PPPoE, and this is disabled by default (at least on my build with disabled IPv6 support).

**Comment by lantis1008** [comment]
Under what section do you pass pppd_options noipv6?

**Comment by lantis1008** [comment]
Setting ipv6 to 0 worked for him. No need for pppd_options noipv6. 

I'm going to try to find out the implications of adding both

**Comment by m45t3r** [comment]
This would be my whole `wan` interface:
```
config interface 'wan'
        option ifname 'wan'
        option proto 'pppoe'
        option username 'turbonet@turbonet'
        option password 'gvt25'
        option keepalive '3 5'
        option dns '200.175.89.139 200.175.182.139 8.8.4.4'
        option peerdns '0'
        option ipv6 '0'
        option pppd_options 'noipv6'
```
However an easier way (that OpenWRT alredy uses for default options) is to simple include `noipv6` in `/etc/ppp/options`.

**Comment by lantis1008** [comment]
suggest you remove your password @m45t3r if that is genuine.

**Comment by m45t3r** [comment]
It is. Does not matter because it is the default password for my ISP (so everyone uses the same password).

**Comment by m45t3r** [comment]
I am testing the following patch (it is still compiling in my local fork from Gargoyle-BB, it seems to apply correctly at least):
```
--- a/package/network/services/ppp/files/etc/ppp/options
+++ b/package/network/services/ppp/files/etc/ppp/options
@@ -8,3 +8,4 @@
 maxfail 0
 lcp-echo-failure 5
 lcp-echo-interval 1
+noipv6
```

I put it in `patches-generic` folder. I remember that just setting this option, without modifying `/etc/config/network` worked too.

**Comment by m45t3r** [comment]
@lantis1008 Forget what I said before, `noipv6` didn't make any difference and only `option ipv6 '0'` fixed my connection.

**Comment by lantis1008** [comment]
Cool. 
In that case, I'll add it.

**Comment by m45t3r** [comment]
Just FYI, I got back to OpenWRT and the option to enable or disable IPv6 negotiation in PPPoE actually pass `option ipv6 '1'` to wan interface. And looking at the configuration this make sense:

https://wiki.openwrt.org/doc/uci/network#protocol_pppoe_ppp_over_ethernet
```
Name	Type	Required	Default	Description
ipv6	boolean	no	0	Enable IPv6 on the PPP link
```

So the default for a PPPoE configuration is 0 (all the others use 1). This makes this issue even stranger. In OpenWRT (I got back to Barrier Breaker since my routers only have 4MB of Flash) it seems to connect fast even with explicit requiring IPv6 (that my ISP supports, so I got a valid IPv6 address).

I don't know, maybe this issue is only caused because Gargoyle disables IPv6 from builds?

**Comment by FelixLeo** [comment]
i think adding noipv6  is not the correct way and at my case it doesn't have any effect, 
because there is an override for ipv6 in /lib/netifd/proto/ppp.sh:

ppp_generic_setup() {
        local config="$1"; shift
        json_get_vars ipv6 demand keepalive username password pppd_options pppname
        if [ "$ipv6" = 0 ]; then
                ipv6=""
        # added this lines as Luci GUI completely removes ipv6 parameter when deselected
        elif [ "$ipv6" = "" ]; then # added as Luci GUI completely removes ipv6 parameter when deselected
                ipv6="" # added as Luci GUI completely removes ipv6 parameter when deselected
        else
                ipv6=1
        fi

So you either need to make sure the Luci does keep ipv6 parameter 0 or 1 in any case in /etc/config/network or modify the ppp script as I did which for me was the quick and dirty fix.

**Comment by lantis1008** [comment]
This issue was resolved by passing IPv6 = 0 to the config. 
All users on the forum experiencing this issue reported a success after the change. 

Luci is not part of Gargoyle.
