### ISSUE TITLE
[Proposal] Create a new target for 4MB Flash/no USB routers

### ISSUE THREAD

**Issue by m45t3r** [ericpaulbishop/gargoyle#524]
I was playing with some compile options in OpenWRT CC-branch, and got a build that works stable in my 4MB Flash router (TL-WR941ND). Removing all support for USB, removing debug information and stripping kernel from unecessary code (dropping support for external modules), I could fit a fairly complete build of OpenWRT-CC with LuCI+luci-app-sqm+luci-app-upnp and still have a 512KB `/overlay` partition.

So I tried to port the same configuration file to Gargoyle, and this is the result: [config.zip](https://github.com/ericpaulbishop/gargoyle/files/233184/config.zip)

I could compile a Gargoyle-CC with support for miniupnpd (that was removed from CC because of the size), include all simple plugins (plugins smaller than 5KB, like webshell and initd) and still have a 512KB '/overlay' partition, that is bigger than the 320KB partition from Gargoyle BB. However some things didn't work, like WAN IP in Status page was reporting the LAN IP from my router, instead of the real IP (I am using PPPoE). Most notably, neither *B/W Distribution* and *QoS Distribution* graphics work, probably because I removed all debug support from kernel.

Anyway, my proposal here is to create a new target, say `4mb-nousb` or something, specific to routers with 4MB of Flash and no USB support, that excludes support for some modules to increase the available space, maybe bringing back miniupnpd in official builds and having more space to new features in the future. I think that removing all USB modules and stripping the resulting kernel should be sufficient. Since those routers don't have USB support (officially, anyway), there is no need to care about these builds being non-compatible with PPTP or OpenVPN plugins (that require additional modules), since it wouldn't fit anyway.

**Comment by m45t3r** [comment]
Just FYI, the config.zip file that I attached in the OP have some other options that I activated just for fun, not necessary related with what I described above. In special, this config.zip file activates Hardened build options too (that would be nice to have in Gargoyle too, however this is for another issue).

**Comment by lantis1008** [comment]
i'm going to have a quick look at this. There are some things that are stripped that i think should be kept in if possible... 
I'm giving it a build now to see.

**Comment by m45t3r** [comment]
I created a much better version here: https://github.com/m45t3r/gargoyle/blob/1.9.X_m/targets/ar71xx/profiles/nousb/config

This version may be diff'd with the one from `default/config` since it is based on that, so it should be easier to see what I changed. I am currently used a build based on this config file on my TL-WR941ND, and nothing seems to be broken.

It has an 320KB /overlay, that is the same from official Gargoyle, however it includes various plugins (see [README.md](https://github.com/m45t3r/gargoyle/blob/1.9.X_m/README.md) from repo for details) and I even re-enabled miniupnp since this is important to me. So I think something similar can be done in official builds, maybe not including plugins by default, however having a bigger /overlay + miniupnp back will already be useful.

**Comment by lantis1008** [comment]
I will look again thank you.

**Comment by lantis1008** [comment]
ath_regd is not preferred and not needed.

**Comment by m45t3r** [comment]
Well, I know about ATH_REGD, however it is my personal build so I can add it. However, I read somewhere that ATH_REGD is not necessary anymore to set country for Wi-Fi. Is this true?

Anyway, I did an update to this file to try to shrink it further, however it may be not be necessary. I had some junk files in /www that increased the size of the build. After cleaning it up, I got /overlay of 384KB.

I think that the only changes that is needed to compile is to remove kernel debugging and to strip kernel and libraries. I will try here, can I do a PR if it works?

**Comment by lantis1008** [comment]
It is not necessary correct. 

I've already created a PR.

**Comment by m45t3r** [comment]
What you mean not necessary correct?

I saw your PR, however it is based on the older config file that I created. In the new one I removed more things. However, I think that I can fit miniupnp + default target in 4MB just by removing kernel debugging and stripping kernel/libraries, without disabling other modules (like gargoyle-plugin-tor or gargoyle-plugin-usb-storage). I think if this is the case (the result still has at least 320KB /overlay), it would be easier to maintain, this is why I suggested a new PR.

I can test here if this does work if you want and do the PR myself.

**Comment by lantis1008** [comment]
You do not need ATH REGD. And if you include it I don't think Eric will accept it.

I would not include Tor. That's not a good idea on a low spec device. 
Is there anything wrong with my PR or does it work. ?

**Comment by m45t3r** [comment]
I will not include ATH_REGD. I just include in my personal builds. I know the reason it can't be included.

There is nothing wrong, however it is not right either. For example, since this is based in my older config, there is some unecessary things that can be removed since plugin-gargoyle_usb-storage is disabled. For example, all `kmod-nls-*` can be removed, since this is only used for filesystem encoding support. If you look in my [config](https://github.com/m45t3r/gargoyle/blob/1.9.X_m/targets/ar71xx/profiles/nousb/config) file now, I removed various other packages, including samba, tor, minidlna, etc., since they're not used anyway (no plugin is compiled).

However, I think that maintaining all those modifications will be hard to track, this is why I propose to just keep compiling all these plugins as modules and just disable kernel debugging and enable kernel/libraries strip, that seems to give the most savings anyway. I don't know if this will be sufficient, however I want to try in my machine at least. If it works I can report the results.

**Comment by lantis1008** [comment]
Ok sure. 
I will put my PR on hold and wait for you to update me on your results. 

Is that ok?

**Comment by m45t3r** [comment]
Ok, I am compiling.

**Comment by m45t3r** [comment]
Resulting sysupgrade image for TL-WR941NDv3 is 3538948 bytes in size, so it should have an overlay of 448KB, much better than the 320KB with the default profile (and yeah, I included miniupnpd).

@lantis1008, can you check my PR and see if everything is alright.

Just a note, I (re)activated miniupnpd in both `default_small` and `default` profiles.

**Comment by lantis1008** [comment]
Why have you now created a second PR?
Would you like me to update mine and close yours?

**Comment by m45t3r** [comment]
@lantis1008 just because it is easier than posting a random file here, however you can do what you want. You can just merge my PR or update your PR according to mine.

**Comment by lantis1008** [comment]
Can you please close yours, and I'll browse the changes from your repository? Just link it to me in a comment here. I'll do it tonight when I finish work. 
Thanks for your efforts with this. It will be nice to keep 4mb routers going for a bit longer.

**Comment by m45t3r** [comment]
Ok, it is basically this commit: https://github.com/ericpaulbishop/gargoyle/pull/565/commits/763ace14d4153806924659989a3f34340ac190c1

**Comment by m45t3r** [comment]
@lantis1008, I would recommend you to drop your PR and create a new one based on commit https://github.com/m45t3r/gargoyle/commit/763ace14d4153806924659989a3f34340ac190c1. I think it is easier to import the new changes to try to fix the old config file.

And anyway, commit https://github.com/m45t3r/gargoyle/commit/763ace14d4153806924659989a3f34340ac190c1 brings a small number of changes, this is basically the patch between the `default_small` from https://github.com/m45t3r/gargoyle/commit/763ace14d4153806924659989a3f34340ac190c1 and the `default` from current trunk:

```
diff --git a/config_default b/config_default_small
index c3c44bc..0d82452 100644
--- a/config_default
+++ b/config_default_small
@@ -292,10 +292,10 @@ CONFIG_KERNEL_SWAP=y
 CONFIG_KERNEL_DEBUG_FS=y
 # CONFIG_KERNEL_PERF_EVENTS is not set
 # CONFIG_KERNEL_PROFILING is not set
-CONFIG_KERNEL_KALLSYMS=y
+# CONFIG_KERNEL_KALLSYMS is not set
 # CONFIG_KERNEL_FTRACE is not set
-CONFIG_KERNEL_DEBUG_KERNEL=y
-CONFIG_KERNEL_DEBUG_INFO=y
+# CONFIG_KERNEL_DEBUG_KERNEL is not set
+# CONFIG_KERNEL_DEBUG_INFO is not set
 # CONFIG_KERNEL_DYNAMIC_DEBUG is not set
 # CONFIG_KERNEL_KPROBES is not set
 # CONFIG_KERNEL_AIO is not set
@@ -304,8 +304,8 @@ CONFIG_KERNEL_DEBUG_INFO=y
 # CONFIG_KERNEL_FANOTIFY is not set
 # CONFIG_KERNEL_BLK_DEV_BSG is not set
 CONFIG_KERNEL_MAGIC_SYSRQ=y
-CONFIG_KERNEL_COREDUMP=y
-CONFIG_KERNEL_ELF_CORE=y
+# CONFIG_KERNEL_COREDUMP is not set
+# CONFIG_KERNEL_ELF_CORE is not set
 # CONFIG_KERNEL_PROVE_LOCKING is not set
 CONFIG_KERNEL_PRINTK_TIME=y
 # CONFIG_KERNEL_SLABINFO is not set
@@ -334,8 +334,8 @@ CONFIG_KERNEL_RELAY=y
 # CONFIG_NO_STRIP is not set
 # CONFIG_USE_STRIP is not set
 CONFIG_USE_SSTRIP=y
-# CONFIG_STRIP_KERNEL_EXPORTS is not set
-# CONFIG_USE_MKLIBS is not set
+CONFIG_STRIP_KERNEL_EXPORTS=y
+CONFIG_USE_MKLIBS=y
 CONFIG_USE_UCLIBCXX=y
 # CONFIG_USE_LIBSTDCXX is not set
 
@@ -2265,7 +2265,7 @@ CONFIG_PACKAGE_iptables-mod-timerange=y
 CONFIG_PACKAGE_iptables-mod-webmon=y
 CONFIG_PACKAGE_iptables-mod-weburl=y
 # CONFIG_PACKAGE_iptaccount is not set
-# CONFIG_PACKAGE_miniupnpd is not set
+CONFIG_PACKAGE_miniupnpd=y
 # CONFIG_PACKAGE_nftables is not set
 
 #
```

**Comment by lantis1008** [comment]
I'm seeing no significant diff between yours and mine. ?

**Comment by m45t3r** [comment]
Well, for one various `CONFIG_PACKAGE_plugin-gargoyle` are commented, so it means that you're using the old config file. In my new one, I don't disable any plugin, I just disable kernel debugging and enable strip libraries/kernel.

**Comment by lantis1008** [comment]
We don't include plugins by default in any targets. I'm following the precedent. This was done intentionally.

**Comment by m45t3r** [comment]
I know, however the plugins are not even compiled. They are commented, not compiled as module (like in `default`).

**Comment by m45t3r** [comment]
Like those ones:
`
# CONFIG_PACKAGE_plugin-gargoyle-minidlna is not set
# CONFIG_PACKAGE_plugin-gargoyle-openvpn is not set
...
# CONFIG_PACKAGE_plugin-gargoyle-tor is not set
# CONFIG_PACKAGE_plugin-gargoyle-usb-printer is not set
# CONFIG_PACKAGE_plugin-gargoyle-usb-storage is not set
# CONFIG_PACKAGE_plugin-gargoyle-webcam is not set
`

**Comment by m45t3r** [comment]
And:
```
CONFIG_PACKAGE_minidlna=m
CONFIG_PACKAGE_openvpn-openssl=m
CONFIG_PACKAGE_gargoyle-tor=m
CONFIG_PACKAGE_gargoyle-tor-geoip=m
```
or:
```
CONFIG_PACKAGE_kmod-nls-base=m
CONFIG_PACKAGE_kmod-nls-cp1250=m
CONFIG_PACKAGE_kmod-nls-cp1251=m
CONFIG_PACKAGE_kmod-nls-cp437=m
CONFIG_PACKAGE_kmod-nls-cp775=m
CONFIG_PACKAGE_kmod-nls-cp850=m
CONFIG_PACKAGE_kmod-nls-cp852=m
CONFIG_PACKAGE_kmod-nls-cp862=m
CONFIG_PACKAGE_kmod-nls-cp864=m
CONFIG_PACKAGE_kmod-nls-cp866=m
CONFIG_PACKAGE_kmod-nls-cp932=m
CONFIG_PACKAGE_kmod-nls-iso8859-1=m
CONFIG_PACKAGE_kmod-nls-iso8859-13=m
CONFIG_PACKAGE_kmod-nls-iso8859-15=m
CONFIG_PACKAGE_kmod-nls-iso8859-2=m
CONFIG_PACKAGE_kmod-nls-iso8859-6=m
CONFIG_PACKAGE_kmod-nls-iso8859-8=m
CONFIG_PACKAGE_kmod-nls-koi8r=m
CONFIG_PACKAGE_kmod-nls-utf8=m
```
Just some examples. Since those packages are still compiled, they still use space, because they use C functions that the library strip can't remove (or in the case of kmod packages, increase kernel size for the same motive). Disabling them can save some space, however I don't think it is worth it since the space savings are minimal. This is why I did a clean new config file, that is commit https://github.com/m45t3r/gargoyle/commit/763ace14d4153806924659989a3f34340ac190c1 (I did even that PR to save you the work that you needed to import my changes). In this config file I didn't disable the plugins, they're still enabled, I just disabled kernel debugging and stripped kernel/libraries.

In https://github.com/m45t3r/gargoyle/commit/763ace14d4153806924659989a3f34340ac190c1, if someone wants to install Tor or OpenVPN, because they have space (someone that custom compiled a firmware using the new profile for a target with 8MB of RAM), they can still use it. This is an advantage. Another advantage is that there is less work to maintain the difference between both profiles, `default` and `default_small`.

**Comment by lantis1008** [comment]
Ok. 
I'm going to close my pull request, and you can open a brand new one and do whatever you like with it. I'm now done with this issue.

My final opinion on this.
1. I commented out those particular packages because default_small devices will be incapable of running openvpn and tor. The majority of these devices will not have enough RAM to reliably do so. ```It can be run on a router with 32MB of memory only if SWAP is enabled, but 64MB is recommended```
2. Not all of those default_small devices have a usb port. The ones that do, I'm inclined to not offer the support, UNTIL, we know that the firmware is stable enough on a large range of test devices operating under normal working conditions for an extended test period.
A small handful of devices does not satisfy my personal "stability" requirements.
3. I know how to read a pull request. I went to yours, saw things that i don't agree with, modified them and submitted my own based on what i think should end up in Gargoyle. You don't need to repeatedly point out https://github.com/m45t3r/gargoyle/commit/763ace14d4153806924659989a3f34340ac190c1 like it's bigger than Ben Hur.

**Comment by m45t3r** [comment]
Well, I am not trying to piss you off. However like I was saying, if you want to disable USB, you need to scan the config file to remove recursive dependencies. Even I couldn't track all of them. This is why I suggested that we only remove kernel debugging and stripping features. This is a less invasive change.

If your only objective is to make people unable to install Tor/OpenVPN, you could only remove the plugins (so they wouldn't be packaged and it wouldn't appear in the repository), however in your PR we still had things like `kmod-usb_*`  disabled. Not that this isn't your fault, it is mine, the original file that I posted above is flawed.

About your point 2, even the devices that don't have USB support generally support USB by using hardwares mod. Not that I am qualified to say if those moddified devices should be allowed to have USB support in Gargoyle or not.

Well, fair enough, sorry for the stress, it was not my intention. I will reactivate my PR them.

**Comment by lantis1008** [comment]
We will have to agree to disagree on USB support.
I don't have a problem with you or the work you've done. I appreciate it. 

I just don't agree with some of the decisions you've made here. 
And that's fine. It's not me that has the final say anyway.

No problem mate. :)
I will keep an eye on the PR.

**Comment by m45t3r** [comment]
I will leave a note in the PR, if @ericpaulbishop or someone else things it is better to completely remove USB support in those builds I can push a change that will simple disable the USB related packages (`gargoyle-plugin_*`).

In this way, no USB plugin will be available in `default_small` repository, however if someone really wants to try USB they could add the `default` repository and try to install from there (it probably will work since the modules will still be available in `default_small`, just disabled). Of course, in this case it would be **completely unsupported**.
