### ISSUE TITLE
Small comestic issue in Connection->Basic

### ISSUE THREAD

**Issue by m45t3r** [ericpaulbishop/gargoyle#529]
Just a small comestic issue (better described with images than words):
![captura de tela 15](https://cloud.githubusercontent.com/assets/844343/14938538/f900ef6e-0efc-11e6-83d0-ea2d1c66e0dd.png)
![captura de tela 16](https://cloud.githubusercontent.com/assets/844343/14938539/fa4e59e2-0efc-11e6-87ee-88900d8c6b2a.png)

Look at `Encryption:`. When `Wireless Mode: Access Point (AP)` the selection box width is bigger than when `Wireless Mode: AP+WDS`. It should be the same width. This happens in all themes I tested (included Default, Xeye, Light and Green).

**Comment by lantis1008** [comment]
It gets wider because under AP because you can also use RADIUS. The box dynamically sizes to its widest content. This behaviour is consistent with all boxes in the GUI, and in my opinion, not an issue.

**Comment by lantis1008** [comment]
suggest close
