### ISSUE TITLE
Suggestion: Gitter.im

### ISSUE THREAD

**Issue by stopspazzing** [ericpaulbishop/gargoyle#530]
[Gitter.im](https://gitter.im/) integrates with github (and a bunch of other services). Would allow people to communicate faster than forums & github comments. Also has a phone app. It's also free.

**Comment by nworbnhoj** [comment]
Yep - so will you setup a Gargoyle room?

**Comment by stopspazzing** [comment]
@nworbnhoj To whom are you asking?

**Comment by ericpaulbishop** [comment]
I'm Pretty sure he was asking me.

Created here  https://gitter.im/ericpaulbishop/gargoyle.

Please note that I prefer to communicate via issues/pull requests, so that's the best way to talk about things with me. If you want to use gitter.im, though go right ahead.

**Comment by nworbnhoj** [comment]
To whomever was going to set it up! Thanks @ericpaulbishop
