### ISSUE TITLE
DDNS hangs on add/update

### ISSUE THREAD

**Issue by lantis1008** [ericpaulbishop/gargoyle#544]
On latest 1.9.x DDNS seems to hang the interface when adding or updating a config. 
Specifically I have been testing using no-ip.com. 
Running "ps" while it is hung shows the DDNS process stuck and the /tmp/tmp.sh file (the one that we write UI commands into) is sitting stuck. 

I haven't had much time to investigate the issue so I'm opening it up to all.

**Comment by obsy** [comment]
My users also report this, but I cannot reproduce this. From my network everything works fine.

**Comment by lantis1008** [comment]
I initially couldn't reproduce it, but now I can every time. 
Are you using no-ip.com?
Most complaints seem to come from that provider.

**Comment by obsy** [comment]
no-ip.com, see http://eko.one.pl/forum/viewtopic.php?pid=164069#p164069 (in Polish...)

**Comment by ericpaulbishop** [comment]
I just tried to reproduce this and I haven't gotten it to fail yet. I now have a no-ip ddns host configured, will see if it fails over time. If I can manage to reproduce the problem, I will try to fix it. I need to see to be able to reproduce it to fix it, though.

**Comment by lantis1008** [comment]
Will attempt to lock down a process

**Comment by dlogictech** [comment]
I can also confirm that my DDNS does indeed hang when adding or editing the config using no-ip.com DDNS service.
In my case the configuration is using the xxxxx.no-ip.org domain name.
