### ISSUE TITLE
Busybox site is down

### ISSUE THREAD

**Issue by m45t3r** [ericpaulbishop/gargoyle#562]
Gargoyle current master is based on OpenWRT-CC, that uses Busybox 1.23.2.

The problem is, Busybox website is down (for two or three days, at least), and it was the only available place that had the source code for Busybox 1.23.2. The mirror in Busybox's Makefile (http://distfiles.gentoo.org/distfiles/) does not offer this specific version of Busybox, so currently it is impossible to compile Gargoyle (and OpenWRT-CC, for that matter).

I am reporting here because I don't have any idea where I can report this bug upstream, and it directly affects Gargoyle, even if the bug itself is from OpenWRT.

**Comment by lantis1008** [comment]
I was able to download it from an alternate location and continue the build. 
http://sources.openelec.tv/mirror/busybox/

**Comment by obsy** [comment]
Or http://sources.lede-project.org/

**Comment by m45t3r** [comment]
Got the link from obsy, works great.

However wouldn't it be better to fix this somewhere? I could report upstream, however OpenWRT seems pretty dead to me...

**Comment by lantis1008** [comment]
At some point gargoyle will probably move to being LEDE based. But not today

**Comment by lantis1008** [comment]
Suggest close. This appears no longer an issue. 
@m45t3r

**Comment by m45t3r** [comment]
@lantis1008 Fair enough.
