### ISSUE TITLE
Add TL-WR740 v5/v6 to the list of devices

### ISSUE THREAD

**Issue by m45t3r** [ericpaulbishop/gargoyle#569]
A frined of mine bought a TL-WR740N. For my surprise it was not yet supported in Gargoyle (even Gargoyle 1.9), since it is a v5 variation of this router.

![whatsapp image 2016-07-30 at 18 31 27](https://cloud.githubusercontent.com/assets/844343/17273881/f5a9081e-569c-11e6-959a-b3ff5f231118.jpeg)

The router is supported in current OpenWRT-CC, since I could compile current Gargoyle and the firmware worked without problems. However it is not in the list of `profile_images` file, so it is not available in any version of Gargoyle.

BTW, I don't know about TL-WR740n v6, I can confirm that v5.1 works, at least.

**Comment by lantis1008** [comment]
It would be important to distinguish that v5.0 will not work and users shouldn't attempt to flash, from my understanding.

**Comment by lantis1008** [comment]
As these are both 4MB flash devices, they are no longer able to be supported. Please close issue.
