### ISSUE TITLE
Missing contribution guidelines

### ISSUE THREAD

**Issue by fatso83** [ericpaulbishop/gargoyle#579]
After using it for a month I really like the Gargoyle software, but I was thinking the UI could use some updating [(*)](#ui) and was trying to find out how I could contribute. The first thing that struck me was that finding out how to get started was not as easy as I am used to in the front-end world. 

The first two major omissions, IMHO, are a `README.md` file and a `CONTRIBUTE.md`. 

## README.md
As this is the first thing anyone landing here meets, it should basically contain a short summary of what the project is, which features it has (delegating to the Wiki or homepage for more details), how to get started using it, and some pointers for people wanting to contribute. 

## CONTRIBUTE.md
This is the part I am interested in. How, where, what, when, who. Code styles, guidelines for PR size, etc. Just by browsing the code and the build scripts I was still unsure where the stuff I was interested in were, and how it all was assembled. After browsing the issues and reading through some merged pull requests, I started realizing that a lot of UI stuff were deep in some subfolders in the code tree (like [package/gargoyle/files/www](https://github.com/ericpaulbishop/gargoyle/tree/master/package/gargoyle/files/www)). Which is fine, I guess, but I think a lot of potential contributors never even get this far as they cannot find where to begin. This project might lose out on some potential good work, especially from people more interested in building a smooth, modern front-end than hacking embedded code.

I have created/contributed to several open source projects, and I know that providing these files avoid a lot of administrative overhead by answering common questions. I think the [CONTRIBUTE.md](https://github.com/sinonjs/sinon/blob/master/CONTRIBUTING.md) from the Sinon project makes for a pretty good template.

---

<a name="ui"></a> Regarding the UI, I am using 1.9.X (Built 20160924-1943 git@093be12) (which someone gave me a link to on the forum somewhere ...), which does not include the latest UI improvements I have seen being merged in October, so some things might already be fixed.

**Comment by fatso83** [comment]
Some things I was thinking about in possible improvements were:
- expose HTTP endpoints in stead of server rendered markup to enable realtime updates of the UI
- try to split BE and FE code more up to enable more modular build scripts for the front-end

But as there are no guidelines to find I was unsure of how small one should keep the PRs, if one should discuss them beforehand in some dev channel to make sure the work does not go to waste, etc.

**Comment by lantis1008** [comment]
Would be happy to discuss the current work on the GUI, and any improvements at https://gitter.im/ericpaulbishop/gargoyle
However, it is late my time and i am signing off now.

**Comment by jan-kiszka** [comment]
Picking up this still open issue: Would be good to add at least a minimal readme with description of the build setup (I had to parse build.sh) - but also to set the very important link between https://www.gargoyle-router.com/about.php#license and this repository. It seems there is no license for the meta data and other source code inside the repo mentioned somewhere which makes all that appear to be unlicensed.

**Comment by lantis1008** [comment]
Thanks, I will look at adding some relevant information, however as I don’t control the github instance I may not be able to do all of it.
The build requirements are listed in the wiki if you need further information.

**Comment by lantis1008** [comment]
I've added a basic README. I'll add a contribution guideline another time, at which point we will close this issue.

**Comment by lantis1008** [comment]
I have now added a base CONTRIBUTING guide as well. If you find bits are missing, please add them or raise an issue stating which bits you think are missing.
