### ISSUE TITLE
Update ffmpeg to 3.2

### ISSUE THREAD

**Issue by tapper82** [ericpaulbishop/gargoyle#581]
ffmpeg is now up to ver 3.2 with a lot of fixes in the change log. If it does not take any more space on routers with low flash could we update from 2.4.4 to 3.2.

**Comment by tapper82** [comment]
Or if it's not used know more then remove it? Is it used for any thing other than webcam plugin?

**Comment by lantis1008** [comment]
Resolved as of https://github.com/ericpaulbishop/gargoyle/commit/eba94bf81923f6006c1f95551d588ada6e48f408. 
Please close.
