### ISSUE TITLE
QoS: top 2 rows in match criteria table not sortable.

### ISSUE THREAD

**Issue by fifonik** [ericpaulbishop/gargoyle#583]
If I click on arrow up in the second row or on arrow down in the first row in the QoS match criteria tables -- nothing happened.
Looks like it is a bug in moveThisCellsRowUp and moveThisCellsRowDown methods in table.js.
Index should be zero based:
https://developer.mozilla.org/en-US/docs/Web/API/Node/childNodes

**Comment by lantis1008** [comment]
This is resolved in the latest development version. 
Here: https://github.com/ericpaulbishop/gargoyle/commit/d39a60f200acfe0b5ad32258d700c3d9caa600d4
And here: https://github.com/ericpaulbishop/gargoyle/commit/d666e15aea0c60a29d13e17317245b8b3c7385a0

**Comment by lantis1008** [comment]
Now resolved in master as of https://github.com/ericpaulbishop/gargoyle/commit/33deb7bfd74205d937eb235701439ec99268ec5e

**Comment by lantis1008** [comment]
Ping @fifonik   Please close this issue.
