### ISSUE TITLE
Plugins not retrieving from Gargoyle site -- possible site configuration issue?

### ISSUE THREAD

**Issue by lantis1008** [ericpaulbishop/gargoyle#586]
```ewget http://gargoyle-router.com/packages/gargoyle-1.8.1/ar71xx/default/Packages```
```<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
Packages are returning a 301 redirect (with no redirect URL i might add??)

This is pretty easy to patch to HTTPS (although not retroactively), however...

```ewget https://gargoyle-router.com/packages/gargoyle-1.8.1/ar71xx/default/Packages```
```Could Not Fetch URL```

Doesn't seem to work. Does not appear to be a SSL issue because:
```ewget https://lantisproject.com/gargoyle_custom/gui_overhaul/mvebu/default/Packages```
returns the expected output.

For interest, openwrt doesn't seem to accept https package retrieval
```ewget https://downloads.openwrt.org/chaos_calmer/15.05.1/mvebu/generic/packages/base/Packages```
Returning the same error as gargoyle site
http works fine in this instance.

**Comment by ericpaulbishop** [comment]
Thanks for pointing this out -- I enabled https redirects for everything, but should have allowed plain http for the package downloads. Should be fixed now.
