### ISSUE TITLE
Add rule to qos download creates errors

### ISSUE THREAD

**Issue by joequant** [ericpaulbishop/gargoyle#600]
When I click "add rule" to qos download I get a dialog box that says that "There is an error" in fields that I have not filled in.  This is despite the fact that the check box in the UI is not active.  This error disappears if I click and unclick the checkbox, which suggests that when the page is loaded that something is not getting set to false.

**Comment by joequant** [comment]
This seems to the partly due to the fact that I got myself in the situation where there is no table that contains the qos rules, and so when I add the rules, I get an error in table.js:90 about a table being none.

**Comment by lantis1008** [comment]
What version/commit are you seeing this behaviour on?

Please describe further how you ended up in a situation with no "table"?
After removing all rules, adding additional rules still worked fine for me. 

I'd suggest a failsafe reset and trying to reproduce such behaviour.

If you can come up with a sequence of events that guarantees the error, I can look at debugging it.

**Comment by joequant** [comment]
This is happening with with the master version with the new GUI.
commit: ff413a5be2e6ebb7cbefd03d43a116610a2dbc9c

When I turn on QOS download and click Active Congestion after a clean reset and then click on "Save changes" the entire table disappears.  Once the table disappears, then I can't add any new rules.

**Comment by joequant** [comment]
Let me try to reproduce locally.  What I think is happening is that in the course of processing the javascript, there is an error that puts the UI into a weird state.

**Comment by lantis1008** [comment]
Can you please either reflash or failsafe reset your router. Then clear your browser cache. 

Please then produce a step by step process to produce the error.

**Comment by joequant** [comment]
This is with the dev version of firefox

1) reset to factory default and    clear browser cache
2) login as password
3) set new password and    set Timezone to    Hong Kong
4) login again

5) QosDownload
6) Enable QosDownload and active congestion control - save changes
7) Click QosUpload
8) Enable QosUpload - save changes
9) Go back to QosDownload
10) The rules in QosDownload have all disappeared

Looking    at the web console, when I save    changes    in QosUpload, I
get
this error

TypeError: classification.match(...) is null  qos.js:487:18
   resetData http://192.168.1.1/js/qos.js:487:18
   http://192.168.1.1/qos_download.sh:869:2

**Comment by joequant** [comment]
Also, I tried to do it again, and I got similar but not identical results.  What happened was that I didn't get a console error, but all of the rules disappeared, and the service classes all disappeared and the only class that exists is "dclass_1"

Looking in the dmesg in the router, there aren't any errors that I can see.

**Comment by lantis1008** [comment]
What router make and model is this?

**Comment by joequant** [comment]
wr1043nd-v3

**Comment by lantis1008** [comment]
I couldn't make this happen on a fresh flash. There is possibly something different about our environments.

**Comment by lantis1008** [comment]
You aren't using multiple tabs or something like that right?

**Comment by lantis1008** [comment]
Hi Joe, are you still seeing this issue on 1.11.0?
