### ISSUE TITLE
Bump Openwrt

### ISSUE THREAD

**Issue by tapper82** [ericpaulbishop/gargoyle#602]
Hi can you bump Openwrt pleas there is a kernel update and fixes for usb 2.0 for mvebu.
https://git.openwrt.org/?p=15.05/openwrt.git;a=commitdiff;h=03d52cfcff87c0e8e09e7a455a6fdefb7138e369

**Comment by tapper82** [comment]
Nice one lantis.

**Comment by lantis1008** [comment]
Did you test this @tapper82?
1 forum user has reported a problem with it

**Comment by ericpaulbishop** [comment]
I tested that all patches applied appropriately and everything compiled
before merging. I assumed that the actual upstream commit was accurate,
which might have been a mistake...

**Comment by lantis1008** [comment]
The commit matches the upstreamed fix in kernel 4.4. 
Unsure what to make of it. Will dig more with the user.

**Comment by tapper82** [comment]
Hi yes I tested this on a WD-N750 and a WDR3600 all is fine. Thay are still up and running since i flashed them. What platform is the forum user running. If i have a router I will flash and test.

**Comment by lantis1008** [comment]
Well the USB change you requested is for the mvebu series... you didn't test it before suggesting it?

**Comment by tapper82** [comment]
No sorry! I thought it was just for the WRT1200AC and it's by Sera and as they have dun a lot on the mvebu platform, I thought it would be OK. I will take this on board. Next time test!
On WRT1900 AC v2 both USB ports work with:
Gargoyle Version:
1.9.X (Built 20170110-2258 git@33deb7b)
I can mount and unmount a fat 16 1 GB drive. Both ports work.
When using Gargoyle Version:
1.9.X (Built 20170209-1606 git@f1e9e21)
Onley one port is working for me it's the port that's just USB. The one that is a USB and Esata combo will not work.
Again sorry to all.

**Comment by lantis1008** [comment]
Can possibly partial revert back to http://git.openwrt.org/?p=15.05/openwrt.git;a=commit;h=1fea0d89f5b7867262213fc0ac459c4ab861e465

I'll try to do some testing soon.

**Comment by lantis1008** [comment]
Testing patch to fix.
https://github.com/openwrt/openwrt/pull/388
