### ISSUE TITLE
Minor glitch with gui

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#606]
@lantis1008:
Default WAN:

![zrzut ekranu z 2017-02-15 18-42-23](https://cloud.githubusercontent.com/assets/695356/22987341/b7381aa2-f3ae-11e6-8c9c-ec7c0ecc4b71.png)

switch to qmi modem:

![zrzut ekranu z 2017-02-15 18-42-33](https://cloud.githubusercontent.com/assets/695356/22987360/c5207998-f3ae-11e6-9edc-7618c2a36c6c.png)

(select is visible next to scan button, but should be invisible yet)

Click "scan"

![zrzut ekranu z 2017-02-15 18-42-50](https://cloud.githubusercontent.com/assets/695356/22987402/e607f654-f3ae-11e6-81a9-4404292b21c4.png)

Select has different style.

**Comment by ericpaulbishop** [comment]
Should now be fixed in fa0327945a2c4e4b1af8e21025c2f1c769b68233
