### ISSUE TITLE
the crontabs show error

### ISSUE THREAD

**Issue by livepu** [ericpaulbishop/gargoyle#611]
```
root@Gargoyle:/etc/crontabs# cat root
0,1,11,21,31,41,51 * * * * /usr/bin/set_kernel_timezone >/dev/null 2>&1
* * * * * if [ -z "$(ifconfig | grep tun 2>/dev/null)" ] ; then logger "openvpn stopped, restarting" ; /etc/init.d/openvpn restart ; fi
0 0,4,8,12,16,20 * * * /tmp/do_webmon_backup.sh
0 0,4,8,12,16,20 * * * /tmp/bw_backup/do_bw_backup.s
0 0,4,8,12,16,20 * * * /tmp/bw_backup/do_bw_backup.sh
0 0,4,8,12,16,20 * * * /tmp/bw_backup/do_openvpn_bw_backup.sh
```

here is "0 0,4,8,12,16,20 * * * /tmp/bw_backup/do_bw_backup.s"

**Comment by lantis1008** [comment]
Do you have a set of steps that reproduces this?

**Comment by livepu** [comment]
after set WiFi timer switch.

**Comment by lantis1008** [comment]
Using the Wifi Schedule plugin?
I have just set a number of timers, edited them, cancelled them etc with no problem.

Can you be more specific about a list of steps to produce the issue?
Can you also confirm what version of Gargoyle you are running?

**Comment by livepu** [comment]
gargoyle version==commit d8fa73cc9409cd8c84f03170f8734825b1a69759
after make ramips , I change ramips-src to support psg1218.
and then in dir( ramips-src) make clean ,make menuconfig, make V=99
here is psg1218 dst for openwrt-cc
https://github.com/livepu/openwrt-k2/commit/4bcb852f901a5fadd370b84608a0f308aac03fcd

**Comment by lantis1008** [comment]
Steps to produce the problem?
Thank you for confirming the version.

**Comment by livepu** [comment]
use the bin for psg1218 ,Using the Wifi Schedule plugin,will show the error

**Comment by lantis1008** [comment]
The plugin is device agnostic, and therefore you should be able to provide me step by step instructions to reproduce such an error.
Example:
1. Install wifi schedule plugin
2. Activate timer for Sunday to turn on at 06:00 and off at 07:00
3. Check crontab for the bug

Without adequate instructions to reproduce the bug, then you might as well have not reported it.

**Comment by livepu** [comment]
My English is poor, I'm sorry.
I compile firmware with WiFi schedule plugin. Activate WiFi schedule plugin, set the Mo period, save. Then, cancel the activation, close the plugin. This time, I logged in to SSH see the wrong part of the crontabs.

**Comment by lantis1008** [comment]
I cannot reproduce this error using the steps you have described.
