### ISSUE TITLE
some error after switch to simplifiedchinese-zh-cn

### ISSUE THREAD

**Issue by cpexplorer** [ericpaulbishop/gargoyle#612]
Version：1.9.2
Symptom：After switch to zh-cn，either in qos uploade or qos download page, rule can't be added，moreover,“save changes” button has no response.
![2017-03-06_214056](https://cloud.githubusercontent.com/assets/19789201/23880826/40b2cccc-0891-11e7-83ee-bfc2ed05998e.png)

**Comment by lantis1008** [comment]
Will investigate

**Comment by lantis1008** [comment]
Am not seeing this error in EN, ZH-CN, or using the Dark-One theme. Have you tried clearing your browser cache?

If that does not resolve the issue, can you please provide some kind of debug information?
Logread and/or google chrome developer console output.
Thanks.

**Comment by cpexplorer** [comment]
Nothing obvious concerned found in syslog.
Here is console output(such problem appear only in zh-cn):
![2017-03-15_085457](https://cloud.githubusercontent.com/assets/19789201/23928932/ba0348d2-095d-11e7-9287-975a85549fc1.png)
![2017-03-15_085518](https://cloud.githubusercontent.com/assets/19789201/23928936/bafafda2-095d-11e7-99d2-f488f72e8d2f.png)

**Comment by lantis1008** [comment]
Thanks, will look again. 

Did you clear your browser cache and try again?
Ctrl+F5

**Comment by cpexplorer** [comment]
Clear cache does not work.Change browser like ie , edge，problem remain.

**Comment by cpexplorer** [comment]
what's more,rules that were successfully added(in en) can't display either
![2017-03-15_091220](https://cloud.githubusercontent.com/assets/19789201/23929255/a919311a-095f-11e7-84d7-eba862495934.png)
![2017-03-15_091307](https://cloud.githubusercontent.com/assets/19789201/23929257/a9d56c22-095f-11e7-9cde-f044bb19e06f.png)

**Comment by cpexplorer** [comment]
Any progress？ @lantis1008

**Comment by lantis1008** [comment]
Sorry very busy at the moment. 
I'll have time to look next week.

**Comment by cpexplorer** [comment]
OK,Many thanks.

**Comment by lantis1008** [comment]
Can you please pause the debugging at line 502 and tell me what the value of the "ruleTableColumns" variable is? It should be an array.

**Comment by cpexplorer** [comment]
That's weird，different from you!
 Gargoyle version 1.9.X    | OpenWrt Chaos Calmer branch        |
| Gargoyle revision d8fa73c | OpenWrt commit 03d52cf 

![2017-03-22_200436](https://cloud.githubusercontent.com/assets/19789201/24197179/9a9c293a-0f3b-11e7-91a1-f1a61d32142f.png)

**Comment by lantis1008** [comment]
You need this 
https://github.com/ericpaulbishop/gargoyle/blob/master/package/plugin-gargoyle-i18n-English-EN/files/www/i18n/English-EN/qos.js#L83
Or the equivalent in your ZH-CN translation. 
It can't find the string so it fails.

**Comment by lantis1008** [comment]
If you'd like to provide a translation I can put it in as a change (or you can do this yourself as well)?

**Comment by cpexplorer** [comment]
Need time to try，cause i'm new to gargoyle

**Comment by cpexplorer** [comment]
simply add translation qosStr.Comment="备注" seems not work for this issue
![2017-03-22_211748](https://cloud.githubusercontent.com/assets/19789201/24199570/12314896-0f45-11e7-8e29-c0c2648ac6b7.png)

**Comment by cpexplorer** [comment]
update: after clear my chrome cache, issue fixed now.

**Comment by cpexplorer** [comment]
Issue fixed now.
You can add translation qos.Comment="批注" to zh-cn package @lantis1008

**Comment by cpexplorer** [comment]
Issue fixed.Thanks very much!

**Comment by lantis1008** [comment]
Great :) thanks for submitting the change too

**Comment by lantis1008** [comment]
Can be closed as of https://github.com/ericpaulbishop/gargoyle/commit/85255a604f17d2aaacf49ee9c9823b16e58ae29e
