### ISSUE TITLE
build.sh code error report

### ISSUE THREAD

**Issue by cpexplorer** [ericpaulbishop/gargoyle#618]
Linux platform：Centos 6.5
`npm -v 
3.10.4`
`node -v
v6.3.1`
`symptom：bash: nodejs: command not found`
![2017-03-25_160114](https://cloud.githubusercontent.com/assets/19789201/24320655/7ee853c2-1174-11e7-999d-a15e5eaf37c5.png)
I think i should replace string "nodejs" with "node" in the following lines.
[https://github.com/ericpaulbishop/gargoyle/blob/master/build.sh#L390](https://github.com/ericpaulbishop/gargoyle/blob/master/build.sh#L390)
[https://github.com/ericpaulbishop/gargoyle/blob/master/build.sh#L393](https://github.com/ericpaulbishop/gargoyle/blob/master/build.sh#L393)
[https://github.com/ericpaulbishop/gargoyle/blob/master/build.sh#L418](https://github.com/ericpaulbishop/gargoyle/blob/master/build.sh#L418)
[https://github.com/ericpaulbishop/gargoyle/blob/master/build.sh#L421](https://github.com/ericpaulbishop/gargoyle/blob/master/build.sh#L421)

**Comment by lantis1008** [comment]
nodejs is the correct command. 
If nodejs was missing from your system it should have been compiled and built before Gargoyle.

**Comment by cpexplorer** [comment]
But i have already had node and npm installed on my centos 6.5.

**Comment by lantis1008** [comment]
Node was renamed to nodejs
Anecdotal: http://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04

You had an old version?

**Comment by cpexplorer** [comment]
I had this version(defined in build.sh)[node_version_tag="v6.3.1"](https://github.com/ericpaulbishop/gargoyle/blob/master/build.sh#L14) installed

**Comment by lantis1008** [comment]
@ericpaulbishop you might be more qualified (better understanding) to comment here. 
I'm seeing no issues on my end.

**Comment by cpexplorer** [comment]
I test it on ubuntu14.04，the correct command is also node. May be further judgement should be added to determine either nodejs or node is available like this?[https://github.com/cpexplorer/gargoyle/commit/4012079344a935493bd3a82259cd879fa16806a2](https://github.com/cpexplorer/gargoyle/commit/4012079344a935493bd3a82259cd879fa16806a2)

**Comment by lantis1008** [comment]
This looks to be an appropriate solution, although I'm still not sure where the problem arises from lol.

**Comment by cpexplorer** [comment]
Another feedback by the way：
Firstly，I suggest that the packages src[https://github.com/ericpaulbishop/gargoyle/blob/master/build.sh#L586](https://github.com/ericpaulbishop/gargoyle/blob/master/build.sh#L586) replaced with git clone -b for-15.05 https://github.com/openwrt/packages.git "$openwrt_package_dir"，cause the former missing some package like pcre、libsodium and diffutils
Secondly，Line [603](https://github.com/ericpaulbishop/gargoyle/blob/master/build.sh#L603) to [608](https://github.com/ericpaulbishop/gargoyle/blob/master/build.sh#L608) may missing some packages that exist in the third-level directory of "$openwrt_package_dir" which is not provided by openwrt source. For example,pcre and libsodium in $openwrt_package_dir/lib/ and diffutils in  $openwrt_package_dir/devel，and so on. These packages may be essential to some openwrt plugin like [shadowsocks](https://github.com/shadowsocks)
Hope to attract attention, thanks! @lantis1008 @ericpaulbishop

**Comment by ericpaulbishop** [comment]
The issue with different names for nodejs binary on different systems should be fixed in a4211e17
