### ISSUE TITLE
Translate new QOS Comments to other languages

### ISSUE THREAD

**Issue by lantis1008** [ericpaulbishop/gargoyle#619]
Hi multilingual contributors!

Can you please take it upon yourselves to update your relevant translation for the following line:
https://github.com/ericpaulbishop/gargoyle/blob/master/package/plugin-gargoyle-i18n-English-EN/files/www/i18n/English-EN/qos.js#L83

Any translations that have not been done within 7 days i will do myself with the help of Google Translate (i.e. not very well).

Appreciate your help!

- [ ] @petbrau (German)
- [x] @d3fz (Portuguese) - #621 
- [x] @butyl (Slovak - messaged on forums) - #622 
- [x] @WildRat (Russian) - #620 

French?
Norwegian?
Spanish?

Already Complete
English, Polish, Chinese

**Comment by d3fz** [comment]
Thank you for the heads up.

Done, PR sent.

**Comment by lantis1008** [comment]
German, French, Norwegian and Spanish translations added.
