### ISSUE TITLE
Plugin adblock

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#628]
@lantis1008 

Why sorted results is stored in /plugin_root/usr/lib/adblock/*.list instead of /usr/lib/adblock/* as they are read?

https://github.com/ericpaulbishop/gargoyle/blob/master/package/plugin-gargoyle-adblock/files/www/js/ablock.js#L115

**Comment by lantis1008** [comment]
Yes is problem

**Comment by lantis1008** [comment]
I think i need to rewrite it properly to store everything in plugin_root and symlink to the desired locations. that would probably be the most sane way of doing everything.

**Comment by lantis1008** [comment]
Sorry it took so long to look at this.

This does not seem to be an issue.
We are storing everything at /plugin_root in the hope that if someone is using an external plugin root, we store it there and not on their router (saving space).
The important files are symlinked back to /usr/lib/adblock on install of the plugin. So the operation should work just fine.

If you disagree with this method, i'm happy to change it. But as far as i can see for functionality, it works

**Comment by obsy** [comment]
IMO  use one location of while/black list.

**Comment by obsy** [comment]
My users - yes :)

**Comment by lantis1008** [comment]
please check #671 and provide feedback there if anything further
