### ISSUE TITLE
Wireless country options

### ISSUE THREAD

**Issue by fengchen-github** [ericpaulbishop/gargoyle#629]
There is no wireless country options via web.
Different countries have different 5ghz channels, the default US may cause device can not search the 5ghz signal.
Need to modify the / etc / config / wireless file.

[https://en.wikipedia.org/wiki/List_of_WLAN_channels](https://en.wikipedia.org/wiki/List_of_WLAN_channels)

**Comment by lantis1008** [comment]
Please see here:
https://github.com/ericpaulbishop/gargoyle/pull/469

In short, this is low priority and not likely to be solved soon.

**Comment by cpexplorer** [comment]
#默认开启wifi,设置国家为CN以支持13信道
	find "$target-src" -name "mac80211.sh" -print |while read line
	do
		if [ "${line:0-16:4}" = "wifi" ];then
			sed -i '/.*option disabled 1/{s/1/0/}' $line
			[ -z "$(sed -n '/option.*country/p' $line)" ] && sed -i '/option.*hwmode/ a\\toption country\tCN' $line
		fi
	done

**Comment by fengchen-github** [comment]
13信道倒无所谓，主要是前几天装了波兰版的石像鬼搜不到5g信号，后来研究lede发现是信道的问题，和国家设置也有关系，石像鬼web界面没有设置项

**Comment by lantis1008** [comment]
It shouldn't stop you searching a band based on the country.

**Comment by fengchen-github** [comment]
Different countries allow different channels.
Clients devices in different countries support different channels.

**Comment by lantis1008** [comment]
Did you read #469 ?

**Comment by francisuk1989** [comment]
see https://github.com/ericpaulbishop/gargoyle/pull/752
Closed
