### ISSUE TITLE
openvpn connection problems on 1.9.2

### ISSUE THREAD

**Issue by joequant** [ericpaulbishop/gargoyle#631]
I'm having problems with openvpn on 1.9.2 that don't seem to exist in 1.9.1.  The connection log indicates that the keys exchange is getting garbled

A google seems to indicate that this might have something to do with the handling of tls-cipher

Sun May 14 20:05:37 2017 182.239.75.116:37889 VERIFY OK: depth=1, C=??, ST=UnknownProvince, L=UnknownCity, O=UnknownOrg, OU=UnknownOrgUnit, CN=wbpmtnymodpfzcm, name=wbpmtnymodpfzcm, emailAddress=wbpmtnymodpfzcm@vdtddvyfgjptpea.com
Sun May 14 20:05:37 2017 182.239.75.116:37889 VERIFY OK: depth=0, C=??, ST=UnknownProvince, L=UnknownCity, O=UnknownOrg, OU=UnknownOrgUnit, CN=chuwi, name=chuwi, emailAddress=chuwi@.com
Sun May 14 20:05:38 2017 182.239.75.116:37889 TLS_ERROR: BIO read tls_read_plaintext error: error:1408F119:lib(20):func(143):reason(281)
Sun May 14 20:05:38 2017 182.239.75.116:37889 TLS Error: TLS object -> incoming plaintext read error
Sun May 14 20:05:38 2017 182.239.75.116:37889 TLS Error: TLS handshake failed
Sun May 14 20:05:38 2017 182.239.75.116:37889 SIGUSR1[soft,tls-error] received, client-instance restarting
Sun May 14 20:06:33 2017 182.239.75.116:57734 TLS: Initial packet from [AF_INET]182.239.75.116:57734, sid=90072d3f e825dfa4

**Comment by joequant** [comment]
Closing issue.  It's failing for me on 1.9.1 and I know it worked for me before there.

**Comment by myeyre** [comment]
Failed with exact same error on 1.9.2 custom x86 build. Works like a charm on 1.8.1 ar71xx and I really like this nearly openvpn-in-one-click feature.

Will give a try to master branch.

**Comment by joequant** [comment]
Just one comment.  What happened with me is that I cleared out all of my old keys and then regenerated everything from scratch, and that seemed to fix the problems.  Still not quite certain what happened.
