### ISSUE TITLE
Network stop for a while in NETGEAR WNDR4300 V1

### ISSUE THREAD

**Issue by crackself** [ericpaulbishop/gargoyle#638]
Found it when gaming(out of connect),the problem occur in periodically on my 4300 by using firmware build from the latest code(build by "make ar71xx.usb_large_nand")，QoS Distribution pannle show  net download trackffic stop（Circular chart show evenly distributed about every rule）.always need about 3min  back to normal.
For compared,now the using firmware download frome Gargoyle's offical web site and that problem never occur.

**Comment by lantis1008** [comment]
did you do a successful `make FULL_BUILD=true ar71xx.usb_large_nand` first?

**Comment by crackself** [comment]
no,just only make by  `make ar71xxx.usb_large_nand`,should I try BULL_BUILD=true?
