### ISSUE TITLE
Is there any plans to support Shadowsocks as a plugin?

### ISSUE THREAD

**Issue by crackself** [ericpaulbishop/gargoyle#640]
Shadowsocks-libev is a branch for openwrt`https://github.com/shadowsocks/openwrt-shadowsocks` ,but it's default web GUI only work on luci web interface.I wonder is that any plans to support it as a plugin or any wiki about writing supported web interface fo Gargoyle web?

**Comment by lantis1008** [comment]
I don't know of any plans to support it. 

There is documentation on building Gargoyle here: https://www.gargoyle-router.com/wiki/doku.php?id=developer_documentation

No documentation on building plugins specifically, however all plugins are in this repo and using them as a starting point is reasonably straight forward. 
The minidlna plugin is nice and simple example of interacting with various parts of Gargoyle.

If there are particular elements you don't understand I can try to answer specific questions here or on the forum.

**Comment by crackself** [comment]
thanks,I will read and ask for help when geting trouble！

**Comment by crackself** [comment]
I going to write the `Makefile` for add shasowsocks menu ,here's get an uncertainty:
the Makfile in `plugin-gargoyle-minidlna` show "uci set gargoyle.system.minidlna='352'" in line 46.Is it intent to setting the position of the plugin show in Gobal menu (can't find the same command in Makefile about plugin-gargoyle-tor)?so,if I need to calculate and set the same one into Makefile?
![screen shot 2017-07-12 at 22 52 55](https://user-images.githubusercontent.com/16448332/28124510-70e82120-6756-11e7-9904-eb0bad7f9952.png)

**Comment by lantis1008** [comment]
That is correct. 
From what I understand of shadowsocks, this plugin will belong under the firewall or connection menus?
The number determines the order it will be displayed. 
The defaults are listed here https://github.com/ericpaulbishop/gargoyle/blob/master/package/gargoyle/files/etc/config/gargoyle#L77
There are also the other plugins which will have their own entries in the respective makefile.

**Comment by lantis1008** [comment]
Tor is here https://github.com/ericpaulbishop/gargoyle/blob/master/package/plugin-gargoyle-tor/Makefile#L65

**Comment by crackself** [comment]
so difficult to write a JS scrip and shadowdocks.sh😂.could luci interface work with Gar web?could I add the openwrt feeds to install luci?

**Comment by lantis1008** [comment]
You can install it, but it isn't designed to work with it at all.
