### ISSUE TITLE
The lastest update seems faile to save chages of wireless setting

### ISSUE THREAD

**Issue by crackself** [ericpaulbishop/gargoyle#643]
update code to commit 14a8cfaa75794d17f39744ae9c169dc00113823d and build(FULL_BUILD) for netgear 4300,it can not save change to wifi password.
![2017-07-29 08 44 12](https://user-images.githubusercontent.com/16448332/28740692-a796e67a-743a-11e7-9c05-7c09b67abfb6.png)

**Comment by crackself** [comment]
this problem still exists on commit 10f4ee6383ecb34e60af98646c0bd66ea63df56f

**Comment by lantis1008** [comment]
I'm not seeing the same issue. Can you please provide more details. 
Or even a system log?

**Comment by crackself** [comment]
don't know how to output kernel log,here'ssystem log get from systemlog plugin,it seems many rule to do with dnsmasq(I have nothing change about it):
`Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain bbs
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain bbs
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain bbs
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain dyn
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain dyn
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain dyn
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain parody
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain parody
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain parody
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain glue
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain glue
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain glue
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 78.47.86.43#53 for domain bit
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 178.32.31.41#53 for domain bit
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using local addresses only for domain lan
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: reading /tmp/resolv.conf.auto
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain micro
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain micro
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain micro
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain oss
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain oss
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain oss
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain null
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain null
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain null
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain ing
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain ing
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain ing
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain indy
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain indy
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain indy
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain gopher
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain gopher
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain gopher
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain geek
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain geek
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain geek
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain fur
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain fur
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain fur
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain free
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain free
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain free
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain bbs
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain bbs
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain bbs
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain dyn
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain dyn
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain dyn
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain parody
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain parody
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain parody
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.142.171.235#53 for domain glue
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 95.211.32.162#53 for domain glue
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 66.244.95.20#53 for domain glue
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 78.47.86.43#53 for domain bit
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 178.32.31.41#53 for domain bit
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using local addresses only for domain lan
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 211.162.52.209#53
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: using nameserver 211.162.61.236#53
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: read /etc/hosts - 1 addresses
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: read /tmp/hosts/dhcp - 1 addresses
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq-dhcp[4387]: read /etc/ethers - 0 addresses
Sun Aug  6 13:28:27 2017 daemon.info dnsmasq[4387]: exiting on receipt of SIGTERM
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: started, version 2.73 cachesize 150
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: compile time options: no-IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP no-DHCPv6 no-Lua TFTP no-conntrack no-ipset no-auth no-DNSSEC loop-detect inotify
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: DNS service limited to local subnets
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq-dhcp[4456]: DHCP, IP range 192.168.1.100 -- 192.168.1.249, lease time 12h
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain micro
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain micro
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain micro
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain oss
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain oss
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain oss
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain null
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain null
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain null
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain ing
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain ing
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain ing
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain indy
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain indy
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain indy
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain gopher
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain gopher
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain gopher
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain geek
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain geek
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain geek
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain fur
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain fur
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain fur
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain free
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain free
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain free
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain bbs
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain bbs
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain bbs
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain dyn
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain dyn
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain dyn
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain parody
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain parody
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain parody
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain glue
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain glue
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain glue
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 78.47.86.43#53 for domain bit
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 178.32.31.41#53 for domain bit
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using local addresses only for domain lan
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: reading /tmp/resolv.conf.auto
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain micro
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain micro
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain micro
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain oss
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain oss
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain oss
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain null
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain null
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain null
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain ing
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain ing
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain ing
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain indy
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain indy
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain indy
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain gopher
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain gopher
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain gopher
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain geek
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain geek
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain geek
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain fur
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain fur
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain fur
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain free
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain free
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain free
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain bbs
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain bbs
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain bbs
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain dyn
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain dyn
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain dyn
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain parody
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain parody
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain parody
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.142.171.235#53 for domain glue
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 95.211.32.162#53 for domain glue
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 66.244.95.20#53 for domain glue
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 78.47.86.43#53 for domain bit
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 178.32.31.41#53 for domain bit
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using local addresses only for domain lan
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 211.162.52.209#53
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: using nameserver 211.162.61.236#53
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: read /etc/hosts - 2 addresses
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq[4456]: read /tmp/hosts/dhcp - 1 addresses
Sun Aug  6 13:28:32 2017 daemon.info dnsmasq-dhcp[4456]: read /etc/ethers - 0 addresses
Sun Aug  6 13:28:47 2017 user.notice root: vsftpd init: mounted = 0
Sun Aug  6 13:28:47 2017 user.emerg syslog: ERROR: No drives attached, no directories to share!
Sun Aug  6 13:28:48 2017 user.emerg syslog: setting up led WAN (green)
Sun Aug  6 13:28:48 2017 user.emerg syslog: setting up led USB
Sun Aug  6 13:28:48 2017 user.emerg syslog: setting up led WLAN2G
Sun Aug  6 13:28:48 2017 user.emerg syslog: setting up led WLAN5G
Sun Aug  6 13:28:48 2017 daemon.info procd: - init complete -
Sun Aug  6 13:29:06 2017 user.notice firewall: Reloading firewall due to ifup of wan6 (eth0.2)
Sun Aug  6 13:49:29 2017 user.notice firewall: Reloading firewall due to ifup of wan (eth0.2)
Sun Aug  6 13:49:38 2017 kern.warn kernel: [  113.040000] ipt_bandwidth: timezone shift of 60 minutes detected, adjusting
Sun Aug  6 13:49:38 2017 kern.warn kernel: [  113.050000]                old minutes west=0, new minutes west=-60
Sun Aug  6 13:49:59 2017 authpriv.info dropbear[5628]: Not backgrounding
Sun Aug  6 13:50:05 2017 daemon.info hostapd: wlan0: STA c4:8e:8f:fa:16:2f IEEE 802.11: authenticated
Sun Aug  6 13:50:05 2017 daemon.info hostapd: wlan0: STA c4:8e:8f:fa:16:2f IEEE 802.11: associated (aid 1)
Sun Aug  6 13:50:05 2017 daemon.info hostapd: wlan0: STA c4:8e:8f:fa:16:2f RADIUS: starting accounting session 59870B61-00000000
Sun Aug  6 13:50:05 2017 daemon.info dnsmasq-dhcp[4456]: DHCPREQUEST(br-lan) 192.168.1.143 c4:8e:8f:fa:16:2f 
Sun Aug  6 13:50:05 2017 daemon.info dnsmasq-dhcp[4456]: DHCPACK(br-lan) 192.168.1.143 c4:8e:8f:fa:16:2f DESKTOP-FSAERC5
Sun Aug  6 13:50:40 2017 auth.info passwd: Password for root changed by root
Sun Aug  6 13:50:40 2017 authpriv.info dropbear[5628]: Early exit: Terminated by signal
Sun Aug  6 13:50:40 2017 authpriv.info dropbear[6018]: Not backgrounding
Sun Aug  6 13:51:19 2017 daemon.notice hostapd: wlan0: STA 8c:0d:76:d5:af:3b IEEE 802.11: did not acknowledge authentication response
Sun Aug  6 13:51:22 2017 authpriv.info dropbear[6358]: Child connection from 192.168.1.143:55691
Sun Aug  6 13:51:31 2017 authpriv.notice dropbear[6358]: Password auth succeeded for 'root' from 192.168.1.143:55691
Sun Aug  6 13:52:30 2017 authpriv.info dropbear[6366]: Child connection from 192.168.1.143:55832
Sun Aug  6 13:53:10 2017 authpriv.notice dropbear[6366]: Password auth succeeded for 'root' from 192.168.1.143:55832
Success
`

**Comment by lantis1008** [comment]
Log reveals nothing interesting. Can you do a factory reset and setup manually rather than restore to rule out corrupt config?

If not resolved, please share the settings you are trying to use so I can replicate.

**Comment by crackself** [comment]
I have try Restore Default Configuration and cut down power,then boot the machine,but no help.
 my custom change to build:Makefile and config(in ar71xx/profile/usb_large_nand),all the change just about the language setting,.the commit 172926d1d2fa4797441369d4892a137d97721718 without this problem.

[Makefile.zip](https://github.com/ericpaulbishop/gargoyle/files/1203093/Makefile.zip)
[config.zip](https://github.com/ericpaulbishop/gargoyle/files/1203094/config.zip)

**Comment by crackself** [comment]
another problem is:language name blank:
![languages](https://user-images.githubusercontent.com/16448332/29003890-b9bdecf0-7af1-11e7-8647-b47f6fc9b4d2.png)

**Comment by lantis1008** [comment]
And do all of these problems go away if you use English?

**Comment by LoveyCat** [comment]
I have the same problem, other options is ok.

**Comment by crackself** [comment]
u r ringht ,I make  wrong setting of localize.today I have  try firmware complie with origin Makefile,but still faile to save wifi changes.my  device is  NETGEAR wndr 4300V1.

**Comment by lantis1008** [comment]
Before you save settings, can you please press F12 to open developer console of your browser and see if any errors appear there?
I still haven't been able to reproduce a problem.

**Comment by crackself** [comment]
@LoveyCat what's your device ,mine is NETGEAR wndr 4300.

**Comment by LoveyCat** [comment]
@crackself  me too , I'm sure it's not language caused this problem ,because I only compile English support,  only save wifi settings have this problem .

**Comment by LoveyCat** [comment]
@lantis1008 I get this information when I try to save changes
![2017-08-07_184942](https://user-images.githubusercontent.com/14886041/29023660-45dff2aa-7ba1-11e7-9f24-03c01db82ec6.png)

**Comment by crackself** [comment]
@lantis1008 
get one error and a warring
![debug](https://user-images.githubusercontent.com/16448332/29024468-c71400e8-7ba4-11e7-9510-d6d77d94361a.png)

**Comment by lantis1008** [comment]
thanks guys, that narrows it down, and definitely means it was caused by https://github.com/ericpaulbishop/gargoyle/commit/1280cd65095eb14945a7d431b07396820f88ea45

**Comment by crackself** [comment]
@LoveyCat the same errors

**Comment by LoveyCat** [comment]
waiting for your good news ^_^

**Comment by crackself** [comment]
@lantis1008 wow! 👍

**Comment by lantis1008** [comment]
Can you guys test #644 please

**Comment by crackself** [comment]
I‘m building the firmware,will feedback later

**Comment by lantis1008** [comment]
It is night here. I won't see reply for 8 hours. Hopefully is ok otherwise I will look tomorrow.

**Comment by crackself** [comment]
need times to complete new building,see you tomorow.v

**Comment by crackself** [comment]
need times to complete new building,see you tomorow.
EDIT:
the change work.but there some others problem come up.I build by make FULL_BUILD=ture ar71xx.usb_large_nand TRANSLATION=internationallize FALLBACK_LANG=English-EN ACTIVE_LANG=SimplifiedChinese-ZH-CN,the system could not to load plugins source、overview page have blank messages and menu have addition character。
![pic_quark_1502123342091](https://user-images.githubusercontent.com/16448332/29036242-4174df7e-7b64-11e7-963c-dc22f497a661.jpg)

**Comment by crackself** [comment]
that proble cause by router firmware cache,not a bug.

**Comment by crackself** [comment]
@lantis1008 here a confusion about the language setting,although build by make FULL_BUILD=ture ar71xx.usb_large_nand TRANSLATION=internationallize FALLBACK_LANG=English-EN ACTIVE_LANG=SimplifiedChinese-ZH-CN,language show blank name,any suggest about this?
![1](https://user-images.githubusercontent.com/16448332/29069932-8cf658b8-7c6f-11e7-9f4b-5d9905012b8b.png)

it will show full name after reflash plugin.

**Comment by fengchen-github** [comment]
![page_error](https://user-images.githubusercontent.com/16919103/29100837-dd539a16-7ce0-11e7-86a1-cb83e9c66fb7.png)
wireless disabled

**Comment by lantis1008** [comment]
@fengchen if your issue is about your x86 device without a wireless device then please create a separate issue. 

And as I said before, I don't think it is supported. 

If it is related to the issue being discussed, please elaborate. 

@crackself I will look into this

**Comment by d3fz** [comment]
Hi, i've also noted the language description display bug, i think it's been around since 1.9.0, not sure.

After installing additional language pack:
![8rxxtms - imgur](https://user-images.githubusercontent.com/22578839/29152147-1a5a5be0-7d5c-11e7-9b69-d5f8154c6048.png)

This is what it looks like in "Plugins", before refreshing packages:
![0l1vaja - imgur](https://user-images.githubusercontent.com/22578839/29152226-a5e6c2f2-7d5c-11e7-91a0-a2b37687c482.png)

Clicking "Refresh Plugins" button solves the problem, but only temporarily.
![bsfr5p7 - imgur](https://user-images.githubusercontent.com/22578839/29152334-56878b14-7d5d-11e7-807c-260a699dac1e.png)

**Comment by lantis1008** [comment]
Am still looking into this. Interesting behaviours when you do and don't refresh the plugins. 
I believe the "description" field doesn't exist until you do it.

**Comment by d3fz** [comment]
Is this issue related ?

https://github.com/ericpaulbishop/gargoyle/issues/141

**Comment by lantis1008** [comment]
Yes for sure

**Comment by lantis1008** [comment]
@ericpaulbishop any comment here?
Is this something that can be resolved through gpkg modification (looks like preinstalled packages are losing description field) or should a workaround like displaying the package name if description is not present be implemented?

**Comment by ericpaulbishop** [comment]
I don't think it's related to what was going on with #141. I think this is more likely due to not preserving data for pre-installed packages due to space constraints on some routers. The directive CONFIG_CLEAN_IPKG_PARTIAL=y set in many of the config files and wipes out this data. 

The best solution may be to update what that directive does so that the data isn't removed for any package that has "plugin-gargoyle" in it's name.

**Comment by lantis1008** [comment]
Great. 
I can look into that unless you're already on the case?

**Comment by ericpaulbishop** [comment]
Please do. There's a gargoyle-specific generic patch that adds CONFIG_CLEAN_IPKG_PARTIAL support (it's something I added, it's not from openwrt) that you can modify to implement this.

**Comment by lantis1008** [comment]
This should now be addressed

**Comment by crackself** [comment]
@lantis1008 @ericpaulbishop thanks your effort.here's feedback message by using the patch:
first build,without set zh_cn LANG pluging as build-in in the config,comple by `make FULL_BUILD=true ar71xx.usb_large_nand TRANSLATION=internationalize ACTIVE_LANG=SimplifiedChinese-ZH-CN`，the web interface show server error.ssh conect and run `firstboot` will bright back EN inteface.
second build: I modify the config ,setting localize LANG as prebuild plugin. About build.sh,before line 673 (		make $num_build_thread_str V=99 GARGOYLE_VERSION="$numeric_gargoyle_version" GARGOYLE_VERSION_NAME="$lower_short_gargoyle_version" GARGOYLE_PROFILE="$default_profile")
add
 `# enter packge select UI
			echo -e "                 Going to setting Menuconfig  "
			echo -e "                Prees "Y" for continue! "N" for Canncle! "
			echo "**************************************************************************"
		read ANSWER
		if [ $ANSWER = 'Y' -o $ANSWER = 'y' ] ; then
			make menuconfig
		elif [ $ANSWER = 'N' -o $ANSWER = 'n' ] ; then
			echo ""
		fi`
then it show the menuconfig select before build start,I just exit and without save anything ,finally the output firmware get the localize web, aslo with name show in plugin.
so,I guest is that to do with the cache of packages(or plugins) in build dir?
