### ISSUE TITLE
bcm5709C supported

### ISSUE THREAD

**Issue by LoveyCat** [ericpaulbishop/gargoyle#647]
I'm running a x86 router.But when I compile image for it ,I didn't find bcm5709 driver in makemenuconfig.
Does bcm5709C Gbit network card can be supported in gargoyle? 
Lede project already support this card by kmod-bnx2 kernel module.
![2017-08-19_205309](https://user-images.githubusercontent.com/14886041/29486813-422601ca-8521-11e7-90cb-e7eb0c80f018.png)

**Comment by lantis1008** [comment]
Gargoyle is currently a few kernel versions behind. 

You can backport the driver. 
http://www.pastebin.com/b9vLxKfh

The user I originally wrote this for never ended up having any success. 

I have a precompiled driver here
http://lantisproject.com/gargoyle_custom/gui_overhaul/
But I can't remember what kernel version it was done for.

**Comment by LoveyCat** [comment]
Many thanks, I'll test it  :)

**Comment by lantis1008** [comment]
Did you have success?

**Comment by LoveyCat** [comment]
no, it's so hard to me. I'm waiting for switching to lede

**Comment by LoveyCat** [comment]
@lantis1008 Thanks for your help, I test again today,  use your patch, it works now on 10.0.x

**Comment by lantis1008** [comment]
Fantastic. 
Well done on getting it to work.
