### ISSUE TITLE
Bump MiniDLNA version to 1.2.1

### ISSUE THREAD

**Issue by d3fz** [ericpaulbishop/gargoyle#648]
Would it be possible to bump MiniDLNA version from 1.1.5 to 1.2.0 ?

Changelog:
https://sourceforge.net/projects/minidlna/files/minidlna/1.2.0/

1.2.0 - Released 17-May-2017
--------------------------------
- Add libavformat > 57 compatibility.
- Add TiVo Bonjour discovery support using Avahi for Bolt.
- Improve Samsung BD-J5500 support.
- Add quirk to fix video playback on Hyundai TVs.
- Add non-destructive update rescan support.
- Enhance bookmark support to work with Kodi.

**Comment by lantis1008** [comment]
Looks good. 
I'll do it in the next week.

Will require minor patch update and the UI to be modified slightly.

**Comment by d3fz** [comment]
Great.
Thanks Lantis.

Since you're at it, may i suggest a slight modification to "www/js/minidlna.js" file to go with this as well ?

From (Line 193/194):
`			uci.set(pkg, sec, "db_dir", base + "/_minidlna");`
`			uci.set(pkg, sec, "log_dir", base + "/_minidlna");`
To:
`			uci.set(pkg, sec, "db_dir", base + "/.minidlna");`
`			uci.set(pkg, sec, "log_dir", base + "/.minidlna");`

This should stop the generated "minidlna" folder from showing up on the TV.

**Comment by lantis1008** [comment]
I can check that. I might leave it as is and use this functionality instead. I'll just generate a file into it. 
https://github.com/ericpaulbishop/gargoyle/blob/master/package/minidlna/patches/020-ignore-directory.patch

**Comment by d3fz** [comment]
Quick update. New version released 3 days ago.

1.2.1 - Released 24-Aug-2017
--------------------------------
- Added Movian client detection and subtitle support.
- Fixed an issue with discovery on non-Linux systems.
- Fixed Bonjour discovery compatibility with TiVo Bolt.
- Fixed NFO file parsing, and added change monitoring support for them.
- Added a workaround for video thumbnails on some Samsung clients.
- Added DoS protection for event subscriptions.
- Fixed content browsing issues with some Samsung TVs.
- Improved non-destructive update scan support.

**Comment by lantis1008** [comment]
I was in the procsss of testing 1.2.0
Off we go again

**Comment by d3fz** [comment]
Sorry, didn't mean to cause any rework. Since the ”issue” was still open, i thought it could be a good idea to address to this brand new version.

If you need any help testing this, i'll be glad to help. I use this functionality almost everyday.

**Comment by lantis1008** [comment]
No dramas at all :)
If it's worth doing once it's worth doing twice. 

I'll let you know how testing goes. If you are able to produce your own images then I will provide the source code otherwise I may be able to build you something

**Comment by lantis1008** [comment]
I'm testing 1.2.1 now. I couldn't make rapid re-scan work, so i'm leaving it out of the UI for now. 
If when it gets merged you want to test and figure out exactly how it works, by all means we can put it in to the UI.

**Comment by d3fz** [comment]
Great.

I'll definitely test the "non-destructive update rescan", as this is the main new feature i'm really interested in.

If i get it to work, i'll let you know, so we can make the proper changes to the UI.

Thank you Lantis.

**Comment by lantis1008** [comment]
Feel free to compile based on that and test yourself.

**Comment by d3fz** [comment]
Will do. Should i close this issue now or only when it gets merged ?

**Comment by lantis1008** [comment]
Leave it as is. 
I've set up the PR so it should auto close this issue when it is merged. 

Let me know if any issues. 
Feel free to open separate issue about the non destructive rescan or resurrect this one.
