### ISSUE TITLE
Run Gargoyle x86 on VMware

### ISSUE THREAD

**Issue by kuoruan** [ericpaulbishop/gargoyle#655]
gargoyle_1.9.2-x86-geode-combined-jffs2-128k.img
I want to run Gargoyle on VMware with x86 version.
But it stuck at "Switched to clocksource refined-jiffies" when booting up.
Any help?

**Comment by fengchen-github** [comment]
jffs2 format does not support hard disk, you have to compile using ext4 format

**Comment by kuoruan** [comment]
OK, Thanks.
