### ISSUE TITLE
OpenVPN getting out of date

### ISSUE THREAD

**Issue by ispyisail** [ericpaulbishop/gargoyle#663]
Hi all

I notice the newest OpenVPN client complaining the the OpenVPN server is out of date.

https://openvpn.net/index.php/open-source/downloads.html

![warning](https://user-images.githubusercontent.com/12116110/31373487-b682433c-adf6-11e7-8ae6-302ab706c745.jpg)

**Comment by ispyisail** [comment]
> Tue Oct 10 20:00:11 2017 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6

> Tue Oct 10 20:00:11 2017 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.

> Tue Oct 10 20:00:13 2017 WARNING: INSECURE cipher with block size less than 128 bit (64 bit).  This allows attacks like SWEET32.  Mitigate by using a --cipher with a larger block size (e.g. AES-256-CBC).

> Tue Oct 10 20:00:13 2017 WARNING: cipher with small block size in use, reducing reneg-bytes to 64MB to mitigate SWEET32 attacks.

> Tue Oct 10 20:00:18 2017 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

**Comment by ispyisail** [comment]
https://community.openvpn.net/openvpn/wiki/DeprecatedOptions#DeprecatedOptionsinOpenVPN

Options no longer used

**Comment by ispyisail** [comment]
Some useful research has been done here

https://www.gargoyle-router.com/phpbb/viewtopic.php?f=11&t=11247

**Comment by ericpaulbishop** [comment]
I'm setting the default cipher to AES-CBC-256 and replacing ns-cert-type with remote-cert-tls. 

auth-nocache is kind of pointless given that everything gets saved to flash anyway, so worrying about what's in memory is the least of your problems if someone has root access to the device.
