### ISSUE TITLE
Status page "Device Configuration" show blank

### ISSUE THREAD

**Issue by crackself** [ericpaulbishop/gargoyle#666]
Device Configuration on status page do not match anything：

![status](https://user-images.githubusercontent.com/16448332/31541813-74723ada-b042-11e7-8752-d9d944adf071.png)
build with source commit 5e29860bed3c0374d6e6f840456804323798386a,should I remove it from overview.sh?

**Comment by lantis1008** [comment]
That field is one of two values, both populated from the language file.
Either "Gateway" or "Bridge". It works fine on my build?

**Comment by crackself** [comment]
Yes,I find that  in   `gargoyle/package/plugin-gargoyle-i18n-English-EN/files/www/i18n/English-EN/overview.js `,aslo check it in my router `/www/i18n/English-EN/overview.js`.My router setting as an wireless AP,it should be a Gateway device

**Comment by lantis1008** [comment]
Can you debug the loading of that variable in a browser console?

**Comment by crackself** [comment]
yes, it seems may cause due to I modify some JS files, please have a look .
Many Thanks!
![error](https://user-images.githubusercontent.com/16448332/31544854-5d868436-b04f-11e7-9550-bfd41f38c89f.png)

**Comment by lantis1008** [comment]
Can you provide your SH and JS files that you have modified? I can’t see anything from that information.

**Comment by crackself** [comment]
Thanks tips, it cause by `ovwS.Openwrt Interface="WEB GUI";` in overview.js；correct it as `ovwS.Openwrt_Interface="WEB GUI";`
