### ISSUE TITLE
OpenVPN default cipher is not AES-CBC-256?

### ISSUE THREAD

**Issue by ispyisail** [ericpaulbishop/gargoyle#668]
Hi Eric

I've done a couple of builds and much testing but the default is still blowfish?

see screen shot for defaults

![default](https://user-images.githubusercontent.com/12116110/31597170-6fd861f8-b2a3-11e7-9ebe-8bd95ec2df64.jpg)

**Comment by lantis1008** [comment]
i just tried this on latest build and it defaulted to 256

**Comment by ispyisail** [comment]
Interesting

I did two builds and installed Firefox to check for caching problems but it still defaulted to blowfish?

I'll try again with the next build?

**Comment by lantis1008** [comment]
any update
?

**Comment by ispyisail** [comment]
I've done many installs now and they all default to 128 blowfish?

Having said that in the big picture it doesn't really matter?
