### ISSUE TITLE
Themes CSS rules being overridden by Bootstrap's defaults

### ISSUE THREAD

**Issue by d3fz** [ericpaulbishop/gargoyle#672]
If any custom CSS rule is created inside common.css/internal.css, does not get applied, because it's being overridden by Bootstrap's default style. 

The problem:
```
<link rel="stylesheet" href="/themes/Gargoyle/common.css?1.9.X--Built-20170613-1957-git-7cf7ad1-"/>
<link rel="stylesheet" href="/themes/Gargoyle/internal.css?1.9.X--Built-20170613-1957-git-7cf7ad1-"/>
<script src="/js/common.js?1.9.X--Built-20170613-1957-git-7cf7ad1-"></script>
<script src="/js/overview.js?1.9.X--Built-20170613-1957-git-7cf7ad1-"></script>
<script src="/js/table.js?1.9.X--Built-20170613-1957-git-7cf7ad1-"></script>
<script src="i18n/English-EN/strings.js?1.9.X--Built-20170613-1957-git-7cf7ad1-"></script>
<script src="/i18n/English-EN/overview.js?1.9.X--Built-20170613-1957-git-7cf7ad1-"></script>
<script src="/themes/Gargoyle/theme.js?1.9.X--Built-20170613-1957-git-7cf7ad1-"></script>
<link rel="stylesheet" href="/themes/Gargoyle/bootstrap.min.css?1.9.X--Built-20170613-1957-git-7cf7ad1-">
<link rel="stylesheet" href="/themes/Gargoyle/theme.css?1.9.X--Built-20170613-1957-git-7cf7ad1-">
```
Shouldn't "bootstrap.min.css" be the first stylesheet included? Only then the themes specific CSS.
```
<link rel="stylesheet" href="/themes/Gargoyle/bootstrap.min.css?1.9.X--Built-20170613-1957-git-7cf7ad1-">
<link rel="stylesheet" href="/themes/Gargoyle/common.css?1.9.X--Built-20170613-1957-git-7cf7ad1-"/>
<link rel="stylesheet" href="/themes/Gargoyle/internal.css?1.9.X--Built-20170613-1957-git-7cf7ad1-"/>
<link rel="stylesheet" href="/themes/Gargoyle/theme.css?1.9.X--Built-20170613-1957-git-7cf7ad1-">
```
Also, is it really necessary to include 3 CSS files (more http requests) just for the theme? Couldn't we merge all CSS files into one? Or maybe cut down to only two, to keep things more organized.

**Comment by lantis1008** [comment]
I disagree. 
Common and internal should be first (arguably bootstrap before both) and theme last. 
Theme should override all others. 
Common and internal are probably going to be rarely edited by a new theme. And even if they are, it should be done in the theme file in my opinion to minimize repetitive inclusion of files.

**Comment by lantis1008** [comment]
Combining common and internal I’m ok with

**Comment by d3fz** [comment]
My mistake, theme.css being the **last** and moving bootstrap to the **top**. Would solve the mentioned problem.

+1 for combining common and internal. One less request.

**Comment by lantis1008** [comment]
I’ll look at this at some point (unless you want to?)
Just need to check reordering won’t break any of the themes behaviour

**Comment by d3fz** [comment]
Had a look at gargoyle_header_footer.c, but i can't test it.

Is this correct ?
http://www.mergely.com/GOKv3BZX/

**Comment by d3fz** [comment]
Another reason why this would be helpful is that putting all stylesheet files before scripts, would make pages load (slightly) faster.  

I don't see why this change would break any of the themes behaviour, but it's worth a look.

**Comment by lantis1008** [comment]
I think that is correct. i'd need to compile to test

**Comment by lantis1008** [comment]
@d3fz is this stopping you pushing your new theme? or what is going on there? If so i'll get it done, otherwise it will just continue to rot until i find time

**Comment by d3fz** [comment]
Hi, @lantis1008.

Stopping from pushing? Actually, no. I've just been short on time. But organizing these files order a little better could help decrease page loading times, even if slightly. 

Also, reducing/merging theme CSS files would be helpful as well. Any easy approach for this?  

*Does this proposed solution still applies?*
>Had a look at gargoyle_header_footer.c, but i can't test it.
>Is this correct?
>http://www.mergely.com/GOKv3BZX/

**Comment by lantis1008** [comment]
Please close as of #784 
Sorry it took so long!

**Comment by d3fz** [comment]
No worries at all! Thank you for looking into it.

Closed.

**Comment by d3fz** [comment]
@lantis1008, 

Regarding the merging of `internal.css` into `common.css` made in #784, what about this header section `-c "internal.css"`, presented on every `page/*.sh file`? Should it also be changed/removed?

### Taking `hosts.sh` page header as example
```bash
<%
	# This program is copyright © 2008-2013 Eric Bishop and is distributed under the terms of the GNU GPL
	# version 2.0 with a special clarification/exception that permits adapting the program to
	# configure proprietary "back end" software provided that all modifications to the web interface
	# itself remain covered by the GPL.
	# See http://gargoyle-router.com/faq.html#qfoss for more information
	eval $( gargoyle_session_validator -c "$COOKIE_hash" -e "$COOKIE_exp" -a "$HTTP_USER_AGENT" -i "$REMOTE_ADDR" -r "login.sh" -t $(uci get gargoyle.global.session_timeout) -b "$COOKIE_browser_time"  )
	gargoyle_header_footer -h -s "status" -p "hosts" -c "internal.css" -j "gs_sortable.js  common.js hosts.js table.js" -z "hosts.js basic.js" -i -n dhcp wireless
%>
``` 
It doesn't break anything as is, but this stylesheet include will still be generated (and now invalid):
```html
<link rel="stylesheet" href="/themes/Gargoyle/internal.css?1.11.X--Built-20180806-1612-git-3d4c0b7-"/>
```
I wonder if it could point to an invalid file path if internal.css is completely removed?

**Comment by lantis1008** [comment]
Yep will remove them all. It’ll cause a non fatal error, but we don’t need that

**Comment by lantis1008** [comment]
Done in 22842074f52dd71ccb90c5aac652efb74e7aad15
