### ISSUE TITLE
webgui has a lot of 'undefined' and 'length' errors (Built 20171027-1210 git@ab16f95)，chrome62_x64

### ISSUE THREAD

**Issue by fengchen-github** [ericpaulbishop/gargoyle#673]
![chrome](https://user-images.githubusercontent.com/16919103/32108218-904f64f4-bb63-11e7-9678-65e817917300.png)

![undefined length](https://user-images.githubusercontent.com/16919103/32108377-14c3f312-bb64-11e7-93ef-082bda1da075.png)

**Comment by crackself** [comment]
No this problem to me,may be you have to make clean then make with full build,or it may some files change error. Look at this #666

**Comment by fengchen-github** [comment]
I deleted all the files, re-downloaded the source code, recompiled, did not modify any files, but the problem remains.
In IE11 and firefox have the same problem.
The following is the .config file.

[.config.zip](https://github.com/ericpaulbishop/gargoyle/files/1423919/default.config.zip)

**Comment by crackself** [comment]
It seems you're build for x64 device,? `CONFIG_TARGET_x86_64_Default=y`.But this program may not have a complete support.(check from https://www.gargoyle-router.com/download.php).

**Comment by fengchen-github** [comment]
yes,thanks
