### ISSUE TITLE
Disabling wireless erases settings.

### ISSUE THREAD

**Issue by sheddup** [ericpaulbishop/gargoyle#675]
It would be nice if disabling wireless didn't erase the current wireless config, sometimes I need to take down the WiFi while I troubleshoot other issues in the network.

**Comment by lantis1008** [comment]
The wireless schedule plugin allows you to take the wifi down temporarily with a button press. 
You could take the wifi down from the command line if that is accessible for you. 


You make a good point, but having looked at the code behind that page it is potentially a big rewrite to support what you are suggesting.

**Comment by sheddup** [comment]
Guess I'll use the plugin, thanks 👍
