### ISSUE TITLE
Port eko.one.pl reset features to gargoyle

### ISSUE THREAD

**Issue by ispyisail** [ericpaulbishop/gargoyle#677]
Hi Eric

It appears that @obsy has added a reset feature to his builds

https://eko.one.pl/?p=openwrt-gargoylepl-cc

Any chance of porting these features?

Button operation:

- "WPS / QSS / WI-FI" held down to 2s turns on / off the radio interfaces, if previously configured in the GUI.

- "reset" held from 3s to 10s will restart the device.

- "reset" held from 11s to 90s restores the default ( firstboot ) and restart the device.

 If the device does not have a button, the function is not supported or is under another button. The operation of these buttons is programmable, so they will work if the router is running the system and its proper configuration. 

From the original images, these builds differ in a different set of packages, by default Polish translation, pre-set some elements of the system (other buttons support, settings for Polish time zone, etc.) and some system scripts (sysinfo, wifionoff).

 Gargoyle is a graphical overlay on OpenWrt; therefore - what can not be set in gui can be set using the console; All OpenWrt tutorials can be used in Gargoyle. However, remember that after manually changing the gui configuration you may not know about it and overwrite it with your settings.

**Comment by obsy** [comment]
This is standard openwrt behavior... I'm referring to the name of the buttons, not the code depending on the router model.
`#!/bin/sh

uci batch <<EOF
set system.wps_button=button
set system.wps_button.button='wps'
set system.wps_button.action='released'
set system.wps_button.handler='logger reboot ; /sbin/wifionoff ;'
set system.wps_button.min='0'
set system.wps_button.max='2'
set system.rfkill_button=button
set system.rfkill_button.button='rfkill'
set system.rfkill_button.action='released'
set system.rfkill_button.handler='logger reboot ; /sbin/wifionoff ;'
set system.rfkill_button.min='0'
set system.rfkill_button.max='2'
set system.btn2_button=button
set system.btn2_button.button='BTN_2'
set system.btn2_button.action='released'
set system.btn2_button.handler='logger reboot ; /sbin/wifionoff ;'
set system.btn2_button.min='0'
set system.btn2_button.max='2'
set system.reboot_button=button
set system.reboot_button.button='reset'
set system.reboot_button.action='released'
set system.reboot_button.handler='logger reboot ; /usr/lib/gargoyle/reboot.sh ;'
set system.reboot_button.min='3'
set system.reboot_button.max='10'
set system.reset_button=button
set system.reset_button.button='reset'
set system.reset_button.action='released'
set system.reset_button.handler='logger restore defaults ; /sbin/firstboot -y; reboot ;'
set system.reset_button.min='11'
set system.reset_button.max='90'
commit system
EOF`

**Comment by lantis1008** [comment]
Don’t we already have (some of) this functionality for some models?
https://github.com/ericpaulbishop/gargoyle/blob/master/patches-generic/017-ar71xx-button-handlers.patch

**Comment by obsy** [comment]
Mine is just more general

**Comment by d3fz** [comment]
@ispyisail, did you see issue #681? Does it address the functionality you mentioned here?

**Comment by lantis1008** [comment]
We have a few options here.
Continue using [this patch](https://github.com/ericpaulbishop/gargoyle/blob/master/patches-generic/017-ar71xx-button-handlers.patch) and other variants like it and make it device specific
or
Go to a more generic button handler (like @obsy )

Not my decision to make, but happy to be involved in either option.

**Comment by d3fz** [comment]
+1 for the generic button handler. It would probably address far more/newer routers in the long run, like [Gargoyle Pocket Router (v3)](https://www.gargoyle-router.com/phpbb/viewtopic.php?f=8&t=11331&p=47612#p47603)
