### ISSUE TITLE
Update screen hangs even though update is successful

### ISSUE THREAD

**Issue by joequant** [ericpaulbishop/gargoyle#679]
gargoyle_1.10.x-ar71xx-generic-archer-c7-v2-squashfs-sysupgrade.bin

| Gargoyle version 1.10.X   | OpenWrt Chaos Calmer branch        |
| Gargoyle revision 1e703430| OpenWrt commit 216adcf             |
| Built November 04, 2017   | Target  ar71xx/ath10k-large        |

When I do an update to a new image when keeping the router settings, the screen hangs, although the update itself is successful.

**Comment by lantis1008** [comment]
I can’t rememeber if this was always the case, but I think it can be solved very easily using the same method that the backup/restore page uses. 
I’ll look into it.

**Comment by d3fz** [comment]
Another user reported the [same behavior](https://www.gargoyle-router.com/phpbb/viewtopic.php?f=3&t=11271&p=47586#p47586) on the forum not too long ago.

Does the reboot page share the same method of backup/restore pages?

**Comment by lantis1008** [comment]
So it seems that the upgrade process has become complex, with different platforms requiring different processes. 

We used to look for the “reboot” command getting executed but it looks like this isn’t that reliable anymore. There also seems to be no generic thing we can look for. 
We might be able to look for the following text sent to the shell:
“Rebooting...”
“Sysupgrade successful”
Others?

More digging to be done.
