### ISSUE TITLE
Two web ui bug?

### ISSUE THREAD

**Issue by crackself** [ericpaulbishop/gargoyle#683]
1. Status > SQoS Distribution show blank after update firmware by checkt Attempt to Preserve Settings
2. Setting default LANG as ZH_CN （build command `make FULL_BUILD=true ar71xx.usb_large_nand TRANSLATION=internationalize ACTIVE_LANG=SimplifiedChinese-ZH-CN` ), when first boot after update,  some language named as undefined .

![debug](https://user-images.githubusercontent.com/16448332/32786361-ae38f460-c98e-11e7-892e-0b669d9d3ae1.jpg)
![screenshot-2017-11-14 gargoyle](https://user-images.githubusercontent.com/16448332/32786377-bb6bc158-c98e-11e7-805d-44d5e20bb70e.png)

**Comment by crackself** [comment]
the firmware build from the laste update (14/11/2017)

**Comment by ispyisail** [comment]
> Attempt to Preserve Settings

Try without preserving settings?

**Comment by lantis1008** [comment]
Please provide a translation for 
`”TiZ.IRST = Iran”;`
To fix the other issue. I will do the commit if you don’t want to.

**Comment by crackself** [comment]
@lantis1008 It should be "TiZ.IRST = 伊朗",thank.
