### ISSUE TITLE
Historical B/W Distribution data changing/wrong

### ISSUE THREAD

**Issue by rpodric** [ericpaulbishop/gargoyle#684]
Something is going on with daily totals in B/W distribution. Reboots can cause it, but they're not the exclusive cause. 

Here is the first example:

**Before reboot (reboot done via menu, not cold):**
14th (partial day) 1.6GB down, 75MB up
13th: 7.6GB down, 192MB up
12th: 1.3GB, 240MB up

**After reboot:**
14th:  near zero (I just rebooted, so sort of expected, but I could have _sworn_ data used to survive proper reboots)
13th: 1.6GB down, 75MB up (shifted down from the 14th)
12th: 7.6GB down, 192MB up (shifted down from the 13th). 

**Second example,** on a router with a 7+ day uptime (point is to show that reboots aren't the only cause). No shifting in this case, just wrongness.

Format: What router says _on the 13th_ for DL over the past week / What router _said_ at the end of each day for DL.

Nov 13: 30.6GB / same
Nov 12: 24.7GB / same
Nov 11: 32.8GB / same
Nov 10: 65.6GB / 73.5GB (going backwards, this is when things started changing)
Nov 9: 8.5GB / 29.8GB
Nov 8: 1.6GB / 39.5GB
Nov 7: 27GB / 13GB
Nov 6: 39GB / 13.7GB (router rebooted around this time)

These sorts of things are happening on three Archer C7v2 routers and one WNDRMACv2. All are on 1.10, but I don't know if it's new to that release.

**Comment by lantis1008** [comment]
I believe this should be solved by https://github.com/ericpaulbishop/gargoyle/commit/0ddf9b7c0ae4ed931924cb7c8e74be6cf291baf4

**Comment by rpodric** [comment]
Thanks very much, I'll look for it.
