### ISSUE TITLE
Web Monitor getting stuck on router reboot

### ISSUE THREAD

**Issue by d3fz** [ericpaulbishop/gargoyle#686]
As discussed in [this thread](https://www.gargoyle-router.com/phpbb/viewtopic.php?f=12&t=11180), it seems like the Web Monitor gets stuck for no apparent reason, regardless of what limit is set to.

I've also scheduled my router to reboot every week, and every time the router reboots, webmon logged for the next minute, then got stuck. Tried manual reboot, same problem. This was after reaching the limit of 500 entries, and all working as expected for a few days. 

I kept testing it to be sure, and after another weekly scheduled reboot (every Monday 5am), Web Monitor got stuck again (this time with 184 entries, limit=500), about one minute after reboot. Another user reported the exact behavior on the forum, so I think it's safe to say that a reboot triggers the problem.

Logread did not show anything relevant when that happened.

I have pretty much all services enabled, QoS, Quotas, etc.

Can anyone else confirm this?

**Comment by ViBE-HU** [comment]
Today I restarted my router and history just gone. No entries. And it also stopped so no new ones. I guess reset will fix this but I don't try this time.

**Comment by lantis1008** [comment]
I believe this is fixed now. Please test and close

**Comment by d3fz** [comment]
Closed. Thank you Lantis.
