### ISSUE TITLE
Panel: "OpenVPN Server: Allowed Clients" - regenerated VPN client does not block access to the server using previous key.

### ISSUE THREAD

**Issue by netmonitoring** [ericpaulbishop/gargoyle#688]
Panel: "OpenVPN Server: Allowed Clients" - regenerated VPN client does not block access to the server using previous key.

**Tested on:**

Router Model: Archer C7 V2 EU
Firmware: Gargoyle 1.10.0-ar71xx

**Test to reproduce:**

1. Create VPN client with name "test", push "Add" button, push "Save Changes". Download OVPN configuration and make sure your connection was established successfully.

2. Remove VPN client with name "test" and push "Save Changes".

3. Create VPN client with name "test" again, push "Add" button, push "Save Changes". And reboot router.

4. When router is up to use, try to connect to VPN using keys created first time. Make sure your connection was established successfully. **Furthermore, now you can use both OVPN configurations (first and last one) and they will work.**

Comparing new OVPN configuration file with OVPN created first time, i can see that **`<cert></cert>`** content differs, at: Validity, Modulus, "Subject Key Identifier", "Digital Signature" and CERTIFICATE. Also differs **`<key></key>`**.

All other content is the same, including **`<ca></ca>`** and **`<tls-auth></tls-auth>`**

**Old client should not be able to connect with his private/public key.**

**Comment by lantis1008** [comment]
This should be fixed by my patch set. Thanks for pointing it out
