### ISSUE TITLE
Panel: "OpenVPN Server: Allowed Clients" - checkbox "Enabled" for VPN client does not work.

### ISSUE THREAD

**Issue by netmonitoring** [ericpaulbishop/gargoyle#689]
Panel: "OpenVPN Server: Allowed Clients" - checkbox "Enabled" for VPN client does not work.

**Tested on:**

Router Model: Archer C7 V2 EU
Firmware: Gargoyle 1.10.0-ar71xx

**Test to reproduce:**
1. Create VPN client, push "Add" button, then push "SaveChanges".
2. Now, when VPN client is ready and checkbox "Enabled" is ticked, untick "Enabled" and push "SaveChanges".

**The result:** After changes apply, the checkbox is ticked again. And client still can connect.

**Disabled client should be not able to connect.**

**Comment by netmonitoring** [comment]
If option enabled 'false' is set manually via ssh in '/etc/config/openvpn_gargoyle' for specified client, it still can connect. **Option enabled is ignored at all.**

**Comment by ispyisail** [comment]
Because I'm a visual person

![image](https://user-images.githubusercontent.com/12116110/34027797-f7c53fec-e1c3-11e7-8bc2-370180d97bf8.png)

**Comment by lantis1008** [comment]
This is now resolved. The certificate gets properly revoked.
If the client is connected at the time the certificate is revoked, you will need to disconnect them somehow (restart Openvpn). They won't be able to connect anymore.

`If option enabled 'false' is set manually via ssh in '/etc/config/openvpn_gargoyle' for specified client, it still can connect.`
Manually editing the config files does nothing unless you then trigger the correct services to re-read them. Please let Gargoyle do this for you unless you know what you are doing.
