### ISSUE TITLE
Restrictions not blocking

### ISSUE THREAD

**Issue by ispyisail** [ericpaulbishop/gargoyle#694]
see
https://www.gargoyle-router.com/phpbb/viewtopic.php?f=12&t=11039#p45512

I did my own test to confirm

![image](https://user-images.githubusercontent.com/12116110/33512414-d7413d7c-d794-11e7-94fa-823efb233294.png)

**Comment by lantis1008** [comment]
Confirmed.
Currently investigating.

Temporary workaround:
If you want to exclude 1 ip (for example 192.168.1.40), also include 1 other dummy IP that is not in use (e.g. 192.168.1.200).
This will obviously also exclude the dummy IP, so make sure it is not in use by another device.
