### ISSUE TITLE
Need Help: 1.8.1 branch based on BB, but the svn in build.sh does not work anymore

### ISSUE THREAD

**Issue by tacuar** [ericpaulbishop/gargoyle#696]
@ericpaulbishop  Hi dear Eric, sorry, but here i am in China and for some reason we can't open:

svn://svn.openwrt.org/openwrt

thus , when i run make FULL_BUILD=true custom, the build.sh can not carry on, download fails.

as far as i know, the latest 1.10 stable brance uses git instead of svn, so everything is okey.

I am new to gargoyle and really hopes to know how to modify the build.sh script (starting from the below lines), so the compiling would work for 1.8.1 branch? i know the svn shall be replaced by git, but i can't figure it out how. Thank you!!!

#download openwrt source if we haven't already
if [ ! -d "$openwrt_src_dir" ] ; then
	revision=""
	if [ -n "$rnum" ] ; then
		revision=" -r $rnum "
	fi
	echo "fetching openwrt source"
	rm -rf "$branch_name" "$branch_id"
	if [ "$branch_is_trunk" = "1" ] ; then 
		svn checkout $revision svn://svn.openwrt.org/openwrt/trunk "$branch_id"
	else

**Comment by lantis1008** [comment]
These two commits at a minimum 
https://github.com/ericpaulbishop/gargoyle/commit/f8bb38712c73e284fd3ad62131c3851db40dc677
https://github.com/ericpaulbishop/gargoyle/commit/1fa540e4ca6fbfb84b0a20aedc266933c88d5dac

As I’m sure you’re aware, 1.8.1 is severely outdated and has security holes. You should use the latest where possible. 

SVN for Openwrt was deprecated. It has nothing to do with Chinese Internet

**Comment by tacuar** [comment]
@lantis1008 Thank you Michael !   

i will try to solve it again even not sure i 'm able to sort it out or not .

1.10 is very good for sure and it patched recent krack vulnerability and i've deployed on one of my device.

for the 1.8.1 branch i just hope to make the source still "can be compiled without problem".

previously since i also have 1.10 as well , then i turned to the correspoding build.sh file to check the lines and tried to modified the svn to git.

**Comment by tacuar** [comment]
@lantis1008 hi Michael, sorry, i know you've got lots of things to do both here or in gargoyle forum and huge local works.

but is possible you could update here the build.sh for branch 1.8.1, so that the build.sh could work still?

I tried to modify some lines according to your direction but as a newbie, this seems beyond my ability at this moment.

1.8.1 is a branch old, but still hope that we could reserve it as a memory or record.

Really thank you

**Comment by lantis1008** [comment]
I'm not very interested in fixing an old version. So i'm not really willing to go to the effort of pushing a patch to that branch. If we fixed that one, shouldn't we then go back and fix EVERY version? That feels like a big waste of time for me.
Maybe @ericpaulbishop is interested in fixing older branches? But i'm not.

In any case, the below patch (which is just a rehashing of the above two commits i mentioned + 1 extra) should get your build up and running. However, you may run into source files which won't download due to no longer existing on the content servers. That's not my problem.

[fix181patch.txt](https://github.com/ericpaulbishop/gargoyle/files/1558495/fix181patch.txt)

**Comment by tacuar** [comment]
@lantis1008 indeed, Michael, it's really a waste of time actually and, the treasure thing is, even it's a waste of time, you still provided a fix181patch, that's so kind of you and i really appreciate and i want to thank you for doing this, if someone else saw this and thus could happen to them as well.

Wish you all the Best !

**Comment by lantis1008** [comment]
No problem at all
