### ISSUE TITLE
Wget: can not be compiled into the firmware?

### ISSUE THREAD

**Issue by tacuar** [ericpaulbishop/gargoyle#701]
I've tried several times, under the menuconfig interface, NETWORK--Wget Default, even i choose to install this, the firmware compiled still don't have the wget, don't know why.

It might be due to the dependencies problem, because i don't see libpcre anywhere under menuconfig, for installing the wget, the libpthead and libpcre is needed.

**Comment by crackself** [comment]
I guest you are doing complie some custom package  for openwrt,as i know gargoyle have not include all package from openwrt(unnecessary),but wget can be complie into firmware by edit config files.:
under # Network
# File Transfer
CONFIG_PACKAGE_wget=y

other package you need can add by yourself.but care about adding package into config file(confirm in it's Makefile),wrong position will break your complie.BTW,unnecessary package may conflict to Gargoyle.

**Comment by tacuar** [comment]
@crackself  i run make FULL_BUILD=true custom.

For original OPENWRT compiling, under menuconfig, the wget position is under: Network--->File Transfer, yes, correct.

But for GARGOYLE, there is no wget under Network--->File Transfer, instead, under Network, there is a "wget - default, with SSL" .

I want to add standard wget into the compiling, but don't know how.

**Comment by lantis1008** [comment]
It is part of busybox. 
CONFIG_BUSYBOX_DEFAULT_WGET=y

**Comment by lantis1008** [comment]
And the “default with ssl” IS standard wget. 
wget nossl is a variant
CONFIG_PACKAGE_wget-default
CONFIG_PACKAGE_wget-nossl
