### ISSUE TITLE
Ports table in Overview.sh being shown even with no ethernet cable attached

### ISSUE THREAD

**Issue by d3fz** [ericpaulbishop/gargoyle#708]
The title and screenshot pretty much say it all and it's probably just a minor cosmetic bug. I've noticed this a while ago when installing Gargoyle (1.9.2) on my Archer C7 for the first time, maybe 6 months ago. 

Latest build shows the same bug. Interestingly enough, I'm also running 1.10.x on a WR842ND, and there's no such problem (the table is hidden).
 
![359e286b-3509-4571-870a-aa04cad8b107](https://user-images.githubusercontent.com/22578839/34463943-c4d8c5f8-ee53-11e7-8b98-80f9fa774d44.png)

Can anyone else confirm this?

**Comment by lantis1008** [comment]
This is expected behaviour. It shows that there is nothing plugged in. 

It doesn’t show up on devices not defined in switchinfo.sh (which the wr842 is not).

**Comment by d3fz** [comment]
Thanks for clarifying.

Closing issue.
