### ISSUE TITLE
 Login page does not fully utilize the theme

### ISSUE THREAD

**Issue by WildRat** [ericpaulbishop/gargoyle#709]
![image](https://user-images.githubusercontent.com/1486048/34464001-7ba1f6c4-ee77-11e7-8134-7fc5b6079e49.png)
As you can see in the picture, not all elements use the selected theme.

**Comment by d3fz** [comment]
I'll take a look. 

All Gargoyle themes had to be fully converted when the GUI moved to Bootstrap not too long ago. Probably an element style was left out here and there. So feel free to test and report.

**Comment by WildRat** [comment]
Result of this patch looks OK.

**Comment by d3fz** [comment]
Good to know. I closed my PR temporarily as I'm doing some small tests. Should reopen it soon.

**Comment by WildRat** [comment]
Only don't like addition of ".page-header" to theme. It seems to me that without this everything looks better.

**Comment by d3fz** [comment]
No problem, I'll update the PR and revert this change in Dark One theme. Should be resolved when merged.

Thanks for the feedback.
