### ISSUE TITLE
The plug-in for sending e-mail messages does not work in 1.10 (both options).

### ISSUE THREAD

**Issue by WildRat** [ericpaulbishop/gargoyle#710]
The "Email notifications for Gargoyle" (either SSl or not) does not work in 1.10.

**Comment by d3fz** [comment]
Someone posted (Jul/17) on the forum about email not being sent as well. [See the post.](https://www.gargoyle-router.com/phpbb/viewtopic.php?f=14&t=7236&start=90#p46007)

> Just a small time-saving note for someone installing this for the first time.
If using smtp.gmail.com as the server,
and encryption = TLS,
then port 465 doesn't work
( daemon.err uhttpd[1865]: sendmail: could not send mail (account default from /etc/msmtprc))
have to set the port to 587. 

Is this related?

**Comment by WildRat** [comment]
No, on my system it looks like this:
![image](https://user-images.githubusercontent.com/1486048/34464079-1f790c18-ee7a-11e7-9fd5-0e25549f93e8.png)

**Comment by d3fz** [comment]
Is this error occurring with the latest build (31/Dec)? Some small changes were made to the email page layout, I'll have a look and see what's wrong.

Works fine on my end though: 
![bbd46623-ced3-4f60-9877-64278fc0f294](https://user-images.githubusercontent.com/22578839/34464136-7d47dc22-ee5a-11e7-8f03-164c3d743aff.png)

**Comment by lantis1008** [comment]
Bad gateway means malformed SH file or the language pack is stuffed.

**Comment by lantis1008** [comment]
Step 1 check that it works in English. Then compare the two language files to see what is wrong.

**Comment by d3fz** [comment]
I was checking exactly that just now. 

Right on, Lantis. Found the issue.

Latest change to email.js (Russian-RU) probably messed with UTF-8 BOM and broke the page.

**Comment by lantis1008** [comment]
In that case, the following should be checked 
Russian minidlna
English minidlna
As per the other commits in that change

**Comment by WildRat** [comment]
I not yet tested on 31.12.2017 version. It's don't work on version 1.10 prior to this commit.

**Comment by WildRat** [comment]
I tested, and all works on English. I will start correcting translation.

**Comment by d3fz** [comment]
> In that case, the following should be checked
Russian minidlna
English minidlna
As per the other commits in that change

Just checked this, and only `email.js` had the UTF-8 BOM (little red dot) removed. Adding it back solves the issue.

**Comment by lantis1008** [comment]
I might try writing some scripts later in the i18n-scripts folder to detect files without the BOM and have the option to fix them.

**Comment by WildRat** [comment]
I found some errors in translations files and created pull request.

**Comment by d3fz** [comment]
Those properties (.DataSettings, .Receipment*) that you've changed had already been addressed directly on `email.sh` page, and merged on this PR #706. So you can probably discard them, otherwise, it will break the English translation if merged.

*-> This one is misspelled indeed, I just left as it is to avoid having to correct every single i18n email file to go with it.

**Comment by WildRat** [comment]
Thank you, I corrected pull request.

**Comment by lantis1008** [comment]
@WildRat this should now be fixed. 
Please close
