### ISSUE TITLE
Wrong settings saving in email plugin.

### ISSUE THREAD

**Issue by WildRat** [ericpaulbishop/gargoyle#717]
"bandwidthIntervalSelect" and "count" is not save and load correctly/

**Comment by d3fz** [comment]
Could you please provide the steps you took and also a screenshot?

**Comment by WildRat** [comment]
When saving error in the function:
switch(interval){ on line 765 email.js
its always go to default.

When loading its:
switch(interval){ on line 945 email.js
this time switch works fine, but sets wrong value.

Problem in email.minutes e.t.c. vars.

**Comment by d3fz** [comment]
Does it work correctly when switching the language to English?

![a1317f63-eae1-44f0-944a-f13ec291387a](https://user-images.githubusercontent.com/22578839/34690777-97462cbc-f4a1-11e7-8f39-ff4c66d31c5c.png)

**Comment by WildRat** [comment]
Yes, its works OK on English setting.

**Comment by WildRat** [comment]
#718
I manage to correct this issue.
