### ISSUE TITLE
how to apply the fast-path patch of discent on tree "base_on_openwrt_remerge"

### ISSUE THREAD

**Issue by tacuar** [ericpaulbishop/gargoyle#737]
GARGOYLE is so nice and everytime it is updated to a new branch i would like to try it on.

One thing still puts me here is : how am i supposed to do if i want to apply the fast path shortcut-fe patch on this latest version of gargoyle after lede / openwrt remerge ?

Applying that patch on lede trunk is easy but don't know how to make it work on GARGOYLE ?

Hope to get your instruction

**Comment by tacuar** [comment]
i suppose the way of patching it on GARGOYLE source code would be quite different from on  LEDE

**Comment by lantis1008** [comment]
You need to slightly reformat the patch and put it in the Gargoyle "patches-generic" folder, but other than that it should be reasonably easy.

Using fast path will disable most of gargoyles features, just incase you had not realised.

**Comment by crackself** [comment]
Is that "base_on_openwrt_remerge" branch stable to use? This [patch](https://github.com/crackself/source/commit/11a3b6852e6037cb6d68e960a36ded0af8064125) from https://github.com/dissent1/r7800.git for kernel 4.4/4.9. Test on wndr4300, this patch can make a big improve for wireless transmission.

**Comment by lantis1008** [comment]
No it is still in development. I don't think it can be built properly yet. be patient...

**Comment by crackself** [comment]
Ok,if there need to test,noticed me,may be I can do some thing.

**Comment by tacuar** [comment]
base_on_openwrt_remerge  is being actively worked on, am i right?

**Comment by tacuar** [comment]
@lantis1008  master,i hope to get your instruction about how to slightly modify the patch.

what i do in lede now is as below:

wget https://github.com/lede-project/source/commit/b87b4734c6e56fa45ec612350e2aa480ed2d8dd6.patch
sed -i "s/hack-4.9/pending-4.9/g" b87b4734c6e56fa45ec612350e2aa480ed2d8dd6.patch
patch -p1 < b87b4734c6e56fa45ec612350e2aa480ed2d8dd6.patch

if i do it in gargoyle folder, may i know the exact operation?

**Comment by lantis1008** [comment]
Yes it is being worked on.

Name it "999-SFE.patch" and put it in "patches-generic"
Run the sed command on it to make patch work correctly and save it.

That's all that is required, the patch system will pick it up and apply it during build.
At the beginning of the build process you can see it succeeding/failing to apply gargoyle patches.

**Comment by tacuar** [comment]
@lantis1008 got it with many thanks and hope to have your finally official support someday : ) and better all will be compatible with qos and other things like bandwidth monitoring. 

at this moment i just want to try the speed improvements on wireless throughouts.
