### ISSUE TITLE
Compiling failed due to "690-imq.patch" faied

### ISSUE THREAD

**Issue by tacuar** [ericpaulbishop/gargoyle#738]
Applying /home/gargoyle/gargoyle/custom-src/target/linux/generic/hack-4.9/690-imq.patch using plaintext: 
patching file drivers/net/Kconfig
patching file drivers/net/Makefile
patching file drivers/net/imq.c
patching file include/linux/imq.h
patching file include/linux/netdevice.h
Hunk #1 succeeded at 3681 (offset 12 lines).
patching file include/linux/netfilter/xt_IMQ.h
patching file include/linux/netfilter_ipv4/ipt_IMQ.h
patching file include/linux/netfilter_ipv6/ip6t_IMQ.h
patching file include/linux/skbuff.h
Hunk #4 succeeded at 758 (offset 5 lines).
Hunk #5 succeeded at 920 (offset 4 lines).
Hunk #6 succeeded at 3624 (offset 11 lines).
patching file include/net/netfilter/nf_queue.h
patching file include/net/pkt_sched.h
patching file include/net/sch_generic.h
Hunk #1 succeeded at 519 (offset 1 line).
patching file include/uapi/linux/netfilter.h
patching file net/core/dev.c
Hunk #2 FAILED at 2909.
Hunk #3 succeeded at 2991 (offset 43 lines).
1 out of 3 hunks FAILED -- saving rejects to file net/core/dev.c.rej
patching file net/core/skbuff.c
Hunk #4 succeeded at 3580 (offset 9 lines).
patching file net/ipv6/ip6_output.c
patching file net/netfilter/Kconfig
Hunk #1 succeeded at 842 (offset 9 lines).
patching file net/netfilter/Makefile
Hunk #1 succeeded at 122 (offset 3 lines).
patching file net/netfilter/core.c
Hunk #1 succeeded at 360 with fuzz 1.
patching file net/netfilter/nf_queue.c
patching file net/netfilter/xt_IMQ.c
patching file net/sched/sch_generic.c
Patch failed!  Please fix /home/gargoyle/gargoyle/custom-src/target/linux/generic/hack-4.9/690-imq.patch!
Makefile:104: recipe for target '/home/gargoyle/gargoyle/custom-src/build_dir/toolchain-mipsel_24kc_gcc-5.5.0_musl/linux-4.9.77/.prepared' failed
make[4]: *** [/home/gargoyle/gargoyle/custom-src/build_dir/toolchain-mipsel_24kc_gcc-5.5.0_musl/linux-4.9.77/.prepared] Error 1
make[4]: Leaving directory '/home/gargoyle/gargoyle/custom-src/toolchain/kernel-headers'
toolchain/Makefile:96: recipe for target 'toolchain/kernel-headers/compile' failed
make[3]: *** [toolchain/kernel-headers/compile] Error 2
make[3]: Leaving directory '/home/gargoyle/gargoyle/custom-src'
toolchain/Makefile:94: recipe for target '/home/gargoyle/gargoyle/custom-src/staging_dir/toolchain-mipsel_24kc_gcc-5.5.0_musl/stamp/.toolchain_compile' failed
make[2]: *** [/home/gargoyle/gargoyle/custom-src/staging_dir/toolchain-mipsel_24kc_gcc-5.5.0_musl/stamp/.toolchain_compile] Error 2
make[2]: Leaving directory '/home/gargoyle/gargoyle/custom-src'
/home/gargoyle/gargoyle/custom-src/include/toplevel.mk:216: recipe for target 'world' failed
make[1]: *** [world] Error 2
make[1]: Leaving directory '/home/gargoyle/gargoyle/custom-src'

**Comment by tacuar** [comment]
the branch i used for compiling is /tree/base_on_openwrt_remerge

**Comment by lantis1008** [comment]
then you are on your own. 
This is an active development branch which is not even ready for beta testing yet. Eric is still doing the migration. 

You need to figure it out yourself, or be patient.

**Comment by lantis1008** [comment]
If you want to investigate it yourself, 010-imq.patch is where you need to look.

**Comment by lantis1008** [comment]
Yes but this will not let Gargoyle QOS work and may cause crashes due to missing modules.

**Comment by tacuar** [comment]
@lantis1008  but only this branch is based on lede master, am i correct?  the other latest stable branch is based on cc15.05.1?

**Comment by lantis1008** [comment]
Yes

**Comment by tacuar** [comment]
i checked the latest lede snapshot codes and under generic ---hack-4.9 ,there is no 690-imq.patch, then i simply guess this is unique to gargoyle ,but without this the firmware generated would still work. 
not very sure but i want the compiling to complete at this time, and of course i still will be patient for a error-free stable branch done by Eric.

**Comment by lantis1008** [comment]
690 is generated by 010 in the patches generic folder like I said above. 
Yes it is Gargoyle specific. 
It is tied into several features, I don’t know about the stability of the firmware without it.

**Comment by lantis1008** [comment]
Let alone the other instabilities in this early stage of development.

**Comment by tacuar** [comment]
got it now, but with this patch  at this moment it can't  be patched successfully and i don't know how to modify the patch by gargoyle.

however i will still be patient and keeps very keen on using gargoyle for my routers.
