### ISSUE TITLE
build origin/lede error

### ISSUE THREAD

**Issue by 4593645** [ericpaulbishop/gargoyle#741]
Setting target language

**************************************************************************
** node/npm not installed globally! Attempting to build them            **
**************************************************************************

uglifyjs ok!
Compressing Javascript files...
Done!
uglifycss ok!

**************************************************************************
** WARNING: Cannot compress css, uglifycss could not be installed       **
**************************************************************************

fetching openwrt source
Cloning into '/home/pi/git/gargoyle/downloaded/v17.01.2-2da512e'...
fatal: remote error: access denied or repository not exported: /v17.01.2/openwrt.git
ERROR: could not download source, exiting

**Comment by 4593645** [comment]
$make custome

Setting target language

**************************************************************************
** node/npm not installed globally! Attempting to build them            **
**************************************************************************

uglifyjs ok!
Compressing Javascript files...
Done!
uglifycss ok!

**************************************************************************
** WARNING: Cannot compress css, uglifycss could not be installed       **
**************************************************************************

fetching openwrt source
Cloning into '/home/pi/git/gargoyle/downloaded/v17.01.2-2da512e'...
fatal: remote error: access denied or repository not exported: /v17.01.2/openwrt.git
ERROR: could not download source, exiting

**Comment by lantis1008** [comment]
Are you seriously complaining that a development branch doesn’t work properly?
Debug it yourself, or be patient.

**Comment by 4593645** [comment]
I'm sorry, it doesn't mean that. I need help

**Comment by lantis1008** [comment]
Please avoid reporting bugs on that branch until it is ready for testing. At that stage I would be very appreciative of any bug reports you might send. 

Thank you.

**Comment by 4593645** [comment]
That branch is the 4 version of the kernel?

**Comment by lantis1008** [comment]
It is based on Openwrt, LEDE 17.01.4 at this state. 
So it will be based on kernel 4.4 and 4.9.

**Comment by 4593645** [comment]
I'm a beginner. It supports the use of Gargoyle and has been used for many years. Please tell me how to start this position to get git source code, how to debug error. Thank you very much

**Comment by lantis1008** [comment]
I’m not willing to support this branch until it is ready.

**Comment by 4593645** [comment]
Please tell us that the latest branch is that, so that I can learn.

**Comment by 4593645** [comment]
Get a branch version to perform an error；
$git checkout origin/1.8
$make custom

Setting target language
fetching openwrt source
svn: E000111: Unable to connect to a repository at URL 'svn://svn.openwrt.org/openwrt/branches/barrier_breaker'
svn: E000111: Can't connect to host 'svn.openwrt.org': Connection refused
ERROR: could not download source, exiting

**Comment by lantis1008** [comment]
Just checkout master and build 1.10.

**Comment by 4593645** [comment]
$git checkout 1.10.0
$make custom

uglifycss ok!

**************************************************************************
** WARNING: Cannot compress css, uglifycss could not be installed       **
**************************************************************************

fetching openwrt source
Cloning into '/home/pi/git/gargoyle/downloaded/15.05-216adcf'...
fatal: remote error: access denied or repository not exported: /15.05/openwrt.git
ERROR: could not download source, exiting

**Comment by lantis1008** [comment]
Checkout master...

**Comment by 4593645** [comment]
It's hard for you, God, to bless you！

**Comment by 4593645** [comment]
And one more question. How to start with the development of theme

**Comment by lantis1008** [comment]
Start with a working firmware installed on a router. 
Install an additional theme like Gargoyle Modern.
Modify the files for Gargoyle Modern until the theme is finished. Then package it up into a new theme package.

**Comment by 4593645** [comment]
Do you have any documents related , thanks

**Comment by lantis1008** [comment]
No.
You design the theme in situ on your router and when you are ready to finish it off you turn it into a package. 
The package bit I can assist with at the time, but the rest is up to you

**Comment by 4593645** [comment]
How to introduce packages, key locations such as development tools, how to introduce projects, directory locations, and so on. I am learning nodejs and other technology, whether it is helpful. Our technology is very poor, please enlighten.

**Comment by lantis1008** [comment]
This is outside the scope of GitHub. 
Can you please collate all of your questions in detail and post on the forum under the Development Forum
https://www.gargoyle-router.com/phpbb/viewforum.php?f=7

It can be discussed there in detail. 

Please close this issue.

**Comment by 4593645** [comment]
ok，thinks

**Comment by lantis1008** [comment]
As to why your uglifycss is not working, i expect your version of nodejs and/or npm is too old.
Please ensure you are using something around nodejs 6.13.1 and npm 3.10.10.
I have updated the wiki to reflect this.

https://www.gargoyle-router.com/wiki/doku.php?id=developer_documentation#building
