### ISSUE TITLE
KMOD-IPT-OFFLOAD

### ISSUE THREAD

**Issue by tacuar** [ericpaulbishop/gargoyle#743]
It seems openwrt is switching slowly to linux kernel 4.14.

And now besides fast-path (which is not official ), there is kmod-ipt-offload (official by openwrt) which can improve the NAT.

I suppose GARGOYLE could forget about the 4.4 / 4.9, AND directly switch to 4.14 ? Since OFFLOAD seems having the compatibility with original sqm qos, then we could forget about the fast path issue?

**Comment by lantis1008** [comment]
It doesn't work with QOS, that's the whole point.

**Comment by tacuar** [comment]
this OFFLOAD doesn't work with GARGOYLE QOS either?

......it is bad....

**Comment by lantis1008** [comment]
No, none of them will by design. Think about what it is trying to achieve :)

**Comment by tacuar** [comment]
but this offload can be shut down:

#start
iptables -I FORWARD 1 -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD
#stop
iptables -D FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j FLOWOFFLOAD

if it is shutting down, then gargoyle other features working without problem, right?

**Comment by lantis1008** [comment]
Yes, but then what is the point of including it?

If you are using it, the traffic won't be tracked and able to be used in QOS.
Even if you use it only for SOME traffic, how can you expect the rest of the systems to work properly when they can't see SOME of the traffic?

**Comment by tacuar** [comment]
the thing it is trying to achieve is making GARGOYLE / OP having an improvement of wireless downloading speed same as the commercial factory firmware with commercial driver ?

**Comment by lantis1008** [comment]
And how is it achieving that?? By bypassing as much of the network stack and iptables as possible.
The iptables is where QOS and BW Monitoring sit, and restricitons, etc etc

**Comment by tacuar** [comment]
what about using one main router with GARGOYLE with these nat acceleration modules shutting down, and other second router with gargoyle and these modules working? and the main router QOS can still work and control?

**Comment by lantis1008** [comment]
Then you won't gain anything?
You're just moving the bottleneck.

**Comment by tacuar** [comment]
i do not understand much because i'm not professional on this , only seeing a downloading speed improvment : ) then i come to you and see if this time this new module can work better than the previous fast path

**Comment by tacuar** [comment]
main router (wired only, not using wireless), the second router using as AP with wireless only
