### ISSUE TITLE
Best branch for new pull requests? 

### ISSUE THREAD

**Issue by d3fz** [ericpaulbishop/gargoyle#756]
Since the 1.11.X (**base_on_openwrt_remerge**) branch builds are still being classified as "Bleeding Edge" on the forums, is it safe to assume that the **master** branch is the most stable one? And the one I should choose when opening new pull requests? That way, users that are still not comfortable flashing the bleeding edge builds (for now) would still see some of the latest changes. 

I'm aware that recent work (bug fixes, new features) it's all being done on the other branch, that will most likely be the new master branch once everything is up and running smoothly. By the way, the OpenWRT/LEDE "remerge" already happened or it's still on the way?

**Comment by lantis1008** [comment]
In my opinion, PRs to the new branch should meet any of the following: 
- be directly related to the effort to rebase 
- rely on work already done as part of the rebase 
- cause an eventual conflict if not put on new branch

The last 2 points being reasonably similar. 

18.06 Openwrt is set to be branched this week (it was supposed to have happened already). I think waiting to release 1.11.0 based on that is wise. 
Openwrt site went down yesterday. Unsure if related.

**Comment by d3fz** [comment]
>18.06 Openwrt is set to be branched this week (it was supposed to have happened already). I think waiting to release 1.11.0 based on that is wise.

Well that's good news, didn't know that. Is there an link where I can follow further updates on this?

>Openwrt site went down yesterday. Unsure if related.

Just saw this on LEDE's forum, [Global openwrt.org DNS outage](https://forum.lede-project.org/t/global-openwrt-org-dns-outage/14185).

> In my opinion, PRs to the new branch should meet any of the following:
> - rely on work already done as part of the rebase

I guess this would be the case (slightly). Some small updates were made to some .sh files (header fix, etc) that I've already applied locally (among other fixes of my own), but weren't pushed to the master branch. I guess there wouldn't be any conflicts if merged.

**Comment by lantis1008** [comment]
You should leave the changes that aren’t in master out if possible otherwise they may cause a conflict (two people trying to do the same thing). 
Sometimes git is clever enough to auto resolve this but not always. 

http://lists.infradead.org/pipermail/lede-dev/2018-May/012134.html

**Comment by lantis1008** [comment]
Are we able to close this as resolved?

**Comment by ericpaulbishop** [comment]
I'm going to agree with Lantis and close this issue -- new changes should be based on the base_on_openwrt_remerge branch which will within the next month or so become the master.

**Comment by d3fz** [comment]
Thank you for the feedback.

Resolved.
