### ISSUE TITLE
Failed to connect to git.torproject.org port 443: Timed out

### ISSUE THREAD

**Issue by fengchen-github** [ericpaulbishop/gargoyle#757]
Cloning into 'C:\Users\GRG-Z\Documents\GitHub\obfsproxy-legacy'...
fatal: unable to access 'https://git.torproject.org/pluggable-transports/obfsproxy-legacy.git/': Failed to connect to git.torproject.org port 443: Timed out

**Comment by lantis1008** [comment]
Works fine for me

**Comment by fengchen-github** [comment]
May be caused by GFW.

**Comment by lantis1008** [comment]
Probably 👎 :(

**Comment by schuberng** [comment]
Hey dude, the same happened to me. Just use your system proxy if you are able to get access to YouTube. My solution is using command $ git config --global http.proxy 'socks5://127.0.0.1:[PORT_NUMBER]'. Here is the url for setting git config from stackoverflow. https://stackoverflow.com/questions/15227130/using-a-socks-proxy-with-git-for-the-http-transport
