### ISSUE TITLE
Reduce OpenWRT and Gargoyle dependance

### ISSUE THREAD

**Issue by lukasz1992** [ericpaulbishop/gargoyle#759]
Is it possible to reduce Gargoyle role, to just repository for OpenWRT packages?

I see some packages depend on OpenWRT OS, some other are additional kernel modules (IMQ, dropped Layer7, webmonitoring modules) and settings. I see that Gargoyle is also a set of scripts to prepare OpenWRT, compile it from scratch and do many expensive things. By expensive I mainly mean very long time needed to maintain it (at the moment of Gargoyle 1.10 release, CC branch was considered to be archive)

My idea: let's convert Gargoyle to just a repository, and produce images with OpenWRT ImageBuilder, because:
- It is provided as an easy solution to modify images without breaking binary compatibility (especially for kernel modules)
- We would fastly get support for many boards and porting new would not require much work
- We could easily get updates from OpenWRT,
- We could focus on new features or polish existing
- It could be much easier to maintain patches
- Gargoyle was always an overlay on OpenWRT (and I consider it a best UI)

What is a problem:
- A large work needed to be done at this moment (I consider 18.06 as a good point to start with):
1. Prepare patches for maintained kernels for IMQ support, some netfilter modules support
2. Review all patches and merge them in the special package (for example openwrt-gargoyle-support)
3. Drop all existing packages not directly related to gargoyle, and use OpenWRT replacements. If any package has no replacement, it could be renamed from <NAME> to <gargoyle-NAME>.
4. Drop existing configs/scripts; prepare scripts only for OpenWRT ImageBuilder and configs only for gargoyle-* packages
- some things that could not be done without heavy modification of OpenWRT - are there any?
- Test everything and release as Gargoyle 18.06

What do you think about my idea?

**Comment by ispyisail** [comment]
I'm not sure Gargoyle has enough developers for any major changes?

**Comment by lantis1008** [comment]
To be honest, this one is a bit of a pipe dream.
The only bit of this that is reasonably achievable is imagebuilder, but it would be a Gargoyle specific one.
