### ISSUE TITLE
Gargoyle m4 build fails with glibc 2.28

### ISSUE THREAD

**Issue by joequant** [ericpaulbishop/gargoyle#766]
Gargoyle is pulling in openwrt 18.06 toolchain, and the m4 in that chain is broken in glib 2.2
Here is the m4 patch necessary to fix

https://src.fedoraproject.org/rpms/m4/raw/814d592134fad36df757f9a61422d164ea2c6c9b/f/m4-1.4.18-glibc-change-work-around.patch

**Comment by joequant** [comment]
bison-3.0.4 is also broken with glibc 2.28

**Comment by joequant** [comment]
https://forum.openwrt.org/t/tools-bison-lib-fseterr-c-build-problems-on-18-06-0-due-to-glibc-2-28-changes/18926/2

**Comment by joequant** [comment]
findutils also affected

**Comment by lantis1008** [comment]
Patch is already upstreamed. I’ll pull it in. Please close.

**Comment by joequant** [comment]
thanks!!!
