### ISSUE TITLE
kernel-nfs-server build fails mysterously when cpp is not present

### ISSUE THREAD

**Issue by joequant** [ericpaulbishop/gargoyle#767]
I ran into a mysterous error when building gargoyle-router.  What ended up happening was that when cpp is not present, rpcgen creates a bad header file when nfs-utils is built, and the build stops with mysterous undefined symbol errors.

Don't know how to fix it, but I'd like to put in this report just in case someone else runs into the same problem.

Also nfs-utils needs to be updated to newer versions.

**Comment by lantis1008** [comment]
What kind of build environment are you using that CPP is missing?

**Comment by joequant** [comment]
What happened was that I updated gcc and gcc was symlinked to the right place, but cpp wasn't.
This turns out to be a broken environment, but the issue was that the build didn't fail in anything related to cpp.  rpcgen produced a syntatically correct header file, and the build failed with not being about to build the nfs-server.
It may be that the error is too obscure to be worth fixing the build environment, but the main reason for posting the report is so that someone can pick up the problem if they put in the google terms.

**Comment by joequant** [comment]
Yeah sure.  Will repost it as a "gotcha" in the development forums.
