### ISSUE TITLE
gcc 8.1.0 and binutils 2.31.1

### ISSUE THREAD

**Issue by joequant** [ericpaulbishop/gargoyle#770]
Here are some experiences trying to build gargoyle with gcc 8.1.0 and binutils 2.31.1
Updating openwrt to master of 20 August 2018 picks up the changes, and setting the config variables in the target/config to use gcc 8.1.0 and binutils 2.31.1 works.

The big issue is that the binaries for 8.1.0 are larger and so right now the build tries to build a lot of 8M and 4M images for openwrt which fail, and that prevents the gargoyle images from getting built.

**Comment by joequant** [comment]
Yeah.  It makes more sense to post this on the forum.  Will close the issue and then repost on the forum :-)

As far as why I'm doing this, it's because I like to live on the bleeding edge.

**Comment by lantis1008** [comment]
I understand that, and your knowledge gained by doing so is definitely very useful to the community and to the developers. Please discuss them on the forum for everyone’s benefit. Not many people view GitHub from the community :(
