### ISSUE TITLE
 Bison compile on glibc 2.28 still broken in openwrt 18.06.1

### ISSUE THREAD

**Issue by joequant** [ericpaulbishop/gargoyle#771]
Hi,  two previous glibc 2.28 problems with m4 and findutils were fixed by updating to openwrt 18.06.1

However, bison is still failing.  There is a patch that fixes the problem that can be applyed by hand from the head of openwrt, but it hasn't made it into a release yet.

https://forum.openwrt.org/t/tools-bison-lib-fseterr-c-build-problems-on-18-06-0-due-to-glibc-2-28-changes/18926

**Comment by lantis1008** [comment]
Is this still an issue? If not, please close.

**Comment by lantis1008** [comment]
ping @joequant
