### ISSUE TITLE
Does qos support ipv6 now?

### ISSUE THREAD

**Issue by fengchen-github** [ericpaulbishop/gargoyle#778]
Does qos support ipv6 now?
@lantis1008 @ericpaulbishop

**Comment by lantis1008** [comment]
No

**Comment by fengchen-github** [comment]
I tested on intel j1900 version base_on_openwrt_remerge download speed only 60~70Mbps with qos enable(cpu load 30%） , but it is 120~130Mbps with qos disable.

**Comment by lantis1008** [comment]
I’ve reported this previously. I’ve also taken a look myself but I wasn’t able to fix it. 
It doesn’t affect the operation at all and for all intents and purposes, you may ignore the crash.

**Comment by lantis1008** [comment]
your second question is now fixed. please close @fengchen-github
