### ISSUE TITLE
Title of management pages should say something relevant

### ISSUE THREAD

**Issue by wodim** [ericpaulbishop/gargoyle#782]
Right now the title of every management page says "Gargoyle Router Management Utility". It would be much more useful if it said, for example, "Connected Hosts - Gargoyle Router Management Utility"

**Comment by lantis1008** [comment]
All pages have the title at the top of the body. What use case do you have for it to be in the title bar as well?

**Comment by wodim** [comment]
When I have several tabs of my the configuration interface open it's
impossible to know which is which.

**Comment by lantis1008** [comment]
Gargoyle is not recommended for use in multiple windows/tabs due to the high risk of data corruption. This is a (well documented) limitation at this time.

**Comment by wodim** [comment]
Yes, I know Gargoyle's configuration interface is buggy. That should not be
an excuse not to improve it; if anything, it should be an excuse to improve
it. My suggestion is an easy to implement improvement.

**Comment by lantis1008** [comment]
Sure, i take your point.
As it doesn't handle multiple tabs/windows properly at the moment, having them identified as such is not high on my priority list. I'll return to this in the future unless someone fixes it sooner.

Thanks

**Comment by wodim** [comment]
I understand. Thank you for your work. Have a nice day.

**Comment by lantis1008** [comment]
I was making changes in the related code, so managed to get this one in.
Please close as of #784
