### ISSUE TITLE
Navigation sidebar funky resize in Safari

### ISSUE THREAD

**Issue by lpla** [ericpaulbishop/gargoyle#802]
I was navigating Gargoyle 1.11 release with a Safari browser on my Macbook Pro and this happened:

[Imgur](https://i.imgur.com/FY6mXfB.mp4) (couldn't make it to preview here)

I didn't see any error or warning in browser console

EDIT: this weird 'half-collapsing' only happens on first click on any sidebar link. And tested on latest Chrome and Firefox and it doesn't happen

**Comment by lantis1008** [comment]
Thanks for the recording, that makes it pretty obvious what is going on.
Unfortunately, I can't reproduce this behaviour on my local machine. Can you please provide more details about what version of Safari you are using and on what OS?

**Comment by lpla** [comment]
Yep, sure. Latest version of all, Safari (12.0.3) and Mojave (10.14.3)

**Comment by lantis1008** [comment]
Struggling to test this one at the moment sorry. The only Mac I have access to is too old and can’t be updated past Sierra.

Do you have any experience in web development that you might be able to observe what is changing yourself?
The most likely culprit is a css class being assigned/revoked.

If not, I’ll hsve to put this one on the back burner and come back to it in the future.

**Comment by lpla** [comment]
No problem! I am not an expert in CSS or web design/frontend in general, but I think I can try to debug this if you think that the problem is there. I'll let you know if I find anything!

**Comment by lpla** [comment]
First of all, I tried to update boostrap.min.css, to see if this fixes this bug. And nope, still unfixed, but as a side issue maybe the default Gargoyle theme should have an updated boostrap to avoid unpatched CVEs (see https://github.com/twbs/bootstrap/releases/tag/v3.4.1)

Then, I tried to compare the CSS element inspector with Chrome, and tested disabling some properties, but nothing really worked. 

If you have any suggestion, I am open to test it as soon as possible.

And I also reduced the problem path to a CSS problem because it still happens after disabling javascript and many other options from Developer menu in Safari.

**Comment by lantis1008** [comment]
I haven't been able to reproduce this error on any systems. Unless someone else can confirm or you can provide the reason it is behaving strangely, i can't do anything about this issue for you.

I have updated Bootstrap, however Gargoyle does not use either of the modules listed in the CVE and therefore was not vulnerable to begin with.

**Comment by lpla** [comment]
Sure. I will test today again after latest Mojave and Safari update. Furthermore, in case you built (or going to) another release with these changes I could test it also to confirm all combinations.

**Comment by lpla** [comment]
Tested again with my Mac, OS X 10.14.4 (18E226) and Safari 12.1 (14607.1.40.1.4) and still persists.

Gargoyle Version:1.11.0
Model:TP-Link TL-WR1043N/ND v2

If I have time I will make my own build with latest master commit and test, as I did not find the issue debugging CSS. If you want to close the issue because you can't reproduce and no one blamed about this, I will understand.

**Comment by lantis1008** [comment]
I can't close the issue, only you can. So it stays open as long as you would like it to.
That being said, unless i can reproduce it, it's going to drop off my radar of things to look at.

**Comment by lpla** [comment]
Tested latest build from ispyisail (April 13th) and still happens. I will research further when I have time.

**Comment by lantis1008** [comment]
I just setup a macOS Mojave (10.14.4) with Safari 12.1 (14607.1.40.1.4) and still can't reproduce this.
Are you using any extensions at all?

**Comment by lpla** [comment]
None, using exactly the same versions as you. Are you clicking on the sidebar elements? Even the actual page element produces the effect. This gif shows the clicks: https://imgur.com/a/O3cPEQ8

**Comment by lantis1008** [comment]
This is what i've done.
https://imgur.com/a/t0kG6z1

**Comment by lpla** [comment]
Mmm, so weird. I will close the issue because it looks unreproducible, and probably related to my setup only, as no one else blamed about this. Thanks for taking your time testing this.

**Comment by lantis1008** [comment]
That’s alright. Please reopen it if you discover new information. 
Even if you find out what is different about your setup it would be helpful to know also. 

Thanks
