### ISSUE TITLE
Switch to ath10k-ct firmware

### ISSUE THREAD

**Issue by lantis1008** [ericpaulbishop/gargoyle#806]
@obsy 
Thoughts on moving targets to ath10k-ct firmware?
This is what upstream is doing. Reports seem ok from forum (rocky start, but ok now).
I don't have any devices so not able to test and don't really have an opinion.

**Comment by obsy** [comment]
https://forum.openwrt.org/t/why-the-switch-to-unstable-ath10k-ct/27258/45

For some people *-ct drivers is less stable. I didn't use them for long time so I cannot say anything about their stability. I will ask  question on my forum.

**Comment by obsy** [comment]
https://eko.one.pl/forum/viewtopic.php?pid=217765#p217765

It is not good results.

**Comment by lantis1008** [comment]
Ok. I think revisit in a few months. 
Ath10k CT is receiving regular development. 

Maybe when I branch for 19.xx I’ll include it to see. Can always switch back

**Comment by RomanHK** [comment]
I'll also join. I tested on my turris Omnia "OpenWrt Development Snapshot builds", which uses ath10k-ct + firmware-qca988x-ct and I confirm instability, still disconnecting WiFi (the only advantage - it works LED activity). Now I use Gargoyle with ath10k + firmware-qca988x, no errors and good transfer speed.
