### ISSUE TITLE
Forum PM issue

### ISSUE THREAD

**Issue by lantis1008** [ericpaulbishop/gargoyle#818]
Hi @ericpaulbishop ,
Something might be wrong with the forum PM system.
Please see attached error message when clicking on PM links.

@RomanHK I did not receive your latest PM, please just make a post in the forum. 

![85D182C7-5E6B-49F8-9285-0B574E210FE3](https://user-images.githubusercontent.com/10367653/57819472-eb39a200-77cb-11e9-9d16-c2eb464baf29.png)

**Comment by ispyisail** [comment]
The whole site might be down, I can't connect

https://www.gargoyle-router.com/

**Comment by ericpaulbishop** [comment]
Oops, server ran out of disk space. I just deleted some large and
unncessary log files, site should be back up. Looking into the PM issue now.

Eric

**Comment by ericpaulbishop** [comment]
I couldn't reproduce any issues with the PMs... this may also be related to
the disk space issue I just fixed. Please let me know if this persists and
I will look into it further.

Eric

**Comment by lantis1008** [comment]
PM issue looks related, as it is now fixed. 
Thanks Eric!
