### ISSUE TITLE
default timeserver setting seems duplicate

### ISSUE THREAD

**Issue by crackself** [ericpaulbishop/gargoyle#825]
there‘s  [019-start_sysntpd_sooner.patch](https://github.com/ericpaulbishop/gargoyle/blob/master/patches-generic/019-start_sysntpd_sooner.patch) for modify openwrt default timeserver.Besides, gargoyle package have [configration](https://github.com/ericpaulbishop/gargoyle/blob/master/package/gargoyle/files/etc/uci-defaults/gargoyle-init) also make change of this
```# add new busybox ntp system section if necessary
ntp_section=$(uci get system.ntp 2>/dev/null)
if [ "$ntp_section" != "timeserver" ] ; then
	uci del system.ntp 2>/dev/null
	uci set system.ntp="timeserver"                 2>/dev/null
	uci add_list system.ntp.server="0.pool.ntp.org" 2>/dev/null
	uci add_list system.ntp.server="1.pool.ntp.org" 2>/dev/null
	uci add_list system.ntp.server="2.pool.ntp.org" 2>/dev/null
fi
```
should we remove one ?

**Comment by lantis1008** [comment]
Yes probably can remove the one in uci defaults.
If you want to test no regression on initial flash/sysupgrade (preserved and unpreserved) and make a PR i'll be happy to merge it.
