### ISSUE TITLE
dhcp.lan.ignore is always set to 0

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#844]
https://github.com/ericpaulbishop/gargoyle/blob/d8b3cc58f7413b7b5e974e79f06713310e3531e8/package/gargoyle/files/www/js/basic.js#L124

"LAN DHCP Server Enabled" is ALWAYS enabled after saving changes, even if it was previously turned off. This should stay disabled if was disabled.

**Comment by lantis1008** [comment]
Are there cases where we want this behaviour to protect the user? Just trying to think if there needs to be a sophisticated solution.

**Comment by obsy** [comment]
Simple scenario - router is used as stupid AP, with dhcp server disabled. I don't want the dhcp server to turn on every time I save the settings.

**Comment by lantis1008** [comment]
Sorry I meant the previous behaviour where it always turned back on.
So for example should we always leave the setting alone when setting Connect Via Disabled, and otherwise turn it on?
Are there additional scenarios?

**Comment by obsy** [comment]
Don't bind this to connection type. If this option is available in gui, code should respects user settings. If it was disabled, should be disabled.

**Comment by lantis1008** [comment]
I am looking at this now. I think we should enable it by default in the case where the old connection type was bridge, and we are now going to gateway.
All other scenarios it will be left alone.

Is this a good compromise?

**Comment by obsy** [comment]
Only if we switch from bridge to gateway, yes.

**Comment by ispyisail** [comment]
I also had problem with this. 

So many times I had 2 DHCP servers because gargoyle would auto turn back on. I was sure I had turned if off. 

I'm with obsy it should obey what was set.

**Comment by lantis1008** [comment]
I've resolved this on both 1.12 and 1.13, please check and close if you are satisfied.

**Comment by obsy** [comment]
No.
On default settings - uncheck dhcp server, save, go to basic configuration, click save. DHCP server is now enabled (should be disabled as was previously disabled)

See first post - line 124 enables dhcp server unconditionally.

**Comment by ispyisail** [comment]
agree with obsy

If they lock them self out then failsafe reset.

**Comment by lantis1008** [comment]
Sorry, yes line 124 was supposed to come out as well. I'll fix that.

**Comment by lantis1008** [comment]
How about now...

**Comment by obsy** [comment]
Better...

**Comment by lantis1008** [comment]
@obsy please close when you have time
