### ISSUE TITLE
broken URL: gui, connection, tor; "visible in the global list" - blutmagie.de has moved.

### ISSUE THREAD

**Issue by littlegreenrock** [ericpaulbishop/gargoyle#847]
broken URL: gui, connection, tor; "visible in the global list" - blutmagie.de has moved.

```
				<div id='tor_relay_status_link_container' class="row form-group">
					<span class='col-xs-12'>Within 1-2 hours of activating your relay, it should be visible <a href="http://torstatus.blutmagie.de/">in the global list</a></span>
				</div>

```

the link in the GUI at that location points to http://torstatus.blutmagie.de/
which was correct and working up until 2 months ago (Dec1999).  It appears that the site has moved to https://torstatus.rueckgr.at/index.php

This 'appears' to be confirmed here at Dr. Paul Staroch's site https://paul.staroch.name/en/
and also here https://rueckgr.at/

to be thorough, I see that he has made changes on his github recently for the torstatus project
https://github.com/paulchen/torstatus

**Comment by lantis1008** [comment]
Thanks, i'll fix this over the weekend.

**Comment by lantis1008** [comment]
Fixed in:
1.13.x (853f3feb4e9dd0c5a849c71ac5055222b44539b8)
1.12.x (71545b6163e79b428e376e34fdfffb073dc95456)

Please close issue.

**Comment by lantis1008** [comment]
ping @littlegreenrock. Now fixed in master.
