### ISSUE TITLE
[RFC] Time zone setting

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#853]
About: https://github.com/ericpaulbishop/gargoyle/blob/master/package/gargoyle/Makefile#L77

1. on modern OpenWrt etc/config/system does not exist (created from script) and and generates warnings creating images
`cat: build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/target-dir-d17b3c6f/etc/config/system: No such file or directory
`
2. Can we leave it on UTC?

IMO lines 77-78 should be removed

**Comment by lantis1008** [comment]
I think that is fine. So system config must be generated at firstboot now?

**Comment by obsy** [comment]
By config_generate, yes.
