### ISSUE TITLE
Update logic

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#855]
![a](https://user-images.githubusercontent.com/695356/75621254-1c843280-5b92-11ea-89c7-1c2bee10f906.png)

Uploaded random file (NOT firmware). "Firmware matches device" should be set to No.

**Comment by lantis1008** [comment]
Hmm. That surprises me. I'll check it out.

**Comment by lantis1008** [comment]
Can you provide a sample file please @obsy ?
I can't reproduce this by uploading all sorts of different files (jpegs, txt files, html pages etc.)

Or is there a sequence of events that need to occur first? Maybe a variable is not being reset.

**Comment by obsy** [comment]
Sure: https://we.tl/t-FVa5VUEFmH this zip (don't unzip it). Tested on today snapshot on qemu (x86/64).

**Comment by obsy** [comment]
```
root@Gargoyle:/# ls -al /tmp/up/upgrade 
-rw-------    1 root     root        181712 Mar  1 10:14 /tmp/up/upgrade
root@Gargoyle:/# cd /tmp/up
root@Gargoyle:/tmp/up# ls
fwtool.json                   hash.sha256
hash.md5                      upgrade
hash.sha1                     validate_firmware_image.json
root@Gargoyle:/tmp/up# cat fwtool.json 
root@Gargoyle:/tmp/up# cat validate_firmware_image.json 
{ "tests": { "fwtool_signature": true, "fwtool_device_match": true }, "valid": false, "forceable": true, "allow_backup": true }

```

**Comment by lantis1008** [comment]
So the hint is the x86 target.
The logic is difficult to trace, but it essentially boils down to this check:
https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=package/base-files/files/lib/upgrade/fwtool.sh;hb=0493d57e04774d47921a7d2014b567455d5dc16b#l32
The x86 target does not set "REQUIRE_IMAGE_METADATA", and therefore returns 0 at line 38, signalling that the device match is true.

I'm honestly not sure whether to do anything about this or not. The logic is "working", and we still provide a warning to the user.

This may be a bug report for upstream?

**Comment by obsy** [comment]
Ok, leave it as is.
