### ISSUE TITLE
  Time adjustment cron  didn't work ？

### ISSUE THREAD

**Issue by livepu** [ericpaulbishop/gargoyle#864]
I haven't been in router management for a long time. Found that the time is not accurate, changed the time server. Save the updated time.
now see the read log show it:

> Wed Mar 18 18:42:08 2020 kern.warn kernel: [262107.498071] ipt_bandwidth: backwards time shift detected, adjusting
> Wed Mar 18 18:42:46 2020 cron.err crond[9966]: time disparity of -598 minutes detected

but the corn is here:

> root@Gargoyle:/etc/crontabs# cat root
> 0,1,11,21,31,41,51 * * * * /usr/bin/set_kernel_timezone >/dev/null 2>&1
> * * * * * if [ -z "$(ifconfig | grep tun 2>/dev/null)" ] ; then logger "openvpn stopped, restarting" ; /etc/init.d/openvpn restart ; fi
> 0 0,4,8,12,16,20 * * * /tmp/bw_backup/do_openvpn_bw_backup.sh
> 0 0,4,8,12,16,20 * * * /tmp/bw_backup/do_bw_backup.sh

**Comment by lantis1008** [comment]
I don't see a problem here? Or am i not understanding what your question is?
cron is just telling you there was a time adjustment.

If your time was not being kept accurate, your issue is with ntpd.

**Comment by lantis1008** [comment]
If you are saying that there was an unusually large gap between when you adjusted the time, and when the set_kernel_timezone event ran, then in this case it is hard to determine as cron also was not following the correct time.
This event is also taken care of as part of the bandwidth monitoring iptables module, so as long as that is running it should be caught within a reasonable time period.

**Comment by livepu** [comment]
I found that cron works.

> 
>  -rw-r--r--    1 root     root           673 Mar 18 20:00 bdist4-download-day-31.bw
> -rw-r--r--    1 root     root           673 Mar 18 20:00 bdist4-upload-day-31.bw
> -rw-r--r--    1 root     root          1367 Mar 18 20:00 bdist5-download-month-12.bw
> -rw-r--r--    1 root     root          1367 Mar 18 20:00 bdist5-upload-month-12.bw
> -rw-r--r--    1 root     root            58 Mar 18 20:00 openvpn-hr1-download-2-449.bw
> -rw-r--r--    1 root     root            58 Mar 18 20:00 openvpn-hr1-upload-2-449.bw
> -rw-r--r--    1 root     root            58 Mar 18 20:00 openvpn-hr2-download-minute-359.bw
> -rw-r--r--    1 root     root            58 Mar 18 20:00 openvpn-hr2-upload-minute-359.bw
> -rw-r--r--    1 root     root          2614 Mar 18 20:00 openvpn-hr3-download-180-479.bw
> -rw-r--r--    1 root     root            58 Mar 18 20:00 openvpn-hr3-upload-180-479.bw
> -rw-r--r--    1 root     root          1162 Mar 18 20:00 openvpn-hr4-download-7200-359.bw
> -rw-r--r--    1 root     root          1162 Mar 18 20:00 openvpn-hr4-upload-7200-359.bw
> -rw-r--r--    1 root     root           150 Mar 18 20:00 openvpn-hr5-download-day-365.bw
> -rw-r--r--    1 root     root           150 Mar 18 20:00 openvpn-hr5-upload-day-365.bw
> -rw-r--r--    1 root     root            58 Mar 18 20:00 openvpn-lr1-download-minute-15.bw
> -rw-r--r--    1 root     root            58 Mar 18 20:00 openvpn-lr1-upload-minute-15.bw
> -rw-r--r--    1 root     root            58 Mar 18 20:00 openvpn-lr2-download-900-24.bw
> -rw-r--r--    1 root     root            58 Mar 18 20:00 openvpn-lr2-upload-900-24.bw
> -rw-r--r--    1 root     root           126 Mar 18 20:00 openvpn-lr3-download-hour-24.bw
> -rw-r--r--    1 root     root            58 Mar 18 20:00 openvpn-lr3-upload-hour-24.bw
> -rw-r--r--    1 root     root           150 Mar 18 20:00 openvpn-lr4-download-day-31.bw

-rw-r--r--    1 root     root           150 Mar 18 20:00 openvpn-lr4-upload-day-31.bw
-rw-r--r--    1 root     root            62 Mar 18 20:00 openvpn-lr5-download-month-12.bw
-rw-r--r--    1 root     root            62 Mar 18 20:00 openvpn-lr5-upload-month-12.bw
-rw-r--r--    1 root     root          1170 Mar 18 20:00 total4-download-7200-359.bw
-rw-r--r--    1 root     root          1170 Mar 18 20:00 total4-upload-7200-359.bw
-rw-r--r--    1 root     root          1134 Mar 18 20:00 total5-download-day-365.bw
-rw-r--r--    1 root     root          1134 Mar 18 20:00 total5-upload-day-365.bw

**Comment by lantis1008** [comment]
Can you clarify what it is you're having trouble with?

**Comment by livepu** [comment]
I overtook the route and found that the clock was moving fast. But the time synchronization function is not adjusted normally.

**Comment by lantis1008** [comment]
Check NTPD. It is the function which keeps system time in check.

**Comment by livepu** [comment]
The ntpd process is running, but there is no synchronization time. Only restart every time.
> root@Gargoyle:~# top | grep "ntpd"
> 24571     1 root     S<    1212   1%   0% /usr/sbin/ntpd -n -N -l -S /usr/sbin/n
> 25606 24507 root     S     1208   1%   0% grep ntpd

**Comment by livepu** [comment]
the last ,I find this 
https://github.com/openwrt/openwrt/pull/1551
