### ISSUE TITLE
plugin-gargoyle-cron

### ISSUE THREAD

**Issue by livepu** [ericpaulbishop/gargoyle#872]
I found an old plugin. https://github.com/Mari00/gargoyle-plugins/tree/master/plugin-gargoyle-cron
But the version is very long, can you update to a new version? I think this must be a very good plugin.

**Comment by lantis1008** [comment]
Ok, but it needs significant updating. I will do it later unless someone picks it up before.

**Comment by livepu** [comment]
Thank you very much.

**Comment by lantis1008** [comment]
I'll merge into master in about a week.
You can cherry pick the following if you need it sooner:
https://github.com/lantis1008/gargoyle/commit/f0a4976aeec5375d85868c738d1a0b1dbf0b349f
https://github.com/lantis1008/gargoyle/commit/10dbc652a6166360a1ee94d79d4e48ec0a8c1b94
https://github.com/lantis1008/gargoyle/commit/5762ade33566ef10679c574cdf4dba4b1e06574d

**Comment by livepu** [comment]
Excited, grateful

**Comment by livepu** [comment]
I test it found some bug
`0,1,11,21,31,41,51 * * * *  /usr/bin/set_kernel_timezone >/dev/null 2>&1
edit show min 0~5 is selected.

**Comment by lantis1008** [comment]
fixed https://github.com/ericpaulbishop/gargoyle/commit/2d01037a0c863f0518d51d85e7450cf7dc266a23

**Comment by livepu** [comment]
The test works well
