### ISSUE TITLE
MT7620 NAND support

### ISSUE THREAD

**Issue by michaelfsantos** [ericpaulbishop/gargoyle#875]
Is there a plan to add NAND support for Mediatek MT7620?
There is already a project (X-WRT) that adds this support to OpenWRT: https://github.com/x-wrt/x-wrt/commit/2f3e8a5cf973a074011ee81ee22d11a102efa787
I have some Xiaomi MiWiFi R3 (same as Xiaomi MiWiFi Mini but uses NAND and not SPI) with console access that I could use for testing.

**Comment by obsy** [comment]
"Rebuilt WiFi modules", not NAND support...

**Comment by michaelfsantos** [comment]
> "Rebuilt WiFi modules", not NAND support...

Sorry, have posted the wrong link... :/
Have updated my post above.

**Comment by lantis1008** [comment]
I'd prefer to see this done upstream and then revisit it. 
Has OpenWrt adopted this patch?

**Comment by michaelfsantos** [comment]
> I'd prefer to see this done upstream and then revisit it.
> Has OpenWrt adopted this patch?

I do not know why the OpenWrt did not added support for NAND on Mediatek and do not known if they will add it in the future. This is why there is this fork (X-Wrt) that supports it. There is also Padavan and PandoraBox, but I think both use the proprietary drivers from Mediatek. Because X-Wrt is mainly for the Chinese market, it would be great if Gargoyle can support it. I think it wouldn't be so difficult, because in the example I gave, the Xiaomi MiWiFi Mini is already supported (using SPI) and the Xiaomi MiWiFi R3 has the same hardware (only difference: it uses NAND and not SPI).

**Comment by lantis1008** [comment]
I am not interested in maintaining out of tree device support sorry, particularly for something I don't own and therefore can't guarantee compatibility moving forward.

Chase it up with OpenWrt, and reopen the issue if they adopt support.

**Comment by lantis1008** [comment]
If there aren't any further developments, please close @michaelfsantos .
If OpenWrt adopts support in the future, feel free to raise a new issue or reopen this one.
