### ISSUE TITLE
[1.13] Wan mac location

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#878]
https://github.com/ericpaulbishop/gargoyle/blob/master/package/gargoyle/files/www/js/basic.js#L1677

In openwrt 19.07 wan mac section is not wan_dev but wan_{ifname_with_underscore}_dev. Ex. for Netgear r6220:

```
config device 'wan_eth0_2_dev'
	option name 'eth0.2'
	option macaddr 'XX:XX:XX:XX:XX:XX'
```

**Comment by lantis1008** [comment]
Do you have a corresponding OpenWrt commit that changed this? I haven't ever seen this format. 
What device was it on?

**Comment by obsy** [comment]
In ex. Netgear R6220. 
See https://github.com/openwrt/openwrt/commit/a2d9de21b841ab641c81cf3f6f9eb53e7bbf4a6b#diff-e6d37eeaad10eab440857b39e3ee9b05

**Comment by lantis1008** [comment]
Wow. When will they leave this one alone? Thanks i will look at making some changes around this.
Do you have a device to test any changes?

**Comment by obsy** [comment]
Yes.

**Comment by lantis1008** [comment]
Hey @obsy , can you please test the following patch?
Patch is based on ipv6 branch so line numbers may not line up, but easy to apply by hand.
```diff
--- a/package/gargoyle/files/www/js/basic.js
+++ b/package/gargoyle/files/www/js/basic.js
@@ -1744,4 +1744,5 @@
 function resetData()
 {
-	wanMacLoc = uciOriginal.get("network","wan_dev") != "" ? "wan_dev" : wanMacLoc;
+	wanMacAltLoc = defaultWanIf != "" ? ("wan_" + defaultWanIf.replace(".","_") + "_dev"): "wan_dev";
+	wanMacLoc = uciOriginal.get("network",wanMacAltLoc) != "" ? wanMacAltLoc : wanMacLoc;
 	var removeChannels = [];
```

**Comment by obsy** [comment]
Yes it works. Sets the mac in the correct section.
