### ISSUE TITLE
[firewall/port open] - cannot save rule

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#886]
![a](https://user-images.githubusercontent.com/695356/84696056-287edf00-af4c-11ea-850b-2556aef0a814.png)

Cannot save rule - "there is an error in IP"

**Comment by lantis1008** [comment]
Port opening is IPv6 only.
Port forwarding is used for IPv4

**Comment by obsy** [comment]
Ok, so the "IP" string should be changed to IPv6?

**Comment by lantis1008** [comment]
For clarity, yes it should :smile:

**Comment by lantis1008** [comment]
Fixed as of https://github.com/ericpaulbishop/gargoyle/commit/29dd18d6fb370d84bf2f0700a7ce75352175df49

**Comment by obsy** [comment]
QOS Upload, edit default default rule - service class is populated many times.

![Zrzut ekranu z 2020-07-05 15-50-19](https://user-images.githubusercontent.com/695356/86534296-a85af200-bed7-11ea-9ea0-b6037dc0b8c2.png)

**Comment by lantis1008** [comment]
Thanks can reproduce. Will look.

**Comment by lantis1008** [comment]
Fixed as of https://github.com/ericpaulbishop/gargoyle/commit/43495cc0d8eb22912d1fb8b931a2a7c19cfb8443
