### ISSUE TITLE
dnsmasp show A lot of repeated errors

### ISSUE THREAD

**Issue by livepu** [ericpaulbishop/gargoyle#898]
> Fri Nov 20 19:10:12 2020 daemon.info dnsmasq[19693]: read /etc/hosts - 2 addresses
> Fri Nov 20 19:10:12 2020 daemon.info dnsmasq[19693]: read /tmp/hosts/odhcpd - 2 addresses
> Fri Nov 20 19:10:12 2020 daemon.info dnsmasq[19693]: read /tmp/hosts/dhcp.cfg01411c - 2 addresses
> Fri Nov 20 19:10:12 2020 daemon.err dnsmasq-dhcp[19693]: failed to read /etc/ethers: No such file or directory
> Fri Nov 20 19:10:23 2020 daemon.info dnsmasq[19693]: read /etc/hosts - 2 addresses
> Fri Nov 20 19:10:23 2020 daemon.info dnsmasq[19693]: read /tmp/hosts/odhcpd - 4 addresses
> Fri Nov 20 19:10:23 2020 daemon.info dnsmasq[19693]: read /tmp/hosts/dhcp.cfg01411c - 2 addresses
> Fri Nov 20 19:10:23 2020 daemon.err dnsmasq-dhcp[19693]: failed to read /etc/ethers: No such file or directory
> Fri Nov 20 19:10:24 2020 daemon.info dnsmasq[19693]: read /etc/hosts - 2 addresses
> Fri Nov 20 19:10:24 2020 daemon.info dnsmasq[19693]: read /tmp/hosts/odhcpd - 2 addresses
> Fri Nov 20 19:10:24 2020 daemon.info dnsmasq[19693]: read /tmp/hosts/dhcp.cfg01411c - 2 addresses
> Fri Nov 20 19:10:24 2020 daemon.err dnsmasq-dhcp[19693]: failed to read /etc/ethers: No such file or directory
> Fri Nov 20 19:10:35 2020 daemon.info dnsmasq[19693]: read /etc/hosts - 2 addresses
> Fri Nov 20 19:10:35 2020 daemon.info dnsmasq[19693]: read /tmp/hosts/odhcpd - 4 addresses
> Fri Nov 20 19:10:35 2020 daemon.info dnsmasq[19693]: read /tmp/hosts/dhcp.cfg01411c - 2 addresses
> Fri Nov 20 19:10:35 2020 daemon.err dnsmasq-dhcp[19693]: failed to read /etc/ethers: No such file or directory
> Fri Nov 20 19:10:36 2020 daemon.info dnsmasq[19693]: read /etc/hosts - 2 addresses

**Comment by lantis1008** [comment]
Which version of Gargoyle and can you provide your DHCP config

**Comment by livepu** [comment]
the newest master for 1.13

**Comment by lantis1008** [comment]
It looks like you tried to keep your settings? We don't use /etc/ethers anymore.

**Comment by lantis1008** [comment]
Either way you can ignore it it shouldn't cause any issues

**Comment by livepu** [comment]
I updated from 1.12 to 1.13 (Master) without retaining the settings. But I don't know why the error was not found after the system was rebooted.
