### ISSUE TITLE
plugin usb storage: gui glitches

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#904]
Current master:

----
1. fresh install, add new user: aaa, pass: bbb, click add
2. header is ok, 3 columns with "user" in first
3. save changes, select other menu, back to "usb storage". Header "user" is disappear and now header has 4 columns

---
1. Click "add user",  3 fields. 
2. Click "Cancel"
3. Click "edit" on aaa user
4. Click "Close and discard changes"
5. Click "add user" again. Field "new user" is now disabled, cannot add new user

---
1. Remove "aaa" user
2. Clock "add user"
3. Field "new user" still disabled

**Comment by lantis1008** [comment]
Thanks, I couldn't reproduce the 3rd issue, i believe it was solved as part of fixing the second one.
