### ISSUE TITLE
What is the firmware output directory

### ISSUE THREAD

**Issue by ledewrt** [ericpaulbishop/gargoyle#912]
with github compilation, I can not find the firmware。in openwrt，clone path is openwrt（git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt），openwrt Output path after compilation is：openwrt/bin/targets。

the error at Organize File is：
Run rm -rf ./firmware/
find: ‘openwrt/bin/targets/*/*’: No such file or directory
find: ‘openwrt/bin/targets/*/*’: No such file or directory
find: ‘openwrt/bin/targets/*/*’: No such file or directory
find: ‘openwrt/bin/targets/*/*’: No such file or directory
find: ‘openwrt/bin/targets/*/*’: No such file or directory
find: ‘openwrt/bin/packages/*/*’: No such file or directory

so，gargoyle output path is what? thanks

**Comment by lantis1008** [comment]
`images/<target>`
`built/<target>`

As per the documentation in the wiki 
https://www.gargoyle-router.com/wiki/doku.php?id=developer_documentation

It may be worth reviewing this information, as the Gargoyle build process is slightly different to OpenWrt. 

If this solves your problem, please consider closing the issue.

**Comment by ledewrt** [comment]
thanks
