### ISSUE TITLE
[RFC] Use virtual "provides" for Gargoyle packages

### ISSUE THREAD

**Issue by lantis1008** [ericpaulbishop/gargoyle#915]
For several packages we rely on freezing a certain version of a dependent package.
For example, gargoyle-plugin-email relies on msmtp, which has been (minorly) modified to symlink to "sendmail" which is then used by Gargoyle. 

If the user instead installs upstream msmtp, this plugin would break (discounting the PR from Cezary currently). This can happen inadvertently, unexpectedly, and without the user realising. 

The proposal is to use PROVIDES to ensure that Gargoyle packages get installed in preference to upstream options. 
E.g. msmtp in Gargoyle repo:
PROVIDES:=msmtp-gargoyle
And plugin-gargoyle-email
DEPENDS+=msmtp-gargoyle

The downside of this approach is that the user now has no option to install upstream packages where a newer version may be available without modifying the source. 
This approach therefore may only be appropriate in some cases.

Thoughts and comments welcome.

**Comment by obsy** [comment]
+1
