### ISSUE TITLE
adblock: Could Not Fetch URL

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#920]
ewget has problem downloading first list

```
root@Gargoyle:~# ewget http://winhelp2002.mvps.org/hosts.txt
Could Not Fetch URL
root@Gargoyle:~# ewget https://winhelp2002.mvps.org/hosts.txt
Could Not Fetch URL

```

**Comment by lantis1008** [comment]
I think i've tracked this down to the fact that ewget doesn't support SNI.
I'm going to try and add support for this in and it should fix this problem and also a lot of the ddns urls not working as well.

**Comment by obsy** [comment]
Or.. use tools from openwrt - uclient-fetch with libustream-openssl?

**Comment by lantis1008** [comment]
I didn't want to cut ewget out of the firmware, but it is an option
