### ISSUE TITLE
JS files not minified on Archer C2600 (ipq806x) using 1.13.X factory image

### ISSUE THREAD

**Issue by d3fz** [ericpaulbishop/gargoyle#924]
After flashing Gargoyle for the first time on a C2600, using the factory image from [1.13.X (Built 20210126-1716 git@0c75cab9) build](https://www.gargoyle-router.com/phpbb/viewtopic.php?f=14&t=12896), I've noticed that none of the JS files in `www/js` were minified. But all CSS files in `www/themes` were (but not `theme.js`).

After that, I did a clean sysupgrade using the image from [1.13.X (Built 20210319-0339 git@396836cd) build](https://lantisproject.com/gargoyle_custom/1.13.x/ipq806x/gargoyle_1.13.x-ipq806x-generic-tplink_c2600-squashfs-sysupgrade.bin
), and all JS/CSS files were minified, as expected. Including `theme.js`.

Did a quick folder size comparison on `www/js` afterwards, and I was really impressed to see that the changes from #860 made a ~370kB difference in size. That's quite a lot, actually.

Nice!

**Comment by lantis1008** [comment]
Hey, i'm not seeing this on the latest builds, factory or sysupgrade.
I'd suggest that this isn't an error and more an artifact of one of the community builds "build environment".

**Comment by d3fz** [comment]
I understand.

Thank you for your feedback.

Closing issue.
