### ISSUE TITLE
openPopupWindow still is used :)

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#935]
openPopupWindow function is removed by https://github.com/ericpaulbishop/gargoyle/pull/822 but it still exists in bandwidth.js :)

**Comment by olekstomek** [comment]
I can confirm problem on Gargoyle 1.13 and Gargoyle 1.12.

> Uncaught ReferenceError: openPopupWindow is not defined
>     at expand (bandwidth.js)
>     at HTMLSpanElement.onclick (bandwidth.sh:337)

**Comment by lantis1008** [comment]
Apologies for any inconvenience caused. I also backported it to 1.12 (if that is at all useful) and will ensure it will be brought forward into 1.15
