### ISSUE TITLE
WNDR4300 WAN port is limited to 100Mb

### ISSUE THREAD

**Issue by dengxinggao** [ericpaulbishop/gargoyle#947]
gargoyle_1.13.0-ar71xx-nand-wndr4300-ubi-factory.img
wan port link:1000Mbps,
ethtool eth0：1000Mbps
but is limited to 100Mb.
Test other firmware up to 400Mb.
QOS is not enabled。

**Comment by lantis1008** [comment]
Hi,
Please try
/etc/init.d/bwmon_gargoyle stop

then test again and report back.

**Comment by dengxinggao** [comment]
> From 70Mbps to 170Mbps, but not to 300Mbps

**Comment by lantis1008** [comment]
Do you have “enforce DHCP assignments” on? Try with it off. 

Ultimately your CPU is not fast enough to handle the traffic AND do all of the things Gargoyle is asking of it. There’s no magic fix for this. 
There will be a future effort to improve the performance of the bandwidth monitoring tool, but I wouldn’t expect miracles sorry.

At this stage I can only suggest you ask less of the router, or get a more powerful one.

**Comment by dengxinggao** [comment]
Is there a recommended route?

**Comment by lantis1008** [comment]
If you have a look through the forums you will find some suggestions. 
Commonly, Linksys wrt series, Netgear R7800 or custom x86

**Comment by dengxinggao** [comment]
thank
