### ISSUE TITLE
Enable TP-Link TL-WR710N for Gargoyle 1.14 or later

### ISSUE THREAD

**Issue by sheilbronn** [ericpaulbishop/gargoyle#948]
After having a successful build of Gargoyle 1.13 for the small travel router TL-WR710N v2.1 it is suggested to enable it for standard build in one of the next Gargoyle releases.

Links:

1. Forum post: https://www.gargoyle-router.com/phpbb/viewtopic.php?p=60691#p60691
2. Collected manual build instructions/notes on Github: [https://github.com/sheilbronn/Gargoyle-for-TL-WR710N](https://github.com/sheilbronn/Gargoyle-for-TL-WR710N)

According to the [OpenWrt description of the TL-WR710N](https://openwrt.org/toh/tp-link/tl-wr710n) the V1 and V2.1 are very similar, but for the sake of quality one could consider enabling only a V2.1 build...

**Comment by obsy** [comment]
Or ... drop script for a custom button and compile a gargoyle for all devices on that platform.

**Comment by lantis1008** [comment]
You can propose a patch if you like? I'm not opposed to it. I am not sure of the history of the custom button handler.

**Comment by sheilbronn** [comment]
> Or ... drop script for a custom button and compile a gargoyle for all devices on that platform.

I'm not sure what both of you are referring to regarding a "custom button script/handler" ?! Could you please elaborate? 

To me, compiling the _ath79_ architecture for one or two more targets contained in the _usb_ profile seems to be easiest solution.)

**Comment by sheilbronn** [comment]
Closed, as recommended above.
