### ISSUE TITLE
Saving IPv6 suffix in DHCP

### ISSUE THREAD

**Issue by mickeyreg** [ericpaulbishop/gargoyle#954]
Hi,

If DHCP server for IPv6 is configured then I can write IPv6 Suffix in the form "::32". With this short sufix everything works fine, value 32 is saved to configuration file. But if I want to set "::32:32" than value 3232 is written to the configration file. If I really want to set this value I need to write "::32:0032". It could be acceptable, but when the configuration file is read, then value 320032 is read properly and in the form text "::32:32" is displayed and after saving it is coverted to 3232 so after the next read in the form we have "::3232". I hope somebody understood me :)

Ok. I wanted to try change it alone and I changed the file _/www/js/dhcp.js_ in my router. On GitHub it is the file: _/package/gargoyle/files/www/js/dhcp.js_. I've changed (lines 79-82):

```
if(hostid != "-")
{
	uci.set("dhcp",cfgid,"hostid",hostid.replace(/:/g,""));
}
```

to:

```
if (hostid != "-") {
	var elements = hostid.split(":");
	var idlen = elements.length;
	if (idlen == 4) {
		ucihostid = elements[2] + ("0000" + elements[3]).slice(-4);
	} else {
		ucihostid = hostid.replace(/:/g, "");
	}
	uci.set("dhcp", cfgid, "hostid", ucihostid)
}
```

Maybe it does not look well, but seems to work properly :)

Regards,
Mickey

**Comment by lantis1008** [comment]
Thanks very much for reporting this and providing a solution!
