### ISSUE TITLE
where did arpnat goes?

### ISSUE THREAD

**Issue by rhjdvsgsgks** [ericpaulbishop/gargoyle#961]
hi

seems like arpnat patch disappeared after v1.10 . is it been deprecated or have some successor to it? i need this feature to setup my wired network environment. after some search i found that gargoyle have it. and planing to move from openwrt to gargoyle. but seems been removed?

regards

**Comment by lantis1008** [comment]
Hi, it is replaced by relayd.
https://openwrt.org/packages/pkgdata/relayd
https://openwrt.org/docs/guide-user/network/wifi/relay_configuration

The Gargoyle GUI is configured just as before (with some subnet changes). The user doesn't need to know what happens behind the scenes.
Thanks
