### ISSUE TITLE
[devel][plugin-gargoyle-diagnostics] Bug...

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#964]
Please... data should be validated.

![image](https://user-images.githubusercontent.com/695356/211198606-e3d8c52c-7e26-4945-98c9-9baae9f3ac8e.png)

**Comment by lantis1008** [comment]
I'll put in a fix. User already has full control of the router in this case anyway, but I agree I should do better there.

**Comment by lantis1008** [comment]
Can you please check this solves the problem?
https://github.com/ericpaulbishop/gargoyle/commit/0b904cc87df5234375b0ac77a9fc61f5639179bf

**Comment by obsy** [comment]
Yes, looks good.
