### ISSUE TITLE
[1.13/1.15] Error adding ftp users with the same permission

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#976]
Very old bug, exists in 1.13 and 1.15, and probably earlier.
- system/usb storage
- click "add user" add aaa with password aaa, click add. User apper in gui, ok,
- click "add shared disk",
- select disk/directory etc,  AND: 
-- CIFS/FTP Anonymous Access: Read/Write
-- CIFS/FTP Users With Access: select aaa, with read only, click add 
- click add, and save changes on main screen. 

vsftpd config:
```
root@Gargoyle:/# cat /etc/config/vsftpd 

config share 'share_1'
	option name 'share_1'
	option share_dir '/tmp/usb_mount/9df0e1ab-02/tmp/a1'
	list users_rw 'anonymous'
	list users_ro 'aaa'

config vsftpd 'global'
	option anonymous 'yes'
	option anonymous_write 'yes'
	option pasv_min_port '50990'
	option pasv_max_port '50999'
```

Back to usb storage, edit Currently Shared Disks, Remove aaa user and add again but with read/write. Click close and apply changes,  click save changes.

vsftpd config:

```
root@Gargoyle:/# cat /etc/config/vsftpd 

config share 'share_1'
	option name 'share_1'
	option share_dir '/tmp/usb_mount/9df0e1ab-02/tmp/a1'
	list users_rw 'anonymous'

config vsftpd 'global'
	option anonymous 'yes'
	option anonymous_write 'yes'
	option pasv_min_port '50990'
	option pasv_max_port '50999'
```

Missing list users_rw 'aaa' in config. If anonymous user selected with rw permission, then it is impossible to add new user with the same (r/w) permission.

**Comment by lantis1008** [comment]
I was trying to replicate this on 1.15, and i can see the same config behaviour, but I can't actually establish an FTP connection to the server. Were you able to at least login?

**Comment by obsy** [comment]
Yes, ftp itself works fine. I checked on a virtual machine.

**Comment by lantis1008** [comment]
Ok maybe a windows issue. Will test from another system

**Comment by lantis1008** [comment]
Issue appears to be with vsftpd 3.0.3 and x64 systems. I found a workaround. Now building 3.0.5 as i believe it has been fixed there. 
Then I will look at this issue :)
