### ISSUE TITLE
x86 ，only one lan port？one wan port？

### ISSUE THREAD

**Issue by dengxinggao** [ericpaulbishop/gargoyle#979]
my x86 router have 4 port。
how to add LAN port？

**Comment by obsy** [comment]
Add eth1/eth2 etc to lan bridge.

**Comment by lantis1008** [comment]
This should happen automatically as per this script 

https://github.com/ericpaulbishop/gargoyle/blob/master/targets/x86/patches/50-x86setup.patch

It would be good to know why it did not work for you.

**Comment by dengxinggao** [comment]
I used other methods to solve this problem in PVE.
![image](https://user-images.githubusercontent.com/35987500/221402030-fd93cfa3-f32a-4ee2-b50a-f9b162e75edf.jpeg)

**Comment by lantis1008** [comment]
Out of curiosity, can you please supply
`cat /proc/net/dev`
