### ISSUE TITLE
Gargoyle 1.4 - qutoas others (individual ) dont work

### ISSUE THREAD

**Issue by ewcorek** [ericpaulbishop/gargoyle#991]
Hi Router asus ax1800u, 
after installing gargoyle 1.14
found out that  Quotas for other(individual) dont work.

see logs

Wed Nov 29 10:15:08 2023 daemon.info dnsmasq[30331]: read /tmp/hosts/odhcpd - 1 addresses
Wed Nov 29 10:15:15 2023 kern.info kernel: [47090.395187] do_page_fault(): sending SIGSEGV to iptables for invalid write access to 00000000
Wed Nov 29 10:15:15 2023 kern.info kernel: [47090.403732] epc = 77e1c4c8 in libc.so[77deb000+a9000]
Wed Nov 29 10:15:15 2023 kern.info kernel: [47090.408830] ra  = 77e1ca38 in libc.so[77deb000+a9000]
Wed Nov 29 10:15:15 2023 kern.info kernel: [47090.439808] do_page_fault(): sending SIGSEGV to ip6tables for invalid write access to 00000000
Wed Nov 29 10:15:15 2023 kern.info kernel: [47090.448585] epc = 77e214c8 in libc.so[77df0000+a9000]
Wed Nov 29 10:15:15 2023 kern.info kernel: [47090.453642] ra  = 77e21a38 in libc.so[77df0000+a9000]
Wed Nov 29 10:15:16 2023 daemon.err uhttpd[3167]: Error: There is no such init script like 'miniupnpd'.
Wed Nov 29 10:15:46 2023 kern.info kernel: [47122.035313] do_page_fault(): sending SIGSEGV to iptables for invalid write access to 00000000
Wed Nov 29 10:15:46 2023 kern.info kernel: [47122.043854] epc = 77de94c8 in libc.so[77db8000+a9000]
Wed Nov 29 10:15:46 2023 kern.info kernel: [47122.049236] ra  = 77de9a38 in libc.so[77db8000+a9000]
Wed Nov 29 10:15:46 2023 kern.info kernel: [47122.080072] do_page_fault(): sending SIGSEGV to ip6tables for invalid write access to 00000000
Wed Nov 29 10:15:46 2023 kern.info kernel: [47122.088708] epc = 77e0a4c8 in libc.so[77dd9000+a9000]
Wed Nov 29 10:15:46 2023 kern.info kernel: [47122.093784] ra  = 77e0aa38 in libc.so[77dd9000+a9000]
Wed Nov 29 10:15:47 2023 daemon.err uhttpd[3167]: Error: There is no such init script like 'miniupnpd'.
Success

**Comment by lantis1008** [comment]
Can you please detail what type of quota was applied?
Ingress, egress or combined?

**Comment by ewcorek** [comment]
Combined ( others, individual)

**Comment by lantis1008** [comment]
Sorry for not being clear, I need the details of:
- Max Upload
- Max Download
- Max Up + Down
- Quota Resets
- etc.
- When exceeded
- etc.

These options all cause it to go down different code paths and will help me narrow down the issue faster.
That being said, I may not be able to delve into this deeply until Christmas.

**Comment by ewcorek** [comment]
hi just checked all other quotas work, ok, combined, 

see attached reply to your question
![Screenshot 2023-11-29 124412](https://github.com/ericpaulbishop/gargoyle/assets/152382983/e8c81ee4-6577-4a96-886d-ea7c0bde270d)

**Comment by lantis1008** [comment]
Thanks for reporting this. It is now fixed as of ab2fd33.
