### ISSUE TITLE
Problem with Quotas in 1.14

### ISSUE THREAD

**Issue by mswit82** [ericpaulbishop/gargoyle#997]
The problem occurs when QoS is enabled. No traffic is sent to the "upload" class created for throttling purposes (with any quotas rule). All traffic goes to the default queue. The "Download" section appears to be working. (Static throttling when QoS is disabled does not work in both directions.)

**Comment by lantis1008** [comment]
Please post your configuration that reproduces this issue.

**Comment by mswit82** [comment]
Default installation on Edgerouter X, I also checked on x86. The same problem that did not occur in the previous version. I create one additional class in both the "upload" and "download" sections where I want to direct the throttled traffic. Then only the "download" section works correctly.
It doesn't matter what type of "quota" is selected, in the "upload" direction the traffic to be throttled, goes to the default "normal" class.

**Comment by lantis1008** [comment]
I’ve been able to reproduce both issues. 
I have a fix for both but I need to do a bit more testing.

**Comment by mswit82** [comment]
Thank you. I'm surprised no one noticed this in the current version. I hope to restore full functionality in a future version.

**Comment by lantis1008** [comment]
This should now be fixed. Unfortunately you will need to recompile the firmware to enjoy the full fix.
If you just want to quickly fix the QoS issue, you can just delete or comment out the two lines in /etc/init.d/qos_gargoyle as per here:
https://github.com/lantis1008/gargoyle/commit/dab78a4944da75011919b66688b13d1d5c965fb8#diff-8118e97b6791398a6984a4e87b7b0a57e95cbd5bc76af63990ff8528a153d935L512-L513

To fix the throttling without using QoS classes, you need to install sched-prio which you won't be able to do as it is a kernel module so must recompile. In addition there are changes to restore_quotas application.
