### ISSUE TITLE
Temat: Garygole  1.14.0.2 (Built 20231226-1035 git@8e210b77) Cudy x6 v2 Firewall -> transfer limit

### ISSUE THREAD

**Issue by Ludwis77** [ericpaulbishop/gargoyle#998]
Hi

I set a transfer limit on IP (1GB = plus the time range when it works organically) and additionally set that when the limit is exceeded, the transfer should be limited to sending and receiving 150KB/s

Even though the settings are saved, the router does not limit the speed to a given device when the data limit is reached

When trying to force the limit via QoS - after saving the settings in transfer limits and reopening them, the status changes after exceeding the limits and changed to "block all Internet connections"

Thank you in advance for your suggestions

**Comment by lantis1008** [comment]
The first half of your query has been solved in the last 24-48 hours, please see Issue #997 (which was also reported by a user from your forum). 

Can you please explain the second part of your problem please? A picture might help to understand.

**Comment by lantis1008** [comment]
I think maybe both of your issues are solved already, if you could check and come back that would be great.

**Comment by lantis1008** [comment]
If you could confirm your issue is resolved and close it that would be great thank you @Ludwis77

**Comment by Ludwis77** [comment]
New Built 1.14.0.3 fix problem
